---
config:
  theme: dark
---

flowchart TD

    retrieve_the_fallen_weapon[Retrieve the Fallen Weapon]
    click retrieve_the_fallen_weapon callback "
        Retrieve the Fallen Weapon<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Melee: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Exalted may use the bonds that form between a
        weapon and its wielder to call his chosen implement of battle
        to his hand. This Charm can overcome friction and gravity to
        carry the weapon through the air to the character but cannot
        defeat doors, chains and other such substantial hindrances.
        The character must have his weapon hand empty and must be
        able to see the weapon in order to call it to himself. The
        character must have used the weapon and be familiar with it
        to use this Charm on it — it must be his weapon.
        "

    call_the_blade[Call the Blade]
    retrieve_the_fallen_weapon --> call_the_blade
    click call_the_blade callback "
        Call the Blade<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Melee: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Retrieve the Fallen Weapon<br>
        <br>
        The character may call her weapon back to her hand, even
        if she cannot see it. The weapon does not traverse the space
        between its location and the character's hand, it simply flashes into
        her grasp. The call of this Charm reaches only (10x the character's
        Essence) yards, if the weapon is farther than that, the Charm will
        fail. As with Retrieve the Fallen Weapon, the character cannot use
        this power to steal weapons, only to call her own weapon to her.
        "

    summoning_the_loyal_steel[Summoning the Loyal Steel]
    call_the_blade --> summoning_the_loyal_steel
    click summoning_the_loyal_steel callback "
        Summoning the Loyal Steel<br>
        <br>
        Cost: 1 mote to summon or banish<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Melee: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Call the Blade<br>
        <br>
        The character simply gestures, and his weapon flashes to
        his hand, appearing instantly in his grasp regardless of its
        previous location. A character who is holding his weapon can
        also banish it, spending a mote of Essence to place it Elsewhere.
        Weapons that have been placed Elsewhere are gone from the
        world and can only be reached by their Exalted owner through
        the use of Summoning the Loyal Steel. The Exalted must have
        "

    glorious_solar_saber[Glorious Solar Saber]
    call_the_blade ---> glorious_solar_saber
    click glorious_solar_saber callback "
        Glorious Solar Saber<br>
        <br>
        Cost: 5 motes + 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Melee: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Call the Blade<br>
        <br>
        The character can now never be disarmed. She can
        concentrate Essence in her hand, forming a glittering
        golden blade of pure magical energy that does a base lethal
        damage equal to the character's Strength plus her Essence
        score. The blade glows brightly enough to light an area
        three or four yards across. Each Exalted's blade is different,
        perfectly matching her personality and fighting style.<br>
        <br>
        Errata:<br>
        The Saber has a Speed of +3, and an Accuracy and Defense of +1 each.
        "

    iron_raptor_technique[Iron Raptor Technique]
    retrieve_the_fallen_weapon -----> iron_raptor_technique
    click iron_raptor_technique callback "
        Iron Raptor Technique<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Melee: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Retrieve the Fallen Weapon<br>
        <br>
        This Charm allows the character to use his weapon to
        attack up to Dexterity x 5 yards away. The weapon whirls
        through the air to its strike its target, like a bloodthirsty, metal
        bird of prey, and then spins obediently back to the wielder's
        hand. The character attacks with his Melee pool, as usual, and
        the damage is determined using his Strength as if it was anormal
        Melee attack. Iron Raptor attacks can be blocked like normal
        Melee attacks. Botched Iron Raptor attacks can result in stuck
        or lost weapons or injury to the Exalted using the Charm.
        "

    sandstorm_wind_attack[Sandstorm-Wind Attack]
    iron_raptor_technique --> sandstorm_wind_attack
    click sandstorm_wind_attack callback "
        Sandstorm-Wind Attack<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Melee: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Iron Raptor Technique<br>
        <br>
        The character charges his weapon with Essence and
        strikes a blow at a distant target. A slashing edge of concentrated
        force leaps from the weapon and races toward the target.<br>
        The character attacks with his Dexterity + Melee dice pool and
        does a base lethal damage of his Strength + his Essence. The
        Sandstorm-Wind Attack is blocked as a ranged attack, not as
        a Melee attack. Sandstorm-Wind Attack can strike characters
        up to (10 x the character's Essence) yards away.
        "

    edge_of_morning_sunlight[Edge of Morning Sunlight]
    iron_raptor_technique --> edge_of_morning_sunlight
    click edge_of_morning_sunlight callback "
        Edge of Morning Sunlight<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Melee: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Iron Raptor Technique<br>
        <br>
        The character concentrates on manifesting his Essence
        through the medium of his weapon. The weapon
        becomes invested with Solar power and is highly effective
        against creatures of darkness, the undead and the Abyssal
        Exalted. The weapon adds the character's Essence to its
        regular damage when used against such creatures.
        "

    corona_of_radiance[Corona of Radiance]
    edge_of_morning_sunlight --> corona_of_radiance
    click corona_of_radiance callback "
        Corona of Radiance<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Melee: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Edge of Morning Sunlight<br>
        <br>
        The character channels Essence through her body, using
        her weapon as an aggressive focus. Her flesh coruscates with
        flickering Solar energy, and attacks against her by undead,
        creatures of the night and Abyssal Exalted are at + 1 difficulty.
        In addition, if such creatures strike her without using a
        weapon, they must soak aggravated damage equal to the
        character's Essence. While Corona of Radiance is active, the
        Exalted's attacks against such creatures do aggravated damage
        and have a damage bonus equal to the character's Essence.<br>
        <br>
        Errata:<br>
        The description of this Charm mentions the Charm “Solar Blaze”. That’s what Corona of Radiance was
        before the name changed.
        "

    blazing_solar_bolt[Blazing Solar Bolt]
    sandstorm_wind_attack --> blazing_solar_bolt
    corona_of_radiance --> blazing_solar_bolt
    click blazing_solar_bolt callback "
        Blazing Solar Bolt<br>
        <br>
        Cost: 3 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Melee: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Corona of Radiance, Sandstorm-Wind Attack<br>
        <br>
        The character channels pure Solar Essence though herself,
        focusing it with her will and through the medium of her
        weapon. A powerful lance of energy leaps between the Solar's
        Caste Mark, her weapon and the target. The character makes
        an attack with her Dexterity + Melee dice pool, which cannot
        be blocked or dodged without the use of Charms. The attack
        does lethal damage and has a base damage of the Exalted's
        Strength + her Willpower. Against inhabitants of Malfeas and
        the Underworld, Blazing Solar Bolt inflicts aggravated damage.
        "
