---
config:
  theme: dark
---
flowchart TD

    salty_dog_method[Salty Dog Method]
    click salty_dog_method callback "
        Salty Dog Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: One day<br>
        Type: Reflexive<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        While this Charm remains in effect, it gives the
        character perfect sea legs. While the Charm lasts, the
        character will not lose his balance or footing, even on the
        most storm-tossed ship, though collisions and so forth may
        still require Dexterity + Athletics rolls. Characters using
        this Charm will not become seasick, even on rough seas.
        "

    shipwreck_surviving_stamina[Shipwreck-Surviving<br>Stamina]
    salty_dog_method --> shipwreck_surviving_stamina
    click shipwreck_surviving_stamina callback "
        Shipwreck-Surviving Stamina<br>
        <br>
        Cost: 5 motes<br>
        Duration: One day<br>
        Type: Reflexive<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        A character using this Charm can survive indefinitely
        in water. She will never tire from treading water and may
        drink seawater without ill effect. She is protected from
        sunburn and other exposure effects and can hold her
        breath for up to five minutes per point of Stamina. This
        Charm does nothing to ward off hostile sea life, nor does it
        protect a character from inclement weather.
        "

    perfect_reckoning_technique[Perfect Reckoning<br>Technique]
    salty_dog_method --> perfect_reckoning_technique
    click perfect_reckoning_technique callback "
        Perfect Reckoning Technique<br>
        <br>
        Cost: 4 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        Through the use of this Charm, the character may
        learn exactly where her ship lies in relation to landmarks
        and locations she already knows. This knowledge allows
        her to pinpoint her location, but only in regard to known
        landmarks. The Charm does not allow the character to
        indirectly divine the local geography by sensing her distance
        from previously uncharted reefs or lost islands.
        "

    weather_anticipating_intuition[Weather-Anticipating<br>Intuition]
    perfect_reckoning_technique --> weather_anticipating_intuition
    click weather_anticipating_intuition callback "
        Weather-Anticipating Intuition<br>
        <br>
        Cost: 6 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Perfect Reckoning Technique<br>
        <br>
        By placing her finger in the water, the character can
        instantly predict future weather for a number of days equal
        to the Chosen's permanent Essence. The only thing that
        will cause this forecast to err is the influence of powerful
        magic changing the weather - this Charm will foresee
        even freak squalls and unexpected fogs.
        "

    depth_plumbing_intuition[Depth-Plumbing<br>Intuition]
    perfect_reckoning_technique --> depth_plumbing_intuition
    click depth_plumbing_intuition callback "
        Depth-Plumbing Intuition<br>
        <br>
        Cost: 4 motes<br>
        Duration: One scene<br>
        Type: Reflexive<br>
        Minimum Sail: 4<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Perfect Reckoning Technique<br>
        <br>
        By feeling the Essence flows in the world around
        him, the character can sense the depth of the water for
        (100 x his Essence rating) yards. This knowledge allows
        him to discern harbor channels, sense reefs and so on.
        Note that awareness of a hazard doesn't necessarily mean
        that the character's ship is agile or well-handled enough
        to avoid the obstacle.
        "

    wind_defying_course_technique[Wind-Defying<br>Course Technique]
    salty_dog_method --> wind_defying_course_technique
    click wind_defying_course_technique callback "
        Wind-Defying Course Technique<br>
        <br>
        Cost: 6 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        A character using this Charm while aboard a ship can
        tack much more closely to the wind than would be normal
        for his ship and rigging. Ships affected by this Charm
        cannot sail directly into the wind, but they can sail very
        near to it and, in general, handle more lightly and responsively
        than normal. Aside from additions to maneuverability
        and speed, which vary from ship to ship, the pilot may add
        the Essence rating of the character invoking the Charm to
        her Dexterity + Sail for ship handling. A ship that has had
        multiple Exalted use this Charm on it only benefits from
        the character with the highest Essence score.
        "

    storm_weathering_essence_infusion[Storm-Weathering<br>Essence Infusion]
    wind_defying_course_technique --> storm_weathering_essence_infusion
    click storm_weathering_essence_infusion callback "
        Storm-Weathering Essence Infusion<br>
        <br>
        Cost: 6 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Sail: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wind-Defying Course Technique<br>
        <br>
        Storms are great banes of ships, particularly the lightly
        built galleys that ferry cargo between the ports of the Inner
        Sea. Storms can snap masts and oars, capsize ships or simply
        smash them beneath vast swells. While under the protection
        of this Charm, a ship is safe from these and other weather-related
        disasters, so long as it has a competent helmsman —
        no Charm can protect a ship drifting without steerage in a
        gale. A character with this Charm can protect a ship of up to
        (20 x the character's Essence rating) feet in length.
        "

    hull_preserving_technique[Hull-Preserving<br>Technique]
    storm_weathering_essence_infusion --> hull_preserving_technique
    click hull_preserving_technique callback "
        Hull-Preserving Technique<br>
        <br>
        Cost: 8 motes, 1 Willpower, 1 health level<br>
        Duration: One turn<br>
        Type: Simple<br>
        Minimum Sail: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Storm-Weathering Essence Infusion<br>
        <br>
        Even more dangerous to a boat than a storm is a sharp
        impact — from the ram of a warship or from a rock or shoal.
        Even running aground on a sandbank can gut a ship or
        damage it so severely it founders. By bracing herself against
        the ship and channeling Essence through it at the moment
        of impact, the character can cause her magic to absorb the
        damage, leaving the ship unharmed. This effect can cause
        severe damage to a ramming vessel, as the preserved ship
        yields only as much as the impact of the ram pushes it
        sideways through the water. The character may have to use
        this Charm multiple turns in a row if the ship suffers
        multiple impacts. For example, if the ship fails to turn away
        and scrapes longways across a reef, the character may have
        to renew the Charm every turn the scraping continues. As
        with Storm-Weathering Essence Infusion, a character
        cannot use this Charm to protect a ship of more than (20
        x the character's Essence rating) feet in length.
        "
