---
config:
  theme: dark
---
flowchart TD

    salty_dog_method[Salty Dog Method]
    click salty_dog_method callback "
        Salty Dog Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: One day<br>
        Type: Reflexive<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        While this Charm remains in effect, it gives the
        character perfect sea legs. While the Charm lasts, the
        character will not lose his balance or footing, even on the
        most storm-tossed ship, though collisions and so forth may
        still require Dexterity + Athletics rolls. Characters using
        this Charm will not become seasick, even on rough seas.
        "

    shipwreck_surviving_stamina[Shipwreck-Surviving<br>Stamina]
    salty_dog_method --> shipwreck_surviving_stamina
    click shipwreck_surviving_stamina callback "
        Shipwreck-Surviving Stamina<br>
        <br>
        Cost: 5 motes<br>
        Duration: One day<br>
        Type: Reflexive<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        A character using this Charm can survive indefinitely
        in water. She will never tire from treading water and may
        drink seawater without ill effect. She is protected from
        sunburn and other exposure effects and can hold her
        breath for up to five minutes per point of Stamina. This
        Charm does nothing to ward off hostile sea life, nor does it
        protect a character from inclement weather.
        "

    perfect_reckoning_technique[Perfect Reckoning<br>Technique]
    salty_dog_method --> perfect_reckoning_technique
    click perfect_reckoning_technique callback "
        Perfect Reckoning Technique<br>
        <br>
        Cost: 4 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        Through the use of this Charm, the character may
        learn exactly where her ship lies in relation to landmarks
        and locations she already knows. This knowledge allows
        her to pinpoint her location, but only in regard to known
        landmarks. The Charm does not allow the character to
        indirectly divine the local geography by sensing her distance
        from previously uncharted reefs or lost islands.
        "

    weather_anticipating_intuition[Weather-Anticipating<br>Intuition]
    perfect_reckoning_technique --> weather_anticipating_intuition
    click weather_anticipating_intuition callback "
        Weather-Anticipating Intuition<br>
        <br>
        Cost: 6 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Perfect Reckoning Technique<br>
        <br>
        By placing her finger in the water, the character can
        instantly predict future weather for a number of days equal
        to the Chosen's permanent Essence. The only thing that
        will cause this forecast to err is the influence of powerful
        magic changing the weather - this Charm will foresee
        even freak squalls and unexpected fogs.
        "

    depth_plumbing_intuition[Depth-Plumbing<br>Intuition]
    perfect_reckoning_technique --> depth_plumbing_intuition
    click depth_plumbing_intuition callback "
        Depth-Plumbing Intuition<br>
        <br>
        Cost: 4 motes<br>
        Duration: One scene<br>
        Type: Reflexive<br>
        Minimum Sail: 4<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Perfect Reckoning Technique<br>
        <br>
        By feeling the Essence flows in the world around
        him, the character can sense the depth of the water for
        (100 x his Essence rating) yards. This knowledge allows
        him to discern harbor channels, sense reefs and so on.
        Note that awareness of a hazard doesn't necessarily mean
        that the character's ship is agile or well-handled enough
        to avoid the obstacle.
        "

    wind_defying_course_technique[Wind-Defying<br>Course Technique]
    salty_dog_method --> wind_defying_course_technique
    click wind_defying_course_technique callback "
        Wind-Defying Course Technique<br>
        <br>
        Cost: 6 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Salty Dog Method<br>
        <br>
        A character using this Charm while aboard a ship can
        tack much more closely to the wind than would be normal
        for his ship and rigging. Ships affected by this Charm
        cannot sail directly into the wind, but they can sail very
        near to it and, in general, handle more lightly and responsively
        than normal. Aside from additions to maneuverability
        and speed, which vary from ship to ship, the pilot may add
        the Essence rating of the character invoking the Charm to
        her Dexterity + Sail for ship handling. A ship that has had
        multiple Exalted use this Charm on it only benefits from
        the character with the highest Essence score.
        "

    storm_weathering_essence_infusion[Storm-Weathering<br>Essence Infusion]
    wind_defying_course_technique --> storm_weathering_essence_infusion
    click storm_weathering_essence_infusion callback "
        Storm-Weathering Essence Infusion<br>
        <br>
        Cost: 6 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Sail: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wind-Defying Course Technique<br>
        <br>
        Storms are great banes of ships, particularly the lightly
        built galleys that ferry cargo between the ports of the Inner
        Sea. Storms can snap masts and oars, capsize ships or simply
        smash them beneath vast swells. While under the protection
        of this Charm, a ship is safe from these and other weather-related
        disasters, so long as it has a competent helmsman —
        no Charm can protect a ship drifting without steerage in a
        gale. A character with this Charm can protect a ship of up to
        (20 x the character's Essence rating) feet in length.
        "

    hull_preserving_technique[Hull-Preserving<br>Technique]
    storm_weathering_essence_infusion --> hull_preserving_technique
    click hull_preserving_technique callback "
        Hull-Preserving Technique<br>
        <br>
        Cost: 8 motes, 1 Willpower, 1 health level<br>
        Duration: One turn<br>
        Type: Simple<br>
        Minimum Sail: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Storm-Weathering Essence Infusion<br>
        <br>
        Even more dangerous to a boat than a storm is a sharp
        impact — from the ram of a warship or from a rock or shoal.
        Even running aground on a sandbank can gut a ship or
        damage it so severely it founders. By bracing herself against
        the ship and channeling Essence through it at the moment
        of impact, the character can cause her magic to absorb the
        damage, leaving the ship unharmed. This effect can cause
        severe damage to a ramming vessel, as the preserved ship
        yields only as much as the impact of the ram pushes it
        sideways through the water. The character may have to use
        this Charm multiple turns in a row if the ship suffers
        multiple impacts. For example, if the ship fails to turn away
        and scrapes longways across a reef, the character may have
        to renew the Charm every turn the scraping continues. As
        with Storm-Weathering Essence Infusion, a character
        cannot use this Charm to protect a ship of more than (20
        x the character's Essence rating) feet in length.
        "

    subgraph savage_seas[Savage Seas]
        direction TB
        seeking_the_earths_bounty_method[Seeking the Earth's<br>Bounty Method]
        click seeking_the_earths_bounty_method callback "
            Seeking the Earth's Bounty Method<br>
            <br>
            Cost: 6 motes<br>
            Duration: One turn<br>
            Type: Simple<br>
            Minimum Sail: 4<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Perfect Reckoning Technique<br>
            <br>
            By casting his will forth upon the waters, the Chosen
            can uncover where the nearest safe harbor or beaching site
            is located and how to get there. Although the approach to
            the harbor will be clear of hazards and the beach there
            usable for small craft (even if the vessel itself cannot
            beach), the harbor will not necessarily be safe for the crew.
            There might well be monsters in the bay or surroundings,
            the nearby natives (if any) may be unfriendly, or other
            hidden dangers may exist.
            "

        fires_kiss_resistance_prana[Fire's Kiss<br>Resistance Prana]
        click fires_kiss_resistance_prana callback "
            Fire's Kiss Resistance Prana<br>
            <br>
            Cost: 6 motes, 1 Willpower<br>
            Duration: One day<br>
            Type: Simple<br>
            Minimum Sail: 4<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Wind-Defying Course Technique<br>
            <br>
            Fire is rightly feared on all sea-going vessels. Even a ship
            with a First Age hull is filled with furnishings and supplies
            that will burn — and the crew has nowhere to go. Even small
            fires are tolerated only because of necessity, and the galley
            on a ship is the most carefully designed part of most vessels.
            This Charm renders a vessel completely immune to the
            ravages of fire altogether; while it is in effect, no natural fire
            can start aboard the ship. Although existing fires will not be
            affected, neither will they spread further, confining themselves
            to destroying what they are actually burning at that
            moment; any fuel added to the fire will simply refuse to burn.
            Magical or elemental fires can be set normally, but they will
            burn for half as long and take half the effort to douse than
            usual. While burning, they will inflict whatever damage
            they normally would, however.
            "

        ignore_the_winds_course_technique[Ignore the Wind's<br>Course Technique]
        click ignore_the_winds_course_technique callback "
            Ignore the Wind's Course Technique<br>
            <br>
            Cost: 10 motes<br>
            Duration: One scene<br>
            Type: Simple<br>
            Minimum Sail: 5<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Wind-Defying Course Technique<br>
            <br>
            By dint of this Charm, an Exalted helmsman can not
            only tack deeper into the wind than any mortal helmsman,
            she may ignore its direction completely. So long as the
            Charm is in effect, her vessel moves as if the wind were full
            in its sails, no matter what direction the winds actually blow
            or what course the helmsman sets. Anyone watching the
            Exalted's vessel while it sails in defiance of the winds will
            obviously know that some sort of powerful magic is in use.
            "

        masts_unbreakable_will_prana[Mast's Unbreakable<br>Will Prana]
        click masts_unbreakable_will_prana callback "
            Mast's Unbreakable Will Prana<br>
            <br>
            Cost: 4 motes<br>
            Duration: One scene<br>
            Type: Simple<br>
            Minimum Sail: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Wind-Defying Course Method<br>
            <br>
            A ship's mast is its life; without the mast, a sailing vessel
            is utterly subject to tide and current, and few vessels survive
            an attack or sudden squall that wrecks the mast. By way of
            this Charm, the Exalt can render the mast of a ship he is on
            immune to even the greatest winds or the strongest attacks.
            Only actions taken by Deathlords, extremely powerful
            elementals or spirits and the most powerful Exalted (those
            with a permanent Essence of 6 or greater) can hope to
            destroy a ship's mast while this Charm is in effect.
            "

        harden_the_hull_practice[Harden the Hull<br>Practice]
        click harden_the_hull_practice callback "
            Harden the Hull Practice<br>
            <br>
            Cost: 3 motes + 2 per (Essence)L of soak<br>
            Duration: One scene<br>
            Type: Reflexive<br>
            Minimum Sail: 4<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Storm-Weathering Essence Infusion<br>
            <br>
            Unseen hazards and dangers are a threat to every sailing
            vessel. Using this Charm, an Exalt can reinforce the hull of
            her vessel to resist these unforeseen problems. For every 2
            motes of Essence she spends, the hull gains lethal soak equal
            to the Exalted's permanent Essence. This Charm can be
            applied multiple times to the same vessel in a scene, but
            under no circumstances can the soak gained through the use
            of this Charm exceed the highest Stamina + Sail total of any
            Exalt who used this Charm on the ship during the scene.
            "
    end

    perfect_reckoning_technique --> seeking_the_earths_bounty_method
    wind_defying_course_technique --> fires_kiss_resistance_prana
    wind_defying_course_technique --> ignore_the_winds_course_technique
    wind_defying_course_technique --> masts_unbreakable_will_prana
    storm_weathering_essence_infusion --> harden_the_hull_practice

    subgraph Castebook Eclipse
        golden_essence_sails[Golden Essence Sail]
        click golden_essence_sails callback "
            Golden Essence Sail<br>
            <br>
            Cost: 6 motes, 1 Willpower<br>
            Duration: One day<br>
            Type: Simple<br>
            Minimum Sail: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Salty Dog Method<br>
            <br>
            The character using this Charm weaves sails out
            of pure Essence for a ship that has no sails (or badly
            damaged ones). The new sails are of a shimmering
            golden cloth, as light as silk but stronger than canvas.
            They appear on the ship's masts and furl or unfurl at
            their creator's command. They may bear an emblem of
            the Chosen's anima, if she wishes it. Golden Essence
            Sails have a soak value of (the Exalt's permanent
            Essence score + 2) for resisting attacks against the
            ship's rigging or sails, and they do not accumulate
            damage (they ignore any attack insufficient to damage
            them, just like the ship itself does). See Savage Seas,
            pages 92-93, for more information.
            "

        phantom_crew_charm[Phantom Crew Charm]
        click phantom_crew_charm callback "
            Phantom Crew Charm<br>
            <br>
            Cost: 8 motes, 1 Willpower<br>
            Duration: One day<br>
            Type: Simple<br>
            Minimum Sail: 5<br>
            Minimum Essence: 3<br>
            Prerequisite Charms: Golden Essence Sails<br>
            <br>
            With this Charm, the Chosen calls into being
            phantom sailors able to crew any ship the character is
            aboard. The phantom crew speaks only when necessary
            and obeys all of its summoner's orders. The
            phantom sailors will sail the ship anywhere and perform
            any shipboard duties, although they will not
            fight and should be treated as extras with relevant
            Abilities equal to the Exalted's Essence. The character
            can summon a crew sufficient for a ship of up to
            (Essence x 40) feet in length.
            "

        glorious_solar_ship[Glorious Solar Ship]
        click glorious_solar_ship callback "
            Glorious Solar Ship<br>
            <br>
            Cost: 15 motes, 1 Willpower<br>
            Duration: One day<br>
            Type: Simple<br>
            Minimum Sail: 5<br>
            Minimum Essence: 4<br>
            Prerequisite Charms: Phantom Crew Charm<br>
            <br>
            The Exalted conjures an entire vessel from pure
            Essence, capable of bearing him and a number of
            passengers and crew. The ship has a maximum length
            of (the character's Essence rating x 20) feet and
            appears ready to sail, with all of the necessary equipment
            on board. The Glorious Solar Ship has no crew;
            it is up to the Chosen to provide one, either mortal or
            otherwise. Other Sail Charms can be applied normally
            to the Glorious Solar Ship.
            "
    end

    salty_dog_method --> golden_essence_sails
    golden_essence_sails --> phantom_crew_charm
    phantom_crew_charm --> glorious_solar_ship
