---
config:
  theme: dark
---
flowchart TD

    easily_overlooked_presence_method[Easily Overlooked<br>Presence Method]
    click easily_overlooked_presence_method callback "
        Seasoned Criminal Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Stealth: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm does not involve hiding so much as
        becoming difficult to notice. So long as the character does
        nothing to stand out, make herself obvious or become the
        center of attention, those who are not actively looking for
        someone will simply discount her as part of the scenery. For
        example, this Charm does not work on alerted guards or
        those watching over restricted areas or on those who
        intend to stop everyone who passes. Likewise, it cannot
        conceal a character who is very different from her sur-
        roundings; a tall, short-haired, light-skinned woman in a
        crowd of short, long-haired, dark-skinned men is going to
        stand out too much to benefit from this Charm.
        "

    mental_invisibility_technique[Mental Invisibility<br>Technique]
    easily_overlooked_presence_method --> mental_invisibility_technique
    click mental_invisibility_technique callback "
        Mental Invisibility Technique<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Stealth: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Easily Overlooked Presence Method<br>
        <br>
        An extension of Easily Overlooked Presence Method, this
        Charm bends the minds of those seeing the character. Players
        whose characters see the Exalted must make a Willpower roll and
        gain a number of successes equal to the Essence of the Chosen
        using the Charm to actually perceive her and not just ignore her.
        This effect ends if the character takes violent action or if she is
        pointed out by someone who notices her, either directly (&quot;Look!
        Over there!&quot;) or indirectly (Onlookers asking themselves the
        question, &quot;Who is the guard swinging an axe at?&quot;).
        "

    vanishing_from_minds_eye_method[Vanishing from Mind's Eye<br>Method]
    mental_invisibility_technique --> vanishing_from_minds_eye_method
    click vanishing_from_minds_eye_method callback "
        Vanishing from Mind's Eye Method<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Stealth: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Mental Invisibility Technique<br>
        <br>
        The ultimate mental misdirection - the character can
        vanish from all memory. She is no more or less easy to detect
        than before, but those who see her will not recognize her
        because they have no idea who she is. Essentially, the character
        sets up a separate history for herself, starting when the Charm
        is first invoked and ending when she allows it to expire. Beings
        with Essence ratings higher than the character's are immune to
        this effect. Obviously, a character trying to get somewhere she
        shouldn't should have some other Stealth abilities at work
        since, while she will not be recognized, guards are still going to
        stop someone they don't know. Extended use of this Charm can
        cause serious problems for an Exalted who is a ruler, merchant
        or other important person, as others will quickly start dividing
        up the character's now-ownerless property.
        "

    invisible_statue_spirit[Invisible Statue Spirit]
    easily_overlooked_presence_method --> invisible_statue_spirit
    click invisible_statue_spirit callback "
        Invisible Statue Spirit<br>
        <br>
        Cost: 5 motes<br>
        Duration: Until disturbed<br>
        Type: Simple<br>
        Minimum Stealth: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Easily Overlooked Presence Method<br>
        <br>
        This Charm allows the Exalted to truly disappear — no
        amount of visual searching, however thorough, will detect him,
        so long as he remains still. Moving, even in a slow, shuffling walk,
        is enough to disturb the effect of this Charm, as is any sort of
        offensive action. Characters using Invisible Statue Spirit are not
        immaterial, they can be detected by touch or by scent or hearing.
        "

    blurred_form_style[Blurred Form Style]
    invisible_statue_spirit --> blurred_form_style
    click blurred_form_style callback "
        Blurred Form Style<br>
        <br>
        Cost: 8 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Stealth: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Invisible Statue Spirit<br>
        <br>
        This Charm conceals the Exalted, blurring her form
        and allowing her to blend into whatever background she
        stands against, vastly improving her Stealth. Players whose
        characters attempt to spot her when she is hiding or
        moving slowly must gain a number of additional successes
        on their Perception + Alertness rolls equal to the character's
        Essence. If she attacks from a distance, players of those who
        see the attack get one free Perception + Alertness roll at
        difficulty 1 to spot her for each attack she makes. If she
        attacks in hand-to-hand combat, all watching are assumed
        to immediately spot her.<br>
        Once spotted, her enemies can pick her out again at will
        until she escapes from their line of sight for at least several
        seconds. While the Exalted has Blurred Form Style active,
        enemies attacking her at range do so at a difficulty penalty equal
        to her Essence score, and those attacking her in hand-to-hand
        combat suffer a flat + 1 penalty to the difficulty of their attacks.
        "

    sound_and_scent_banishing_attitude[Sound and Scent Banishing<br>Attitude]
    blurred_form_style --> sound_and_scent_banishing_attitude
    click sound_and_scent_banishing_attitude callback "
        Sound and Scent-Banishing Attitude<br>
        <br>
        Cost: 6 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Stealth: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Blurred Form Style<br>
        <br>
        Visual detection is not the only thing an Exalted must
        fear. Through the use of this Charm, an Exalted can
        protect himself from other forms of detection, as well.
        While this Charm is active, the character makes no noise
        of any sort, nor does anything carried on his person or in
        his hands. This effect does not extend beyond his touch —
        a dropped knife will still clatter, a knocked-over pot will
        still shatter. Also, while this Charm is in effect, the
        character has (and leaves) no scent of any sort. Tracking
        beasts will not detect him or be able to follow him.
        "
