---
config:
  theme: dark
---
flowchart TD

    seasoned_criminal_method[Seasoned Criminal Method]
    click seasoned_criminal_method callback "
        Seasoned Criminal Method<br>
        <br>
        Cost: 10 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Larceny: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm grants a character preternatural intuition
        with regard to criminal subcultures. While under the influence
        of this Charm, he can easily pick out criminal establishments
        - pawnshops willing to operate as fences, taverns that are
        thieves' havens and so on. Likewise, the character can easily
        pick out those who are actively interested in buying or selling
        illegal goods and services — he canspot police and officials who
        will accept bribes and individuals interested in selling or buying
        drugs, sex or information. Finally, the character using this
        Charm can easily read lines of power, differentiating important
        organized crime figures from small-time operators and quickly
        tracking down the true thrones and powers of the local underworld.
        In short, characters with this Charm are at home in any
        criminal subculture. This Charm doesn't grant the ability to
        spot agents provocateurs and informers.
        "

    flawlessly_impenetrable_disguise[Flawlessly Impenetrable<br>Disguise]
    seasoned_criminal_method --> flawlessly_impenetrable_disguise
    click flawlessly_impenetrable_disguise callback "
        Flawlessly Impenetrable Disguise<br>
        <br>
        Cost: 7 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Larceny: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Seasoned Criminal Method<br>
        <br>
        By means of this Charm, the character can disguise her
        appearance, her voice and even her scent. The player may not
        imitate a specific individual, but may alter her apparent age by
        as much as 20 years (minimum 16), her ethnicity, her height
        by as much as six inches and her gender. It is impossible to see
        through the character's disguise via mundane means. Characters
        using this Charm can sometimes be detected via the
        Unsurpassed (Sense) Discipline Charm or by the All-Encompassing
        Sorcerer's Sight Charm - in these cases, the matter
        is resolved as normal for disguise attempts — an opposed roll
        of the disguised character's Wits + Larceny versus the
        Perception + Awareness of the character attempting to detect him.
        "

    perfect_mirror[Perfect Mirror]
    flawlessly_impenetrable_disguise --> perfect_mirror
    click perfect_mirror callback "
        Perfect Mirror<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Larceny: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Flawlessly Impenetrable Disguise<br>
        <br>
        This Charm allows a character to perfectly imitate someone
        she is very familiar with. While this Charm is active, not even the
        target's pets, intimates and close friends will be able to tell her
        from the real individual. The character must know the target well
        to perfectly mirror him - at least well enough to imitate him
        through mundane disguise (see the Drama chapter, page 255, for
        rules on disguise). Also, while this Charm covers small mannerisms,
        responses to in-jokes and so forth, it does not grant the
        character access to the mirrored character's memories, so she will
        not be able to use passwords she does not know, recall facts the
        Exalted herself is not familiar with and so forth.
        "

    flawless_pickpocketing_technique[Flawless Pickpocketing<br>Technique]
    click flawless_pickpocketing_technique callback "
        Flawless Pickpocketing Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        With this Charm, one of the Chosen can pick someone's
        pocket flawlessly, with no chance of detection. He must be
        able to touch the target (though no one will notice him do so),
        and the Exalted must have a pouch, pocket or other hiding
        place large enough to put the stolen items into if he does not
        wish to end the theft with the filched item simply palmed.
        "

    stealing_from_plain_sight_spirit[Stealing from Plain Sight<br>Spirit]
    flawless_pickpocketing_technique --> stealing_from_plain_sight_spirit
    click stealing_from_plain_sight_spirit callback "
        Stealing from Plain Sight Spirit<br>
        <br>
        Cost: 6 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Flawless Pickpocketing Technique<br>
        <br>
        This Charm is much like Flawless Pickpocketing Technique,
        allowing a character to steal an item without any
        chance of being caught in the act. However, an Exalted
        utilizing Stealing From Plain Sight Spirit can steal an item
        from plain view, for example stealing a brooch from a table,
        a key from a jailer's keyring or a sword from its scabbard.
        Unless attention is somehow drawn to the act (for example,
        a guard will notice his sword was stolen if he attempts to
        draw it, and a jailer will notice a key is missing if he attempts
        to unlock a door with it), the theft will go unnoticed for at
        least number of turns equal to the character's Essence rating.<br>
        As with Flawless Pickpocketing Technique, the character
        must be close enough to touch the object she wishes to
        steal. Note that the item cannot be actively in use when it is
        stolen - for instance, you cannot use Stealing From Plain
        Sight Spirit to steal the pen or sword out of someone's hand.
        "

    magpies_invisible_talons[Magpie's Invisible Talons]
    stealing_from_plain_sight_spirit --> magpies_invisible_talons
    click magpies_invisible_talons callback "
        Magpie's Invisible Talons<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Stealing From Plain Sight Spirit<br>
        <br>
        This Charm is similar to Stealing From Plain Sight
        Spirit, in that it allows objects to be stolen from plain view
        without their loss being noticed for a number of turns equal
        to the Essence score of the character using the Charm
        (unless some special notice is drawn to the fact that the
        object is no longer present). However, Magpie's Invisible
        Talon allows the character to steal an object from up to one
        yard away per point of her Essence score. As with Stealing
        From Plain Sight Spirit, the character cannot steal an
        object that is actively in use.
        "

    lock_opening_touch[Lock-Opening Touch]
    flawless_pickpocketing_technique --> lock_opening_touch
    click lock_opening_touch callback "
        Lock-Opening Touch<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Flawless Pickpocketing Technique<br>
        <br>
        Through the use of this Charm, the character can
        instantly pick any lock. He needs no tools — all he need
        do is strike or rap it sharply, and it pops open. The
        character must use this Charm once per lock, and so, doors
        with many locks can exhaust an Exalted thief who relies
        only on this Charm. Lock-Opening Touch works on all
        locks, not just those built into doors, and can be used to
        open locked shackles or chests as well.
        "

    door_evading_technique[Door-Evading Technique]
    lock_opening_touch --> door_evading_technique
    click door_evading_technique callback "
        Door-Evading Technique<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Lock-Opening Touch<br>
        <br>
        Some doors do not have locks to pick, being bound
        closed with bars or sorcery. Other doors are equipped
        with too many locks to easily pick, even with the assistance
        of Charms. With this Charm, an Exalted can
        simply step through a locked portal, closed gate, dropped
        portcullis or other closed portal. The character places her
        hand against the portal, steps forward and appears on the
        other side. This Charm also works on windows, sewer
        grates and other aperture closures, but it does not allow
        the character to pass through walls or stick his hand into
        a locked chest and fish around.
        "
