---
config:
  theme: dark
---

flowchart TD

    integrity_protecting_prana[Integrity-Protecting Prana]
    click integrity_protecting_prana callback "
        Integrity-Protecting Prana<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Lore: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Exposure to Wyld energies can cause hallucinations,
        psychological dependency, insanity and even terrible mutations.
        Through the use of this Charm, the character makes her
        person proof against the influence of Wyld energies. While
        the Charm is in effect, her mind and body cannot be warped
        or twisted by the power of the Wyld. Note that, while the
        character's shape and sanity are protected, her body can still
        be torn asunder by Wyld-spawned phenomenon; the whirling
        walls of fire and thunder and the 100-headed snake
        monsters with burning chalcedony eyes are quite real.<br>
        Similarly, her possessions are vulnerable, though the
        protective effect of the Charm does seem to spill over to them
        slightly. A character's sword will turn into a snake that hisses
        and slithers off rather than an asp that bites her hand, and her
        armor will suddenly become gossamer spiderwebs rather than
        sheets of rotting gristle full of carnivorous maggots.
        "

    chaos_repelling_pattern[Chaos-Repelling Pattern]
    integrity_protecting_prana --> chaos_repelling_pattern
    click chaos_repelling_pattern callback "
        Chaos-Repelling Pattern<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Lore: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Integrity-Protecting Prana<br>
        <br>
        Through the use of this Charm, the character protects
        his possessions from the warping influence of the Wyld.
        While the Charm lasts, the character and his goods (an
        amount which can equal a fully laden horse if the character
        is mounted) can sojourn in even the most fluid areas of the
        Wyld without worry that they will suddenly become something
        other than what they currently are.<br>
        Note again that Wyld-spawned phenomenon are not
        warded against, though the Charm makes certain sorts of
        mishaps (falling into the sky, having the ground suddenly
        open up to become a pit of mechanical alligators) quite
        unlikely. The character may be blasted asunder or eaten
        and digested, but up and down will continue to mean the
        same thing, and his feet will tend to always land on a stable,
        solid object of some sort. Any character trying to lead a
        horse into a deep Wyld area had better have the Spirit-Steadying
        Assurances Charm or something similar.
        "

    wyld_shaping_technique[Wyld-Shaping Technique]
    chaos_repelling_pattern --> wyld_shaping_technique
    click wyld_shaping_technique callback "
        Wyld-Shaping Technique<br>
        <br>
        Cost: 20 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Chaos-Repelling Pattern<br>
        <br>
        There are few of their abilities that the Exalted fear
        using. They are, after all, the anointed of the gods. They do
        not command Essence, it flows to match their desire. Even
        the most serious sorts of negligence or mistakes are only
        likely to lead to wild mood swings and misbehavior, not a
        grisly death. But even in the days of the Old Realm, the
        most powerful Solar Exalted used this Charm sparingly.<br>
        A character using this Charm can shape the primordial
        chaos, the inchoate precursor of reality, to his whim.
        Obviously, this Charm does not work in areas where the
        fabric of reality is already set — it must be used in the
        deepest, most fluid Wyld zones or else at the edge of the
        world, forcing shape into the teeth of the howling storm.<br>
        To activate this Charm, the character sets foot in the
        unformed substance of reality and wills it to take shape as he
        commands. The player rolls his character's Essence. Wyld-
        Shaping Technique is an extended action, with the cost of the
        Charm paid for each roll. The number of successes required is
        up to the Storyteller. The character can create nearly any-
        thing — a Demesne, a giant factory that produces golem
        warriors, a bag of diamonds as big as potatoes — but the larger
        and more powerful the thing he wishes to create, the more
        successes the player must roll. A single success would create
        a bag of diamonds or a talent of gold, while three successes
        would create a Demesne, a keep or a talent of one of the Five
        Magical Materials. Five successes would create a fortress, an
        enchanted forest complete with magical inhabitants or the
        aforementioned manufactory for golem warriors.<br>
        If the player botches at any time, horrible side effects result
        as reality shapes to the character's subconscious whims. It may
        take the shape of his fears or simply coalesce in some horrifically
        wrong fashion - the specifics are up to the Storyteller. They
        are rarely pleasant and often worse than fatal.<br>
        Objects created in this fashion are freshly minted. Lacking
        roots in reality, they are more subject to the gnawing of chaos
        than other items. This instability is really only a problem for
        large structures such as fortresses and cities - if such places are
        left unpeopled and not made part of the complex interplay of
        contact that makes up existence, they will slowly dissolve back
        into the chaos from which they sprang.
        "

    essence_lending_method[Essence-Lending Method]
    click essence_lending_method callback "
        Essence-Lending Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        No Exalted is an island. Through the use of this Charm, a
        character can transfer Essence motes to another character. Touse
        this Charm, the character must spend a turn in skin-to-skin
        contact with the target and burn 3 motes of Essence to power the
        Charm. She may then transfer to the target motes of Essence
        equal to 3 x her permanent Essence score. This Essence may not
        cause the target's Essence pool to rise above its normal maximum.
        If the target cannot accept all the transferred Essence, then the
        excess dissipates harmlessly. Characters may activate this Charm
        over successive turns to transfer large quantities of Essence but
        must pay the 3 motes for each turn the Charm is in use.
        "

    will_bolstering_method[Will-Bolstering Method]
    essence_lending_method --> will_bolstering_method
    click will_bolstering_method callback "
        Will-Bolstering Method<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Essence-Lending Method<br>
        <br>
        Exalted can share more than simple power. The touch
        of a Solar can bring new strength to the downcast heart and
        new courage to the terrified. To use this Charm, the
        character must be in skin-to-skin contact with the target
        for a turn and must spend the Essence and Willpower to
        power the Charm. The character may then transfer a
        number of points of temporary Willpower to the target
        equal to the highest Virtue that the two of them share.<br>
        For Example: Dace is transferring Willpower to Swan.
        Dace has Valor 4, Conviction 2, Compassion 3, Temperance
        2. Swan has Valor 3, Conviction 2, Compassion 2, Temper-
        ance 3. Dace can transfer up to three points of Temporary
        Willpower to Swan, one for each dot they share in Valor.<br>
        As with Essence-Lending Method, above, the Will-Bolstering
        Method cannot cause a character's temporary Willpower
        to rise above its normal maximum. Excess points are wasted.
        "

    wound_accepting_technique[Wound-Accepting<br>Technique]
    will_bolstering_method --> wound_accepting_technique
    click wound_accepting_technique callback "
        Wound-Accepting Technique<br>
        <br>
        Cost: 3 motes per health level, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Will-Bolstering Method<br>
        <br>
        Through the use of this Charm, the Exalted can give the
        gift of his very life energy. The character must be in skin-to-skin
        contact with the target for a turn and must spend a point of
        temporary Willpower and the appropriate amount of Essence.
        The Exalted using the Charm immediately takes a number of
        health levels of bashing damage, and the target of the Charm
        immediately heals a like number of levels of bashing or lethal
        damage. Exalted cannot share more health levels than the
        lower of the two character's Staminas. This Charm cannot heal
        aggravated damage, nor can it cause a character to gain more
        health levels than she would normally have. Exalted can, in
        fact, kill themselves through the use of this Charm.
        "

    power_awarding_prana[Power-Awarding Prana]
    wound_accepting_technique --> power_awarding_prana
    click power_awarding_prana callback "
        Power-Awarding Prana<br>
        <br>
        Cost: 5 mote, 1 Willpower, 1 experience point<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Lore: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Wound-Accepting Technique<br>
        <br>
        Through the use of this Charm, the Exalted can lend some
        of her power to a normal mortal recipient. For each point of the
        loaning character's Essence, he can loan one Charm to the
        target. The target must have the appropriate minimum Ability
        to use the Charm, and if the Charms lent have prerequisite
        Charms, then the target must be lent those as well. The Charms
        draw directly on the Essence of the Exalted who lent them, but
        the recipient must pay any non-Essence costs. While the
        Charms are lent, the Exalted cannot use them. The Exalted can
        end the effect of this Charm and recall her power at any time.
        During the First Age, Exalted often used this ability to bolster
        their lictors and pages for important tasks.
        "
