---
config:
  theme: dark
---

flowchart TD

    flawless_handiwork_method[Flawless Handiwork Method]
    click flawless_handiwork_method callback "
        Flawless Handiwork Method<br>
        <br>
        Cost: 3 motes per success<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Craft: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The character channels Essence through his hands and
        tools, enhancing his efforts and making the final produce of his
        work far more impressive than the fruits of any mortal craftsman's
        labor. To use this Charm, the player first makes a regular
        Intelligence or Stamina + Craft roll for the character. Then, the
        player may &quot;buy&quot; additional successes, up to the character's
        Essence rating + the number of successes rolled on the Craft roll.
        Each success bought in this fashion costs 3 motes of Essence.<br>
        Storytellers should consider strongly granting special bonuses
        to objects that are made from good or exceptional
        materials to start and that have astonishing numbers of successes.
        For more details on this, see the &quot;Craft&quot; section of the
        Drama chapter, page 245. Note that Flawless Handiwork
        Method's effects do not occur instantly — the character must
        still take the regular amount of time necessary to construct an
        object of that type, though he need take no longer. An Exalted
        craftsman can knock together in a morning items that would
        take a mortal craftsman months or years to produce.
        "

    flawless_handiwork_method --> object_strengthening_touch[Object-Strengthening<br>Touch]
    click object_strengthening_touch callback "
        Object-Strengthening Touch<br>
        <br>
        Cost: 6 motes<br>
        Duration: One Scene<br>
        Type: Simple<br>
        Minimum Craft: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Flawless Handiwork Method<br>
        <br>
        This Charm strengthens objects, allowing them to
        endure far more damage than normal. Very fragile objects
        such as those made of paper or glass cannot be damaged
        without the full exertion of a Strength at least equal to the
        Essence rating of the character who used the Object-
        Strengthening Touch Charm on them. Objects that are
        not so fragile take roughly twice as much force as normal
        to harm. For rules on breaking and lifting objects, see the
        &quot;Athletics&quot; section of the Drama chapter, page 251.<br>
        Object-Strengthening Touch does not just protect
        against breakage — strengthened objects are also resistant
        to fire, acid, freezing and other forms of damage. The
        character using Object-Strengthening Touch must touch
        the object in order to cause this Charm to take effect.
        Characters can strengthen any object, not just objects that
        are at the focus of the character's Craft Ability. This
        Charm does not work on animals or sentient beings.
        "

    object_strengthening_touch --> durability_enhancing_technique[Durability-Enhancing<br>Technique]
    click durability_enhancing_technique callback "
        Durability-Enhancing Technique<br>
        <br>
        Cost: 10 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Object-Strengthening Touch<br>
        <br>
        Objects subjected to this Charm do not have the immense
        durability of objects subjected to Object-Strengthening
        Touch, but the enhancement is permanent. While objects
        treated with Durability-Enhancing Technique are not completely
        immune to the ravages of time and nature, they are
        very resistant, enduring at least 10 times as long as untreated
        objects. Objects treated with Durability-Enhancing Technique
        add twice the Exalted's score in the Crafts Ability to the
        Strength + Athletics dice pool required to break them. Items
        such as swords and axes that have been treated with
        Durability-Enhancing Technique hold their edges longer, even if
        used to hack through doors or otherwise mistreated
        "

    object_strengthening_touch --> shattering_grasp[Shattering Grasp]
    click shattering_grasp callback "
        Shattering Grasp<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Object-Strengthening Touch<br>
        <br>
        Someone who works with a material for a long time
        learns its strengths and weaknesses. A character who knows
        this Charm can channel Essence to intensify this knowledge
        and can rend stone and metal with his bare hands and tear
        apart wooden doors with his fingers. A character using the
        Shattering Grasp Charm multiplies his Strength + Athletics
        by 2 for the purposes of breaking or damaging the basic
        material he works with for the focus of his Craft skill -
        typically metal, stone or wood. If the character is making an
        attack against such an object, double his damage successes.
        Tanners and leathercrafters do not gain the ability to do extra
        damage in hand-to-hand combat with this Charm.
        "

    shattering_grasp --> craftsman_needs_no_tools[Craftsman Needs No Tools]
    click craftsman_needs_no_tools callback "
        Craftsman Needs No Tools<br>
        <br>
        Cost: 7 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Craft: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Shattering Grasp<br>
        <br>
        The greatest burden of a craftsman is the pressing need for
        tools and a workshop. For an Exalted who has mastered this
        Charm, that is no problem at all. A character who knows this
        Charm can work directly with her chosen material, shaping it
        with hands and voice, laboring without any need for tools.
        Characters using this Charm slowly croon and purr to their
        work as they shape and form the material with their fingertips
        "

    object_strengthening_touch --> chaos_resistance_preparation[Chaos-Resistance<br>Preparation]
    click chaos_resistance_preparation callback "
        Chaos-Resistance Preparation<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Object-Strengthening Touch<br>
        The ravages of the Wyld can twist objects, as well as men. For
        every object that is made better suited to its task, 100 are ruined by
        the energies of unbounded change. This Charm makes an object
        far more resistant to the twisting effects of Wyld energy. Chaos
        Resistance Preparation is not as complete as the Lore Charms that:
        stabilize persons, causing an object protected by this Charm to take
        only take 10 times as long to change as it would normally. However,
        the effects of Chaos-Resistance Preparation are permanent. Objects
        treated with this Charm lend no protective qualities to their
        bearers — a suit of Chaos-Resistant armor will not protect the
        character wearing it from Wyld-induced mutation.
        "

    crack_mending_technique[Crack-Mending Technique]
    durability_enhancing_technique --> crack_mending_technique
    craftsman_needs_no_tools --> crack_mending_technique
    click crack_mending_technique callback "
        Crack-Mending Technique<br>
        <br>
        Cost: 10 motes, 1 Willpower, 1 health level<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Craftsman Needs No Tools, Durability-Enhancing Technique<br>
        <br>
        A character using the Crack-Mending Technique can fix
        any broken object, no matter how severely damaged, so long as
        it was not totally unmade (for example, by powerful sorcery,
        digestion in a Behemoth's gullet or immersion in molten rock).
        The character must spend a number of hours working on the
        object equal to 10 - her Essence, slowly piecing it back together
        and coaxing the fragments to bind to one another.<br>
        This Charm can even remake extremely damaged things
        such as shattered crystal and burnt paper, but it cannot
        remake metaphorical or conceptual things —it cannot mend
        broken hearts, oaths or promises, for example, nor can it
        remake shattered dreams or smashed hopes. Also, it cannot
        remake an object more yards in radius than the character's
        Essence rating. Crack-Mending Technique can restore damaged
        items of First Age manufacture but can do nothing to
        repair those whose magic has fled or been exhausted.
        "
