---
config:
  theme: dark
---

flowchart TD

    friendship_with_animals_approach[Friendship with<br>Animals Approach]
    click friendship_with_animals_approach callback "
        Friendship with Animals Approach<br>
        <br>
        Cost: 3 motes<br>
        Duration: One Scene<br>
        Type: Simple<br>
        Minimum Survival: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Through the use of this Charm, the character can deal
        well with nearly any wild animal. The character must be
        within one yard of the target per point of her Essence.
        Herbivores and smaller omnivores will become somewhat
        docile, even letting the character pet or handle them.
        Predators are less susceptible to this power, and most will
        simply let the character pass unmolested through their
        territory. This power does not work on sentient animals,
        animals that are trained to attack or animals that are
        insane from pain, hunger or disease.
        "

    spirit_tied_pet[Spirit-Tied Pet]
    friendship_with_animals_approach --> spirit_tied_pet
    click spirit_tied_pet callback "
        Spirit-Tied Pet<br>
        <br>
        Cost: 10 motes, 1 Willpower, 1 experience point<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Survival: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Friendship With Animals Approach<br>
        <br>
        By handling an animal, feeding it, petting and scratching
        it and otherwise interacting with it, a character who
        knows this Charm can forge a permanent magical bond
        with the beast. Each time the character uses this Charm
        on the target, it is as if he gained a point of the Familiar
        Background with the target animal as the Familiar. So a
        character who wished to tame a tiger would have to use
        it at least three times to cause the beast to become well-disposed
        to him and an additional two times to gain the
        ability to see through the beast's eyes and communicate
        with it. Obviously, using this Charm on animals such as
        bears, tigers and tyrant lizards can be problematic, as they
        will not allow themselves to be handled, even under the
        effects of Friendship with Animals Approach. A strong
        wrestling ability or a willingness to raise the animal from
        a cub is useful in such instances. Characters cannot have
        more than one Spirit-Tied Pet at a time.
        "

    bestial_traits_technique[Bestial Traits Technique]
    spirit_tied_pet --> bestial_traits_technique
    click bestial_traits_technique callback "
        Bestial Traits Technique<br>
        <br>
        Cost: 8 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Survival: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Spirit-Tied Pet<br>
        <br>
        Through the use of this Charm, a character can gain
        the traits of her Spirit-Tied Pet. Each use of this Charm
        allows the character to gain a single characteristic. Obviously,
        animals have too many characteristics to easily
        model them all. Typically, the character will gain the
        ability to climb rough surfaces, fall great distances without
        "

    hardship_surviving_mendicant_spirit[Hardship-Surviving<br>Mendicant Spirit]
    click hardship_surviving_mendicant_spirit callback "
        Hardship-Surviving Mendicant Spirit<br>
        <br>
        Cost: 5 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Through the use of this Charm, the character becomes
        able to survive in even the most hostile conditions without
        special preparations. Blazing heat or terrible cold are no danger
        to the character, nor are hypothermia from rain or water
        exposure, trench foot, snow and sand blindness, leeches, mosquitoes
        and other potentially deadly biting insects — the
        character is perfectly at home in a harsh wilderness environment.
        This magic protects the character even if he personally
        is not prepared for the environment. A character using Hardship-Surviving
        Mendicant Spirit is at home on a glacier if he is
        bundled in the warmest clothing available or if he is clad in
        nothing but silk slippers and a pair of pantaloons (though he
        may have difficulty walking over ice in silk slippers).<br>
        Note that this Charm does not protect against the most
        hostile of environments - ocean survival, underwater
        survival or the extreme elemental effects near the elemental
        poles. To exist in those environments, characters must use
        the Element-Resisting Prana Charm (p. 182).
        "

    trackless_region_navigation_charm[Trackless Region<br>Navigation Charm]
    hardship_surviving_mendicant_spirit --> trackless_region_navigation_charm
    click trackless_region_navigation_charm callback "
        Trackless Region Navigation Charm<br>
        <br>
        Cost: 7 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Hardship-Surviving Mendicant Spirit<br>
        <br>
        With this Charm, the character can find his way safely and
        surely through even the worst terrain. The character (and a
        number of persons following him equal to twice his Essence
        score) can travel through even the worst terrain with ease.
        Travel through most terrain (forest, light marsh, rock and sand
        desert) is about as fast as if the character was walking over flat,
        level ground - characters will travel about 20 miles a day.
        Travel over very harsh terrain (muskeg at high summer, glacier,
        bayou, dense scrub or fresh-growth jungle) is at half this speed.
        "

    food_gathering_technique[Food Gathering Technique]
    trackless_region_navigation_charm --> food_gathering_technique
    click food_gathering_technique callback "
        Food Gathering Technique<br>
        <br>
        Cost: 3 motes per person<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Trackless Region Navigation Charm<br>
        <br>
        A character with this Charm will never go hungry. In
        a hour of foraging for food, she can gather enough nuts,
        berries, edible tubers, slugs, bugs and small animals to make
        a large meal for a number of people equal to her Essence
        score. Note that this skill typically does not involve
        hunting game, and so, the character does not need a
        hunting tool such as a spear, sling or bow — the character
        will probably not bring back anything larger than a rabbit.
        Storytellers may wish to make it more difficult to gather
        food in certain environments (deep sandy desert and pack
        ice, for example) but should not impose a penalty greater
        than halving the Exalted's take. This is, after all, magic.
        "

    unshakeable_bloodhound_technique[Unshakeable Bloodhound<br>Technique]
    hardship_surviving_mendicant_spirit --> unshakeable_bloodhound_technique
    click unshakeable_bloodhound_technique callback "
        Unshakeable Bloodhound Technique<br>
        <br>
        Cost: 8 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Hardship-Surviving Mendicant Spirit<br>
        <br>
        The character can track anyone in the wilderness,
        following the most minute signs and, sometimes, nothing
        more than a magical intuition of where the target has gone.
        The character can track anyone through any terrain, so long
        as the trail is fresh enough. Over difficult terrain for tracking
        (open ocean, rocky desert, grasslands), the trail remains
        fresh for typically one day per point of the tracking character's
        permanent Essence. Over terrain more amenable to tracking,
        it can be two or even three times that long.<br>
        This ability can be foiled by the Traceless Passage Charm.
        If the target is using Traceless Passage, then the tracker and
        target resolve the matter as if neither was using magic. See
        &quot;Tracking&quot; on page 245 of the Drama chapter for details.
        "

    eye_deceiving_camouflage[Eye-Deceiving Camouflage]
    hardship_surviving_mendicant_spirit --> eye_deceiving_camouflage
    click eye_deceiving_camouflage callback "
        Eye-Deceiving Camouflage<br>
        <br>
        Cost: 6 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Hardship-Surviving Mendicant Spirit<br>
        <br>
        Trough the use of this Charm, the character can conceal
        himself or an object no bigger around than his Essence rating
        in yards so well as to be undetectable. In order to gain the
        benefit of this Charm, the character must spend one hour
        camouflaging his position or the object to be concealed. So
        long as the character stays still and takes no violent action, he
        will not be seen. Note that a character or object camouflaged
        in this fashion is essentially fixed in position. If the character
        moves suddenly or at great length, the effect is disturbed and
        the Charm ceases to have its effect.<br>
        Camouflaged objects or characters can be found
        after a number of hours of intensive searching in their
        immediate area equal to the camouflaging character's
        Essence score or by a character with Unsurpassed (Sense)
        Discipline or some similarly powerful perception power
        whose player succeeds in a Perception + Awareness roll
        against the character's Intelligence + Survival. Note that
        camouflage covers scent and other detection methods as
        well as visual stealth.
        "

    traceless_passage[Traceless Passage]
    unshakeable_bloodhound_technique --> traceless_passage
    click traceless_passage callback "
        Traceless Passage<br>
        <br>
        Cost: 5 motes per person, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Unshakeable Bloodhound Technique<br>
        <br>
        Through the use of this Charm, the character can
        make his passage and the passage of additional persons
        equal to his Essence score totally traceless. They cannot be
        tracked by conventional means, not even with the aid of
        tracking animals or other tracking aids. Only characters
        with the Unshakeable Bloodhound Technique Charm
        can follow them, and even then, it's played out as if they
        were tracking him without magical assistance.
        "

    element_resisting_prana[Element-Resisting Prana]
    hardship_surviving_mendicant_spirit --> element_resisting_prana
    click element_resisting_prana callback "
        Element-Resisting Prana<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Hardship-Surviving Mendicant Spirit<br>
        <br>
        Through the use of this Charm, the character becomes
        able to survive in any environment. The character
        can survive in extreme environments, such as the extreme
        heat and toxic fumes within the caldera of active volcanoes,
        can exist underwater with no ill effects and can even
        exist without danger in conditions as harsh as those of the
        elemental poles. While this Charm is active, the character
        adds her Endurance to her soak when she takes damage
        from elemental sources such as cold, fire and lightning.
        "
