---
config:
  theme: dark
---

flowchart TD

    harmonious_presence_meditation[Harmonious Presence<br>Meditation]
    click harmonious_presence_meditation callback "
        Harmonious Presence Meditation<br>
        <br>
        Cost: 6 motes<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Presence: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        An Exalted using this Charm increases her personal magnetism
        greatly, making her words seem wise and her arguments
        persuasive. While this Charm is in effect, add a number of dice
        equal to her permanent Essence to any Socialize, Presence or
        Bureaucracy rolls that involve one-on-one interactions.
        "

    listener_swaying_argument[Listener-Swaying<br>Argument]
    harmonious_presence_meditation --> listener_swaying_argument
    click listener_swaying_argument callback "
        Listener-Swaying Argument<br>
        <br>
        Cost: 2 motes per die, 1 Willpower<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Presence: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Harmonious Presence Meditation<br>
        <br>
        The character can use Essence to make himself almost
        irresistibly persuasive. For every two motes of Essence spent
        on this Charm, add another die to any Socialize, Presence or
        Bureaucracy roll involving one-on-one interaction. A character
        cannot more than double his pool using this Charm.
        "

    hypnotic_tongue_technique[Hypnotic Tongue Technique]
    listener_swaying_argument --> hypnotic_tongue_technique
    click hypnotic_tongue_technique callback "
        Hypnotic Tongue Technique<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: Special<br>
        Type: Simple<br>
        Minimum Presence: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Listener-Swaying Argument<br>
        <br>
        Through this Charm, an Exalted can program a target to
        undertake an action at a future time. The Exalted must touch
        the target, and the player makes an opposed Willpower roll.
        If the Exalted wins the Willpower roll, she may give the target
        an unspoken command. This command can be as specific and
        elaborate as the character wishes, and the target will not be
        aware of having received it. The suggestion will stay in place
        for a number of days equal to the Charisma of the Exalted
        using the Charm, after which the target forgets it.<br>
        The command can take no more time to execute than the
        Exalted's Essence score in turns. The target can forget or remember
        the act after executing it, at the choice of the Exalted when the
        suggestion is implanted. Characters will not attack themselves or
        others unless already strongly predisposed to do so. If the target wins
        the Willpower roll, she is instantly aware of what the Exalted has
        attempted to do and what the suggestion and conditions were.
        "

    majestic_radiant_presence[Majestic Radiant Presence]
    harmonious_presence_meditation --> majestic_radiant_presence
    click majestic_radiant_presence callback "
        Majestic Radiant Presence<br>
        <br>
        Cost: 8 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Presence: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Harmonious Presence Meditation<br>
        <br>
        A character with this Charm active burns with the
        incandescent radiance of the Unconquered Sun. The
        players of characters attempting to attack the Exalted or to
        stand against him in argument must make a successful
        Willpower roll to have their characters do so. This Charm
        is not compatible with the Dawn Caste anima power.
        "

    underlying_promoting_touch[Underlying Promoting<br>Touch]
    majestic_radiant_presence --> underlying_promoting_touch
    click underlying_promoting_touch callback "
        Underlying Promoting Touch<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Presence: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Majestic Radiant Presence
        <br>
        This Charm causes the target (typically a mortal servant
        of the Exalted) to be imbued with the majesty of the Exalted's
        office. While this Charm is in effect, individuals will treat him
        with the respect and deference they would normally reserve for
        the Exalted who used the Charm (or for any powerful magical
        being, if they are not acquainted with the target's benefactor).
        Players who wish their characters to do otherwise must succeed
        at a Willpower roll with a difficulty of 1 + the Essence score of
        the Exalted who deputized the character.
        "

    terrifying_apparition_of_glory[Terrifying Apparition<br>of Glory]
    majestic_radiant_presence --> terrifying_apparition_of_glory
    click terrifying_apparition_of_glory callback "
        Terrifying Apparition of Glory<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Presence: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Majestic Radiant Presence<br>
        <br>
        If the Majestic Radiant Presence Charm makes the character
        seem terrible and powerful, then Terrifying Apparition of
        Glory makes him unspeakably so. While Terrifying Apparition
        of Glory is in effect, a successful Valor roll is required to attack
        the character. Most animals, even trained attack animals, will
        simply flee. Players of characters who are not actively hostile to
        the Exalted using Terrifying Apparition of Glory must make a
        successful Conviction roll not to obey immediately any non-suicidal
        orders the character gives. This compulsion lasts for at
        least a scene after the target leaves the Exalted's presence.
        Those who are able to attack the Exalted do so at a die penalty
        equal to the character's Essence score. This Charm is not
        compatible with the Dawn Caste's anima ability.
        "

    subgraph Castebook Dawn
        prey_freezing_gaze[Prey-Freezing Gaze]
        click prey_freezing_gaze callback "
            Prey-Freezing Gaze<br>
            <br>
            Cost: 4 motes<br>
            Duration: One scene or special<br>
            Type: Simple<br>
            Minimum Presence: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Harmonious Presence Meditation<br>
            <br>
            When the character uses this Charm, she impresses a single
            target with the overwhelming power of her commanding
            nature. Targets who fail a Valor roll at difficulty +2 are frozen in
            place, unable to move for the next scene. This paralysis is
            emotional rather than physical, but cannot be broken as long as
            the attacking character continues to gaze intently at the target.
            While keeping this eye contact, the character can be no more
            than five yards from the target. She also cannot move faster than
            a walk or perform any complex or difficult actions. The target
            receives additional Valor rolls whenever anyone harms or
            obviously attempts to harm him. If the character ceases to gaze
            at the target, the paralysis continues for the next three full turns,
            but the target instantly breaks free if anyone harms or obviously
            attempts to harm him. This Charm has no effect on targets
            whose Essence is higher than the casting character's.
            "

        command_voice[Command Voice]
        click command_voice callback "
            Command Voice<br>
            <br>
            Cost: 8 motes<br>
            Duration: One scene<br>
            Type: Simple<br>
            Minimum Presence: 5<br>
            Minimum Essence: 4<br>
            Prerequisite Charms: Hypnotic Tongue Technique<br>
            <br>
            The character surrounds herself with a potent aura of
            authority. Unlike Terrifying Apparition of Glory, this Charm
            does not produce an obvious or overwhelming effect. Instead,
            everyone who is inclined to follow orders — including
            peasants, servants, shop assistants, enlisted military person-
            nel and similar individuals— will obey the character as if she
            were in a position of authority over them. Any target that
            makes a successful opposed Willpower roll against the char-
            acter realizes that the character does not have the authority
            to command him. Everyone else will obey all reasonable-
            sounding commands given by the character. Orders to
            commit suicide, go on killing rampages, or requests to give
            the character most or all of the target's money or possessions
            will end the character's influence over the target, However,
            requests for information or admittance to otherwise restricted
            areas will be instantly granted, as will demands for
            moderately expensive merchandise (up to Resources ••) in
            a shop, even if the character does not pay for it.<br>
            Targets may make another opposed Willpower roll to
            disobey the character if a recognized superior contradicts the
            character's orders. Targets who fail this roll will ignore their
            actual superior's requests. One of this Charm's most potent
            and useful features is that others observing the interaction
            will see nothing odd or magical about the character or the
            target'sreaction. This Charm has no effect on beings with an
            Essence greater than 1, though it has proven effective on Fair
            Folk commoners and other supernatural creatures of an
            inherently servile nature.
            "
    end

    harmonious_presence_meditation --> prey_freezing_gaze
    hypnotic_tongue_technique --> command_voice

    subgraph Castebook Zenith
        impassioned_orator_technique[Impassioned Orator<br>Technique]
        click impassioned_orator_technique callback "
            Impassioned Orator Technique<br>
            <br>
            Cost: 5 motes<br>
            Duration: One turn<br>
            Type: Supplemental<br>
            Minimum Presence: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Listener-Swaying Argument<br>
            <br>
            An Exalted acting in accordance with virtue is an
            impressive figure indeed — an Exalted using this Charm
            is even more so. By using this Charm, the Chosen puts
            the weight of her passions behind her arguments. She
            may add one of her Virtue ratings in automatic successes
            to a single Presence roll. The Virtue may be chosen
            when the Charm is invoked, but the Exalted must be
            acting in accordance with the virtue in question. If the
            Exalted is not, or does not, act according to the Virtue,
            the Essence is spent, but no bonus is gained. Invoking
            this Charm automatically adds one point to the
            character's Limit.
            "

        countenance_of_vast_wrath[Countenance of Vast<br>Wrath]
        impassioned_orator_technique --> countenance_of_vast_wrath
        click countenance_of_vast_wrath callback "
            Countenance of Vast Wrath<br>
            <br>
            Cost: 10 motes<br>
            Duration: One scene<br>
            Type: Simple<br>
            Minimum Presence: 4<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Impassioned Orator Technique<br>
            <br>
            When driven by his passions, an Exalted can be an
            almost irresistible force. Through the use of this Charm,
            one of the Chosen may spend Essence to let the
            strength of her virtue strike fear in the hearts of those
            who would oppose her. For the remainder of the Scene,
            any character with a Willpower lower than the Exalted's
            current Limit suffers a penalty to his dice pools equal
            to the Exalt's Essence when attempting to attack her.
            Invoking this Charm automatically adds one point to
            the character's Limit, which counts toward the
            character's Limit for the purposes of determining this
            Charm's effect.
            "
    end

    listener_swaying_argument --> impassioned_orator_technique

    subgraph Castebook Eclipse
        rose_lipped_seduction_style[Rose-Lipped<br>Seduction Style]
        click rose_lipped_seduction_style callback "
            Rose-Lipped Seduction Style<br>
            <br>
            Cost: 1 mote<br>
            Duration: Instant<br>
            Type: Supplemental<br>
            Minimum Presence: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Harmonious Presence Meditation<br>
            <br>
            Infused with Essence, the Exalt becomes incredibly
            attractive to a particular person that she wishes
            to seduce. The Chosen's Presence Ability is doubled
            for the purpose of seducing her chosen target. These
            are Charm bonus dice and count against dice pool
            maximums.
            "
    end

    harmonious_presence_meditation --> rose_lipped_seduction_style
