---
config:
  theme: dark
---
flowchart TD

    dynamic_reaction_enhancement_system[Dynamic Reaction<br>Enhancement System]
    click dynamic_reaction_enhancement_system callback "
        Dynamic Reaction Enhancement System<br>
        <br>
        Cost: 1 mote per +2 Initiative<br>
        Installation Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Dexterity: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        At times, Alchemical Exalted must react swiftly and
        with great purpose. This Charm uses Essence to fuel and
        enhance the Exalt's reactions, slowing the world around
        her until it seems like everything else is moving in slow
        motion. For every mote of Essence the Alchemical spends
        activating this Charm, she may increase her Initiative
        score by +2 for the turn. The Exalt cannot spend more
        motes of Essence activating this power than she has points
        of Dexterity. The Reaction Enhancement System is installed
        on the Alchemical's spine.
        "

    celerity_enabling_module[Celerity Enabling<br>Module]
    dynamic_reaction_enhancement_system --> celerity_enabling_module
    click celerity_enabling_module callback "
        Celerity Enabling Module<br>
        <br>
        Cost: 5 motes and 1 Willpower<br>
        Installation Cost: 1 mote<br>
        Duration: Instant/one scene<br>
        Type: Reflexive<br>
        Minimum Dexterity: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Dynamic Reaction Enhancement System<br>
        <br>
        Although the Reaction Enhancement System makes
        the Alchemical's perception-reaction cycle incredibly
        short, it does nothing to enhance her own speed, and the
        Exalt can often be trapped in a situation where she has a
        perfect understanding of the danger and yet is totally
        unable to react quickly enough to save herself. The Celerity
        Enabling Module is an addition to the Dynamic
        Enhancement Reaction System that uses Essence conductors
        laced throughout the body to supplant the character's
        own human-like reflexes. Though it is expensive and
        draining, it allows the Exalt to exhibit tremendous speed.<br>
        In its primary use, the Charm generally increases the
        Exalted's speed. The Exalt gains a number of extra actions for
        the turn equal to her permanent Essence score. In its second-
        ary use, the Charm enables the Alchemical's body to
        automatically react to a specific threat without the Exalt even
        considering it. In this mode, the Exalted chooses one target.
        For the rest of the scene, she can automatically dodge or parry
        (her choice on a per-attack basis) all the target's attacks
        against her at her full dice pool, even ones she cannot perceive.<br>
        This secondary effect can only be targeted at a single
        individual at a time. The Charm must be activated again
        to switch its focus, and the Exalted's ability to defend
        herself against the first target ends the instant she switches
        targets. While the Alchemical is reacting to the actions of
        a single individual, the Celerity Enabling Module is not
        able to activate its primary function and increase her
        speed. The Exalt can have either automatic defense or
        extra actions, not both. The Celerity Enabling Module is
        visible as implants on the Alchemical's joints.
        "
