---
config:
  theme: dark
---
flowchart TD

    auxiliary_essence_storage_unit[Auxiliary Essence<br>Storage Unit]
    click auxiliary_essence_storage_unit callback "
        Auxiliary Essence Storage Unit<br>
        <br>
        Cost: None<br>
        Installation Cost: 2 motes<br>
        Duration: Permanent<br>
        Type: Special<br>
        Minimum Manipulation: 1<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm installs extra Essence reservoirs on an
        Alchemical, allowing him to use more power at the cost of
        subtlety. For each time this Charm is taken, the Alchemical
        gains an additional 10 points of Peripheral Essence.
        The Exalted cannot take this Charm more times than he
        has points of permanent Essence or more times than he can
        afford to pay the Personal Essence for.
        "
