---
config:
  theme: dark
---
flowchart TD

    personal_gravity_manipulation_apparatus[Personal Gravity<br>Manipulation Apparatus]
    click personal_gravity_manipulation_apparatus callback "
        Personal Gravity Manipulation Apparatus<br>
        <br>
        Cost: 3 motes<br>
        Installation Cost: 2 motes<br>
        Duration: Scene<br>
        Type: Simple<br>
        Minimum Strength: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm allows the Alchemical Exalted to twist
        gravity in the immediate vicinity, letting him decide where
        &quot;down&quot; is in relation to himself. This allows the Alchemical to
        walk or run along any slope as if it were flat ground, including
        walls and ceilings. The surface that the character stands upon
        is not strengthened in any way. The down-ness only extends a
        lew feet from the soles of the character's shoes. If the character
        jumps too high or is pulled far enough away from a surface, he
        will once again have the same &quot;up&quot; and &quot;down&quot; as the rest of the
        world, quite possibly resulting in serious injury.
        The alternate ability of this Charm allows the Exalted to
        use this Charm to control his own weight, reducing it up to 1/
        8 of normal. The character's movement speed is increased by
        50 percent when he weighs more than half his normal weight
        and increased by 100 percent when he weighs less than half
        his normal weight. Obviously, the Exalt will have difficulty
        running in certain situations, and the Storyteller should call
        for Dexterity + Athletics rolls if he tries to change directions
        quickly or run in strong crosswinds. As with all multipurpose
        Alchemical Charms, the player must state which variation of
        the Charm he wishes to use before spending Essence.
        The Personal Gravitation Apparatus is housed entirely
        in the lower legs.
        "

    parabolic_leap_overcharger_device[Parabolic Leap Overcharger<br>Device]
    personal_gravity_manipulation_apparatus --> parabolic_leap_overcharger_device
    click parabolic_leap_overcharger_device callback "
        Parabolic Leap Overcharger Device<br>
        <br>
        Cost: 2 motes per turn<br>
        Installation Cost: 1 mote<br>
        Duration: Special<br>
        Type: Reflexive<br>
        Minimum Strength: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Personal Gravity Manipulation Apparatus<br>
        <br>
        The character further reduces his reliance upon the
        strictures of gravity by channeling Essence through his lower
        legs and leaping gracefully through the air, his anima flowing
        from the base of his feet in a brilliant contrail that colors the
        air behind him. The character's ascent is slow but steady,
        allowing him to rise up to Strength x 3 feet per turn and move
        up to Strength x Essence feet horizontally. The character can
        perform any action while airborne and can change his direction
        in mid-air at will. The Parabolic Leap Overcharger
        Device allows the character to attain a total height of no more
        than Strength x 15 feet of height from a surface sturdy enough
        to support his weight. Note that if a character ends the tur
        in the air, she must activate the Parabolic Leap Overcharger
        Device Charm again the next turn or fall to the ground. A
        character can descend any amount of distance safely using the
        Overcharger Device by activating it for a single turn shortly
        before impact, a useful safety device for Alchemicals who
        spend most of their time working in high, exposed areas.
        As an alternate use of this Charm, the character can opt
        to make a quick &quot;bound,&quot; describing a long arc in the span
        of a single turn, covering a distance up to Strength x Essence
        feet high and five times that long. Using the Parabolic
        Overcharger in this manner during successive turns allows
        the character to &quot;leapfrog,&quot; bounding rapidly over terrain.
        The Exalted can attack on the same turn he activates the
        Parabolic Overcharger, but gains no special bonuses for it.
        The components for the Parabolic Overcharger are
        installed on the rear of each leg behind the knee.
        "
