---
config:
  theme: dark
---
flowchart TD

    salt_into_ash_sleight[Salt Into Ash Sleight]
    click salt_into_ash_sleight callback "
        Salt Into Ash Sleight<br>
        <br>
        Cost: 2 motes + 2 motes per target number reduction<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Clapping her hands, the character surrounds an elemental
        or spirit of water or the sea in a fiery yellow aura.
        Mercury calls that creature to journey. Its reasons to visit
        another place, where important unfinished business awaits
        it, press increasingly upon its mind. Simply by using the
        Charm, the Exalt proves and guarantees that such business
        already exists in some distant place. If necessary, the creature
        becomes aware of it. The creature must make a Willpower
        roll not to set forth immediately. For the duration of the
        scene, Mercury's call reduces the target number for any
        character's attempts to drive the creature away, physically or
        socially. This benefit applies to both attack and damage rolls.
        "

    stone_skipping_spirit[Stone Skipping Spirit]
    click stone_skipping_spirit callback "
        Stone Skipping Spirit<br>
        <br>
        Cost: 5 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The character exhales a puff of wind that travels
        beyond the world and disentangles the destiny of ship,
        sky and sea. No matter how fierce the weather or the
        waves, the ship sails smoothly, isolated from the world.
        For the duration of the scene, Sail checks made for the
        character ignore environmental penalties. He sails on
        a placid sea, with a good wind behind him and the favor
        of the local spirits, even if a typhoon rages around his
        location. He still suffers penalties for any damage the
        ship has taken, but it takes on no further water, and its
        condition does not degenerate naturally for the remainder
        of the scene.
        "

    mirror_shattering_method[Mirror-Shattering Method]
    stone_skipping_spirit --> mirror_shattering_method
    click mirror_shattering_method callback "
        Mirror-Shattering Method<br>
        <br>
        Cost: 5 motes<br>
        Duration: Five days<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 2<br>
        <br>
        Prerequisite Charms: Stone Skipping Spirit<br>
        <br>
        The character casts salt into a puddle or body of
        water beneath her. Its surface breaks and dissolves into
        foaming whitecaps, and the character vanishes. From
        her perspective, the whitecaps rush out in all directions,
        and then, she stands atop a field of white that is — at any
        given moment — water, wind-blown flower petals or
        butterflies. The world around her fades away as she
        separates herself from the normal processes of fate.<br>
        While this Charm remains active, the character can
        travel at twice her normal pace, ignoring any obstacles.
        She remains in Creation, but her presence and location
        are obscured. Only the slightest shimmer in the wind
        marks her passing, which increases the difficulty of
        Awareness checks to notice her or Survival checks to
        track her by 2. She cannot sense the world around her at
        all. Nevertheless, when the Charm ends, she invariably
        finds herself in an auspicious location. If at all possible
        given the distance and general direction of her journey,
        she does not find herself in immediate danger, under
        observation or in a precarious location when she arrives.<br>
        The character can use this Charm when on board a
        ship (or any construct suspended entirely above a body
        of water) by casting salt into the water below. The entire
        ship and crew then travels with her. It sails at twice its
        normal speed across the field of white. An auspicious
        location for a ship's arrival includes the existence of
        water sufficient to keep it afloat.<br>
        As an alternative to mortal travel, a character using
        this Charm can travel to Yu-Shan. This requires five
        days on foot or a day on shipboard. Travel to other
        unusual locations, such as Malfeas, may be possible at the
        Storyteller's discretion. This always requires five days.
        "

    five_ordeals_odyssey[Five Ordeals Odyssey]
    salt_into_ash_sleight --> five_ordeals_odyssey
    mirror_shattering_method --> five_ordeals_odyssey
    click five_ordeals_odyssey callback "
        Five Ordeals Odyssey<br>
        <br>
        Cost: 10 motes, 1 Willpower, 1 health level<br>
        Duration: One hazard<br>
        Type: Simple<br>
        Minimum Sail: 4<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: Salt into Ash Sleight, Mirror Shattering Method<br>
        <br>
        This Charm uses a prayer strip marked with the
        scripture of the Maiden at Sea. The character casts it at
        an adversarial force, and it hangs in the air, wreathed in
        dandelion-hued lightning, until the resolution of the
        Charm destroys it.<br>
        The character may use this Charm when faced with
        any meaningful hazard at sea: storms, thirst while be-
        calmed, pirates, monsters, reefs, mutiny and so forth.
        The character must then take action to remove the
        hazard as a practical threat to her life, health and progress.
        If she ensures that it cannot reasonably prevent a safe
        conclusion to her journey, the Charm marks her victory
        by wreaking massive damage upon the force that op-
        posed her. It tears storms from the sky, breaks the calm
        in a fierce wind, splits the pirate ship in two, consumes
        the monster's corpse with fire and so forth. It kills extras
        and shatters inanimate things. Defeated characters suf-
        fer sufficient bashing damage to reduce them instantly to
        Incapacitated, although fate restores their consciousness
        (healing them to -4) if they face an immediate threat to
        life and limb before waking. In general, the prayer strip
        accomplishes this devastation in the moment of its own
        destruction, casting forth fire, thunder and lightning.<br>
        Each travail speeds the character toward her destiny,
        granting an ever-greater attunement to the Essence
        flows of fate and the world. Each time the character
        invokes this Charm and permits it to run its full duration,
        increase her effective permanent Essence by 1, to a
        maximum of 8. Also, increase the effective permanent
        Essence of characters working closely with her by 1, to a
        maximum of 6. These bonuses last until the end of the
        story, but cannot be used as a basis for training or for
        gaining Charms.<br>
        This Charm requires that the voyage have a purpose
        — the character cannot simply sail around in circles and
        must have some reason to travel across the sea. However,
        the character can freely favor sailing over other means of
        travel when it forms a reasonable alternative. Characters
        cannot learn otherwise unavailable Charms while under
        the effect of the Five Ordeals Odyssey.
        "
