---
config:
  theme: dark
---
flowchart TD

    absence[Absence]
    click absence callback "
        Absence<br>
        <br>
        Cost: 1 mote per difficulty point<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Dodge: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Sidereals are not the fiercest warriors of the
        Exalted. However, their ability to glimpse the future
        makes them surprisingly effective in combat. The Charm
        allows an Exalted to predict where a blade or blow will fall
        in advance, so they can be somewhere else when it does.
        Like many other Sidereal Charms, the player can decrease
        the number that she must roll on a die for it to count as a
        success. In this case, the player can reduce the success
        number of a Dexterity + Dodge roll by one. As always, the
        success number cannot be reduced below 4.
        "
