---
config:
  theme: dark
---
flowchart TD

    wise_choice[Wise Choice]
    click wise_choice callback "
        Wise Choice<br>
        <br>
        Cost: 6 motes<br>
        Duration: Instant<br>
        Minimum Lore: 2<br>
        Minimum Essence: 1<br>
        <br>
        Life is full of choices. This Charm gives a Sidereal the
        edge on mere mortals by allowing them to make the best
        choice when confronted with many options. However, this
        Charm allows only a brief peek into the future, not an
        extended glimpse into all the consequences of the decision.
        So, the short-term benefits won through using Essence in this
        way might easily be outweighed by the long-term downfalls.
        "
