---
config:
  theme: dark
---
flowchart TD

    force_decision[Force Decision]
    click force_decision callback "
        Force Decision<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Presence: 3<br>
        Minimum Essence: 2<br>
        <br>
        The ability to predict possible futures is of little use
        without the ability to make the outcome you prefer come
        to pass. This Charm allows a Sidereal to channel Essence
        into another being briefly, forcing them to make the
        decision the Sidereal desires. The player makes a Manipulation
        + Presence roll with a difficulty equal to the target's
        Essence. Success indicates the target will make the decision
        the way the Sidereal wishes.
        "
