---
config:
  theme: dark
---
flowchart TD

    prior_warning[Prior Warning]
    click prior_warning callback "
        Prior Warning<br>
        <br>
        Cost: 5 motes<br>
        Duration: One hour<br>
        Minimum Awareness: 2<br>
        Minimum Essence: 1<br>
        <br>
        Once a Sidereal has committed Essence to this Charm,
        her perceptions are constantly probing into the immediate
        future for anything that could do her harm. When the
        character is in danger, her player makes a Wits + Awareness
        roll. If the character succeeds, she has a feeling of ill
        ease that informs her of impending danger. The character
        will get a warning period of two minutes per success rolled.
        While the warning she gets does not necessarily allow her
        to avoid the danger completely, it allows her at least a little
        time to prepare. This Charm only allows the Sidereal to
        spot obvious harm: slow-acting poison concealed in her ale
        would not set off the warning because the effect is too far
        in the future. However, it might be triggered just before the
        effects kick in, giving the character time to deduce the
        cause and seek a cure.
        "
