---
config:
  theme: dark
---
flowchart TD

    language_learning_ritual[Language-Learning<br>Ritual]
    click language_learning_ritual callback "
        Language-Learning<br>Ritual<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One week<br>
        Type: Simple<br>
        Minimum Linguistics: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Dragon-Blooded embarking on diplomatic missions
        often invoke this Charm. By spending an hour meditating
        and listening to a native speak the language to be learned,
        the Exalt absorbs the knowledge of the language into her
        mind. The character needs some sort of focus to meditate
        on, usually a cultural object related to or a book written in
        the language to be learned. For the Charm's duration, the
        Dragon-Blooded is completely fluent and naturally conversant
        in the language, without even a trace of an accent.
        The character may also read and write the language. Once
        the duration expires, the knowledge fades immediately.
        "

    thousand_tongues_meditation[Thousand Tongues<br>Meditation]
    language_learning_ritual --> thousand_tongues_meditation
    click thousand_tongues_meditation callback "
        Thousand Tongues<br>Meditation<br>
        <br>
        Cost: 4 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Linguistics: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Language-Learning Ritual<br>
        <br>
        The far-ranging colonial interests of the Dragon-
        Blooded combine with the Air-aspected Exalt's close
        affinity with communication to make this Charm a
        common one.<br>
        The character speaking in tongues can easily speak
        and understand any spoken language for the duration of
        the Charm. If speaking to beings each speaking a different
        language, the character can understand them all, and they
        can all understand the character — but they will still be
        unable to understand each other. The maximum number
        of beings that an Exalted may speak in tongues to at once
        is equal to the character's permanent Essence.<br>
        This Charm just allows the most basic of communication-
        the equivalent of baby or pidgin speech. Any sort
        of social or communicative actions attempted by the
        character are at -4 to her dice pools. Each point of
        permanent Essence that the Dragon-Blood possesses over the
        minimum requirement reduces this penalty by -1.
        This Charm only works on actual speech. Sign language
        cannot be understood, through the use of the
        Thousand Tongues Meditation.
        "

    poisoned_tongue_technique[Poisoned Tongue<br>Technique]
    thousand_tongues_meditation --> poisoned_tongue_technique
    click poisoned_tongue_technique callback "
        Poisoned Tongue Technique<br>
        <br>
        Cost: 2 motes, 1 Willpower<br>
        Duration: Concentration<br>
        Type: Simple<br>
        Minimum Linguistics: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Thousand Tongues Meditation<br>
        <br>
        This Charm allows an Exalted to &quot;hijack&quot; another's
        conversation. The effect is subtle, but it can be deadly if
        applied correctly. The Exalt must be able to hear the
        conversation to twist it, but need not actually be present.
        Eavesdropping through Charms such as Voices on the
        Wind is perfectly permissible, but the range of this
        Charm cannot be extended past 100 feet x the Exalt's
        permanent Essence.<br>
        To twist a conversation, the character's player must
        roll Manipulation + Linguistics. The number of successes
        indicates the degree to which the Dragon-Blooded can
        twist the conversation. A single success would allow her to
        send someone away from a conversation confused, aroused
        or with a sour taste in his mouth. Three or more successes
        are enough to make a speaker seem heroic, amorous,
        ruthless or offensive. Five successes allow the Dragon-Blood
        to completely hijack the conversation, changing or
        amending anything said by any party.<br>
        The participants in the conversation each get a reflexive
        Wits + Perception roll at a roll to notice the use of
        this Charm. The difficulty of the roll is the Essence of the
        Exalt using this Charm. If this roll fails, the character
        doesn't realize that what he means to say and what he's
        actually saying doesn't match and has no way of knowing
        the conversation was altered. If the roll succeeds, he
        realizes the conversation is being manipulated and can
        indicate this through nonverbal means (normally a chop-
        ping motion at one's own throat). Use of this Charm in a
        criminal fashion is a serious offense in the Realm and can
        bring with it a death sentence.
        "

    voice_of_mastery[Voice of Mastery]
    poisoned_tongue_technique --> voice_of_mastery
    click voice_of_mastery callback "
        Voice of Mastery<br>
        <br>
        Cost: 5+ motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Linguistics: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Poisoned Tongue Technique<br>
        <br>
        With more complete mastery of the Air element, the
        Dragon-Blooded can use this Charm to enhance the effect
        of his spoken words. His words seem to resonate with
        listeners, seeming more persuasive, threatening, seductive
        - whatever the Dragon-Blood wishes.<br>
        For the duration of this Charm, the character may add
        his Essence dice to his dice pool for any interaction involving
        speech, whether it is seduction, persuasion or intimidation.
        The Charm normally affects only one listener. Each additional
        mote doubles the number of people affected by the
        Charm. The character must be able to speak the targets
        language, either naturally or through the use of Charms.
        "

    wind_carried_words_technique[Wind-Carried<br>Words Technique]
    click wind_carried_words_technique callback "
        Wind-Carried Words Technique<br>
        <br>
        Cost: 1 mote per sentence, plus distance<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Linguistics: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        The wind carries many things, and sound can be one
        of them. A Terrestrial Exalted can set his words on the
        currents of the wind, sending them through the air to the
        ear of the one he wishes to hear his message.
        For the base Essence cost, a character may send on
        single sentence to the ear of any other person in range. The
        character does not actually have to speak what he wishes
        to say out loud, but he does at least have to vaguely mouth
        the words he wishes to send.<br>
        The difficulty of sending words on the wind increases
        over distance. The further away a character wants to send
        a message, the more difficult the Charm becomes. For a
        single mote of Essence, a character can send a single
        sentence to roughly 100 feet away. This distance is modified
        by the permanent Essence of the character and by the
        expenditure of additional motes of Essence. Multiply the
        100-foot range by the character's permanent Essence score.
        In addition, by doubling the amount of Essence spent on
        the Charm, this modified base range can be increased by a
        factor of 10. An Air-aspected Dynast with an Essence of 4
        could send a single sentence 400 feet for 1 mote, 4,000 feet
        for 2 motes, 40,000 feet for 3 motes and so on.
        The sending character must have a general sense of
        the target's direction, but need not see her. This Charm
        has become essential to the Realm's military operations, as
        it gives the Terrestrial Exalted the ability to communicate
        quickly over long distances on the battlefield. Most Dragon
        Blooded of military inclination know the Charm.
        "

    voices_on_the_wind[Voices on the<br>Wind]
    wind_carried_words_technique --> voices_on_the_wind
    click voices_on_the_wind callback "
        Voices on the Wind<br>
        <br>
        Cost: 3 motes, plus distance<br>
        Duration: One minute<br>
        Type: Simple<br>
        Minimum Linguistics: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Wind-Carried Words Technique<br>
        <br>
        Speech requires breath, the very air of life. Some
        Dynasts of Air can extend their senses through the air and
        so listen to what people far from them say. The further
        away a character wants to eavesdrop, the more expensive
        the Charm becomes. For the basic cost, an Air-aspected
        Dragon-Blood can clearly hear normal speech from 100
        feet away. The character also gets a general sense of the
        target's direction (assuming he doesn't know already). As
        with the Wind-Carried Words Technique, the cost of
        using this Charm increases over distance. The further
        away a character wants to eavesdrop, the more expensive
        the Charm becomes. For a single mote of Essence, a
        character can listen in on speech roughly 100 feet away.
        This distance is modified by the permanent Essence of the
        character and by the expenditure of additional motes of
        Essence. Multiply the 100-foot range by the character's
        permanent Essence score. In addition, by doubling the
        amount of Essence spent on the Charm, this modified base
        range can be increased by a factor of 10.<br>
        This Charm has some limitations. The character must
        specify a single person he wants to spy upon: He cannot, for
        instance, declare that he will &quot;listen for people plotting
        against me.&quot; At most, he can make a list of suspected
        enemies and eavesdrop on them one by one. The character
        also cannot hear anything spoken in an airtight chamber.
        Many of the powerful Dynasts build such chambers for
        their privy councils, specifically to defeat this Charm.
        Finally, listening to a person from so far away demands
        total concentration — the character cannot perform any
        other action while listening to Voices on the Wind.
        "

    with_one_mind[With One Mind]
    voices_on_the_wind --> with_one_mind
    voice_of_mastery --> with_one_mind
    click with_one_mind callback "
        With One Mind<br>
        <br>
        Cost: 2 motes per dot of increase<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Linguistics: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Voices on the Wind, Voice of Mastery<br>
        <br>
        A Dynast of Air can enable a group of people to know
        each other's surface thoughts. What one sees, all the others
        see as well. Her tactical decisions are an open book to her
        allies. As a result, a group that fights using With One Mind
        displays uncanny coordination. They trade off opponents
        without a hitch; one fighter parries a blow aimed at
        another; an enemy seen by one cannot hide from any.<br>
        For each mote that the Dragon-Blooded character
        spends, the recipients gain one dot each of Wits, Perception
        and Melee, up to the Dragon-Blooded character's own
        Linguistics rating. In addition, any of the linked characters
        can parry or abort to parry an attack against any other
        character in the group, provided he is close enough to
        plausibly do so. If multiple characters parry a given attack,
        subtract all their successes from the attack roll.<br>
        The initiating character can link as many people
        using With One Mind as she has dots of Essence, but all
        those linked must have the same level of linkage, and the
        Exalt must pay to enhance each of them. The linked
        group must include the character herself, and there is no
        benefit to be gained from using this Charm unless at least
        two people are linked with it. Dynasts typically use this
        Charm to magnify the fighting prowess of their bodyguards
        or minions.<br>
        Characters linked by this Charm must have trained
        together for at least a week. They must spend a turn on
        a shared breathing exercise and war-shout to initiate
        the link. The characters must also stay within 50 feet x
        highest Essence of the participants of one another. If
        any character moves beyond that range, the link breaks,
        and the Charm ends.<br>
        This Charm also has non-combat uses, allowing instantaneous
        nonverbal communication between the linked
        group for the duration.
        "
