---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph water_occult[Water Occult Charms]
        direction TB

        spirit_reflecting_bowl[Spirit-Reflecting Bowl Technique]
        click spirit_reflecting_bowl callback "
            Spirit-Reflecting Bowl Technique<br>
            <br>
            Cost: 3 motes<br>
            Duration: Until disrupted<br>
            Type: Simple<br>
            Minimum Occult: 2<br>
            Minimum Essence: 1<br>
            Prerequisite Charms: None<br>
            <br>
            Water has deep connections to the spirit world.
            Dragon-Blooded characters with occult interests can use
            this connection to see and communicate with the unseen
            spirits of the world. The character requires nothing more
            than an ordinary bowl of water. As long as the Dynast
            concentrates, she can see nearby spirits reflected in the
            water and hear what they say. A clever Dragon-Blood
            might even do this without the spirits noticing - for
            instance, by using a goblet of water and taking a sip now
            and then, while pretending to do something else.<br>
            Cascade Charms:<br>
            • More powerful and learned Dynasts can actually
            search for a spirit using a bowl of water, and communicate
            with it at a distance.
            "

    end

