---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph fire_lore[Fire Lore Charms]
        direction TB

        fire_blast_trap_trick[Fire Blast Trap Trick]
        click fire_blast_trap_trick callback "
        Fire Blast Trap Trick<br>
        <br>
        Cost: 1 mote<br>
        Duration: Until triggered<br>
        Type: Simple<br>
        Minimum Lore: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        This peculiar Charm finds use among Dragon-Bloods
        who worry about thieves. It takes a clever hand, though, to
        trap a fire inside a box, jar or bottle so that it can't go out.
        The Dynast must place a bit of fuel inside the container —
        firedust from the far south works best — set it on fire, then
        slap the lid shut and seal it just right. When someone opens
        the container, the captive fire explodes, much larger and
        hotter from anger at being trapped. A typical use for the
        fire trap is to rig it inside a trunk or cupboard so that anyone
        who opens it the wrong way pops open the hidden container
        and set off the trap.<br>
        Like most Charms with long-term effects, the fire trap
        &quot;ties up&quot; the mote of Essence used to set it up. For this
        reason, the Aspects of Fire do not manufacture fire traps by
        the dozen. Creating a fire trap takes just a minute, but the
        trap itself can last indefinitely. The trap lasts even after its
        creator's death, if she never reclaimed its Essence. The fire
        trap's explosion has a three-foot radius. The player rolls
        Dexterity + Lore. As well as causing a flash and loud bang,
        for each success the player rolls, the trap does a number of
        points of lethal damage equal to the Essence of the Exalted
        who set the trap, soaked normally. Obviously, fire traps are
        unsuitable for guarding anything that flame could destroy.<br>
        Cascade Charms:<br>
        • The Fire Blast Trap Trick needs few improvements.
        One possibility is an improved fire trap whose flame fills a
        larger area.
        "

    end

    %% described in Storyteller's Companion
    subgraph wood_lore[Wood Lore Charms]
        direction TB

        ten_seasons_growth_discipline[Ten Season's Growth<br>Discipline]
        click ten_seasons_growth_discipline callback "
            Ten Season's Growth Discipline<br>
            <br>
            Cost: 1 mote per minute of use<br>
            Duration: Instant<br>
            Type: Simple<br>
            Minimum Lore: 2<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: None<br>
            <br>
            By communing with the living spirit of a plant, a
            Dragon-Blooded character can rouse it to grow with impossible,
            supernatural speed. A seed can grow into a flower.
            A seedling can become a sturdy sapling. What's more, the
            character can shape the plant's growth. Although instant
            topiary is an esthetically pleasing application, a character
            can also grow trees so they crack stone walls with their
            roots, produce living ladders from ivy or perform other
            useful tricks.<br>
            To employ this Charm, the character must lightly
            stroke the target plant, softly hum or sing to the spirit
            within it and supply it with water. For every minute and
            mote of Essence expended, the plant experiences up to a
            full year's worth of growth. Thus, growing an annual flower
            from a seed requires only one minute and one mote of
            Essence; growing an oak tree 20 years old from an acorn
            takes 20 minutes and 20 motes of Essence.<br>
            Cascade Charms:<br>
            • With greater Lore or Essence, the character could
            learn to grow and shape trees with greater speed and less
            cost of Essence.<br>
            • A plant might actually animate for a short time to
            work the Dragon-Blooded character's will.<br>
            • A plant could grow supernaturally large. A bower of
            giant flowers aids any courtship; more bizarre options
            include giant gourds or pumpkins as houses or boats.<br>
            • A really powerful Dynast might be able to make a
            tree grow around a captured enemy, trapping him in
            ageless slumber until someone cuts the tree down.
            "

    end

