---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph wood_throw[Wood Throw Charms]
        direction TB

        hurled_branch_arrow_technique[Hurled Branch Arrow<br>Technique]
        click hurled_branch_arrow_technique callback "
            Hurled Branch Arrow Technique<br>
            <br>
            Cost: 2 motes<br>
            Duration: Instant<br>
            Type: Simple<br>
            Minimum Thrown: 2<br>
            Minimum Essence: 1<br>
            Prerequisite Charms: None<br>
            <br>
            Through this Charm, a Dragon-Blooded character
            charges any convenient stick or scrap of wood with Essence.
            When he then throws the Essence-charged wood, it
            flies through the air as smoothly as an arrow from a bow —
            and does as much damage. The character rolls Dexterity +
            Thrown, and the improvised missile inflicts damage based
            on its shape — most are point, fowling or frog crotch. The
            weapon has the same range increment as a compound bow.<br>
            Cascade Charms:<br>
            • When the character achieves greater throwing skill,
            she could improve the range or damage of the arrow.
            Alternatively, she might Combo the Charm with Archery-based
            Charms.<br>
            • A character with a higher Essence rating might gain
            the ability to harm spirits with this Charm, or multiply the
            improvised missile's effect in various ways. (See the Archery
            and Thrown Charms for Solars in Exalted for
            inspiration, but tone down their effect and increase the
            Essence costs for Dragon-Blooded characters.)<br>
            • For a variation, a character might have a Charm
            enabling her to use any convenient scrap of wood as a
            melee weapon.
            "

    end

