---
config:
  theme: dark
---
flowchart TD

    stormwind_calling_method[Stormwind Calling Method]
    click stormwind_calling_method callback "
        Stormwind Calling Method<br>
        <br>
        Cost: 5 motes<br>
        Duration: 1 hour<br>
        Type: Simple<br>
        Minimum Occult: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Dragon-Blooded are not born occultists and
        magicians like some Celestial Exalted, but many of them
        study the supernatural lore of their favored element. Many
        Aspects of Air learn the ways of the spirits who create the
        weather through their dances and processions in the sky.
        Exalted who know the ways of the sky-spirits can call them
        to direct the wind. One must speak to the elementals in
        their own tongue: the sounds of wind sighing over stony
        crags and through treetops, and the rumbles of thunder.
        Some Aspects of Air imitate such sounds with their voice
        and a bullroarer. Others might play a flute or position a
        harp so the wind plucks its strings. Inviting the winds to
        blow takes five minutes.<br>
        This basic Charm evokes nothing more than a stiff
        breeze — still enough to interfere with archery or send a
        sailing ship scudding through the waves at top speed
        During the hour of the Charm's effect, the character can
        control the magic wind's direction by singing and whirling
        his bullroarer for a turn.<br>
        Cascade Charms:<br>
        • As the character's Essence rating rises, Charms for
        more powerful winds become possible, all the way up to
        gale force. Old tales mention the great Lords of Air who
        could evoke hurricanes and tornadoes by working together.
        That may be true, but nobody has done it recently.<br>
        • A character can also show greater mastery of the air
        through Charms to command lightning, hail, snow and
        other sorts of storms. (Some of these Charms are also
        suitable for Dragon-Blooded attuned to Water.)
        "


