---
config:
  theme: dark
---
flowchart TD

    element_blow_technique[Element Blow Technique]
    click element_blow_technique callback "
        Element Blow Technique<br>
        <br>
        Cost: Varies<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Melee: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Terrestrial Exalted charges her weapon with the
        Essence of her favored element. An Aspect of Fire's weapon
        flickers with flame; an Aspect of Water's weapon shim-
        mers wetly and moves with eerie, fluid grace; the weapon
        of an Aspect of Air glitters with frost or crackles with
        lightning; an Aspect of Earth's weapon grows more massive
        and gleams like polished stone; the weapon of an
        Aspect of Wood character glows like polished wood or
        sunlight through leaves. For each mote of Essence the
        Exalted's player spends on this Charm, she may add one die
        to a single attack, but can no more than double her regular
        Melee Ability. If the character's specialties apply to the
        attack, she may double those as well.<br>
        Dragon-Blooded characters who know this Charm
        may employ it at will if they use a weapon that bears the
        appropriately colored jade in its hilt (black for water, red
        for fire and so on). With other weapons, the character must
        spend one turn executing a special weapon flourish and
        touching the weapon to the appropriate element. Air-
        attuned Dynasts seldom find this a problem; Dragon-Bloods
        attuned to Fire may suffer more inconvenience.<br>
        Cascade Charms:<br>
        • A Dragon-Blooded character with a higher Essence
        rating could conjure the elemental effect without the need
        for jade or touching the weapon to the appropriate element.<br>
        • An even more powerful Dynast could pull a weapon
        from the appropriate element. For instance, a Fire-attuned
        character could grab the flame from a candle and grow it
        into a sword; an Air-attuned character could conjure a
        weapon of glittering ice from a handful of snow.
        "

    elemental_thunderbolt_method[Elemental Thunderbolt<br>Method]
    click elemental_thunderbolt_method callback "
        Elemental Thunderbolt Method<br>
        <br>
        Cost: 1 mote per 2 dice of damage<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The character unleashes a bolt of elemental force
        extends from her hand — a blast of ice, or fire, a barbed
        javelin, a stroke of lightning or slashing shards of crystal. The
        character rolls Dexterity + Athletics or Archery (whichever
        she prefers) to hit. This attack has a range increment of 20
        yards x the character's permanent Essence, and does a base
        damage of 2 for every mote of Essence she spends activating
        it. The character cannot spend more motes activating this
        Charm than she has points of permanent Essence.
        "
