---
config:
  theme: dark
---
flowchart TD

    shaping_hand_style[Shaping Hand Style]
    click shaping_hand_style callback "
        Shaping Hand Style<br>
        <br>
        Cost: 2 motes<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Craft: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Terrestrial Exalted's basic and close connection
        with the things of the earth gives them great facility in
        manipulating the rude stuff that makes up the world. The
        most basic trick any Exalted craftswoman learns is that
        tools are, to a large extent, an illusion. It is the force of will
        that drives the act of creation, not the material items one
        uses to shape things.<br>
        This Charm bears that out. While the Charm is in
        effect, one of the character's hands may perform the
        function of any one normal tool. The character must
        decide what tool he wants to emulate when the Charm is
        activated. Whether it be a pick axe, hatchet or hammer,
        the Dragon-Blooded's bare hand fulfills the function quite
        nicely. The character takes no damage that a normal tool
        would not normally endure and can perform any normal
        function the tool is capable of - and can use her hand
        normally as well. The Exalt's hand does not take on the
        appearance of the tool in question.<br>
        The shaping hand only emulates the selected tool. If
        the character wants to switch functions, she has to activate
        the Charm again. Both hands can be enchanted separately
        using this Charm.
        "

    stone_carving_fingers_form[Stone-Carving Fingers Form]
    shaping_hand_style --> stone_carving_fingers_form
    click stone_carving_fingers_form callback "
        Stone-Carving Fingers Form<br>
        <br>
        Cost: 1 mote per cubic foot<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Shaping Hand Style<br>
        <br>
        This Charm is extremely popular with Earth-aspected
        Exalts because it forms the prerequisite for so many others.
        It enables the character to split stone with uncanny
        precision. Aside from its usefulness in siege — craft breach.
        ing walls and the like — the character can make all manner
        of useful items out of stone.<br>
        The character must spend at least a full minute care.
        fully striking at the stone. Most characters will use a hammer,
        pick of chisel, but a sword pommel or another rock will do
        just as well. Characters trained in martial arts might strikes
        with their bare hands. An the end of the minute the
        character strikes a final blow and the excess rock shatters,
        leaving behind the shape the character wanted.<br>
        Roll Wits + Craft. With a simple success, a character
        can quarry stone blocks ready for use in building or knock
        a doorway in a wall. With three successes, she can craft an
        obsidian vase, already hollowed out. With five successes,
        she can produce a portrait statue so realistic that a person
        might mistake it for the actual person, turned to stone.<br>
        The Essence cost of this Charm depends on the
        volume of the finished object: 1 mote of Essence per cubic
        foot of stone.
        "

    perfect_climbing_attitude[Perfect Climbing Attitude]
    stone_carving_fingers_form --> perfect_climbing_attitude
    click perfect_climbing_attitude callback "
        Perfect Climbing Attitude<br>
        <br>
        Cost: 1 mote<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Craft: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Stone-Carving Fingers Form<br>
        <br>
        The Dragon-Blooded of Earth include some superb
        mountaineers and rock-climbers, many as a result of this
        Charm. Not only may a character using this Charm cling
        to a rock face like a limpet, she leaves indentations in the
        rock that other people can use as hand- and footholds,
        making the climb easier for them. The Earth-aspected
        Exalt literally crafts a ladder out of a sheer rock surface as
        she climbs it.<br>
        The character can climb a sheer stone wall at a rate of
        10 feet per turn, 20 feet or more per turn up a rough cliff-face
        (or a surface where someone already made handholds
        in the rock). No Ability roll is needed. Those following the
        character up the cliff face are considered to have two
        automatic successes for any climbing check.<br>
        Surfaces that are worse than sheer, such as overhangs,
        call for multiple successes.
        "

    flaw_finding_examination[Flaw-Finding Examination]
    click flaw_finding_examination callback "
        Flaw-Finding Examination<br>
        <br>
        Cost: 1 mote for touch, 3 for sight<br>
        Duration: One minute<br>
        Type: Simple<br>
        Minimum Craft: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        By simply studying any crafted or created item, object
        or structure, a Dragon-Blooded using this Charm may
        determine that item's weakest point. This knowledge can
        be used to locate and eliminate flaws – or exploited to
        destroy the object.<br>
        To use this Charm, the character must study the
        object in question for at least a full minute. If the Exalt is
        able to handle or touch the thing being studied, the Charm
        costs only a single mote. Studying an object from a distance
        costs 3 motes.<br>
        Once the flaw has been determined, the character
        has two options. If the Dynast wants to try and eliminate
        the flaw, roll her Intelligence + Craft score and
        spend a point of Willpower. If the roll succeeds, the
        object is repaired - this Charm can effect the most
        serious repairs without tools, though something badly
        broken may have many flaws.<br>
        If the character wants to damage the thing in ques-
        tion, the Flaw-Finding Examination is much simpler. The
        next successful physical attack the character makes on the
        target does double normal damage. If the Exalt is targeting
        something such as armor or a weapon, treat it as doubling
        the extra successes of a disarming attempt. If the disarming
        attempt succeeds, the weapon or armor is destroyed.
        "

    charm_of_lesser_unmaking[Charm of Lesser<br>Unmaking]
    flaw_finding_examination --> charm_of_lesser_unmaking
    click charm_of_lesser_unmaking callback "
        Charm of Lesser Unmaking<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Craft: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Flaw-Finding Examination<br>
        <br>
        The Charm of Lesser Unmaking allows a Dynast to
        disassemble an object or structure without actually damaging
        any of its components. An item affected by this Charm
        is broken down into its component pieces.<br>
        For instance, if a Dragon-Blood was to use the
        Charm of Lesser Unmaking on a heavy wooden door
        bound in steel bands, the end result would be a stack of
        timbers, some hammered steel bands and a small pile of
        rivets. Items disassembled in this manner are rendered
        useless until put back together. Enchanted items are
        neutralized until reconstructed, but the Charm does not
        permanently disrupt such enchantments.<br>
        When the Charm of Lesser Unmaking is invoked, the
        character's player makes an Essence + Craft roll. The
        difficulty for this roll is 1 for simply constructed items
        (crudely made stone hatchets, huts lashed together with
        vines), 3 for sturdily or competently made items (a well-
        constructed sword, iron chains, the aforementioned door)
        and 5 for intricately or masterfully made items (a finely
        crafted piece of jewelry, a finely forged weapon). If the item
        in question is enchanted in any way, add i to the difficulty,
        meaning most enchanted items are difficulty 6 to disassemble.
        The maximum volume that a Dynast can affect.
        with the Charm of Lesser Unmaking is equal to her
        Essence in cubic yards.<br>
        Unmaking will hot work on any item that is made in
        one piece (i.e., a vase, stone carving or the like). However,
        it will undo knots and reduce chains to their component
        links. Lesser unmaking is a somewhat time-consuming
        process. The Exalt must also remain in contact with the
        item for a number of turns equal to the unmaking difficulty,
        and it cannot be done as a combat maneuver.
        "

    charm_of_greater_unmaking[Charm of Greater<br>Unmaking]
    charm_of_lesser_unmaking --> charm_of_greater_unmaking
    click charm_of_greater_unmaking callback "
        Charm of Greater Unmaking<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Special<br>
        Minimum Craft: 5<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: Charm of Lesser Unmaking<br>
        <br>
        This Charm functions much like Lesser Unmaking
        but with much more dramatic effects. Rather than just
        being taken apart, an item affected by Greater Unmaking
        is actually reduced back to its raw materials. Sword blades
        melt into hunks of raw iron. Timbers turn to freshly cut
        logs. Glittering gemstones return to their uncut state. Fine
        pottery melts to clay.<br>
        When the Charm is used, roll the character's Essence
        + Craft. This roll is difficulty 1 for normal items constructed
        through standard methods, but difficulty 3 for
        exceptionally crafted or constructed things and 5 for items
        forged from the Five Magical Materials. The Exalt must
        also remain in contact with the item for a number of turns
        equal to the difficulty. The maximum volume that a
        Dynast can affect with the Charm of Greater Unmaking is
        equal to her Essence in cubic yards. This Charm is only
        effective against items made of materials in some way
        derived from the earth.<br>
        Items that are unmade are completely destroyed,
        reduced to their component materials. Whatever is un-
        made must be remade from scratch. The raw materials
        retain any inherent value, of course.
        "
