---
config:
  theme: dark
---
flowchart TD

    strength_of_stone_technique[Strength of Stone<br>Technique]
    click strength_of_stone_technique callback "
        Strength of stone Technique<br>
        <br>
        Cost: 2 motes per person<br>
        Duration: The Dragon-Blooded's Essence in scenes<br>
        Type: Reflexive<br>
        Minimum Resistance: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        One of the most notable traits of the element of Earth
        is its strength and resistance to damage. Through this
        Charm, a Dragon-Blooded can take on some of the strength
        and hardness of stone and share it with other people.
        After a short meditation while holding and concentrating
        upon the Essence within a pebble, the character
        becomes stronger and tougher, gaining one dot of both
        Strength and Stamina for the next five minutes. If the
        Dragon-Blooded character wants to include other people
        Dragon-Blooded character wants to include other people
        in the Charm, the recipients must all hold hands in a circle
        with a pebble between each pair of palms. An individual
        cannot benefit from multiple simultaneous uses of this
        Charm, even if different Dragon-Blooded invoke it.<br>
        Cascade Charms:<br>
        • An obvious extension grants actual dots of armor by
        making the character's skin as hard as stone while retain-
        ing the flexibility of life.<br>
        • A more advanced variation lets a Dragon-Blooded
        character become as invulnerable as a stone statue. Unfortunately,
        the character also becomes stiff and slow, cutting
        all Dexterity-based dice pools in half for the Charm's
        duration.
        "


