---
config:
  theme: dark
---
flowchart TD

    stone_carving_fingers_form[Stone-Carving Fingers Form]
    click stone_carving_fingers_form callback "
        Stone-Carving Fingers Form<br>
        <br>
        Cost: Varies<br>
        Duration: 1 minute<br>
        Type: Simple<br>
        Minimum Craft: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm is extremely popular with the Aspects of
        Earth because it forms the prerequisite for so many others.
        It enables the character to split stone with uncanny
        precision. Aside from the usefulness in siegecraft — breach-
        ing walls and the like - the character can make all manner
        of useful items out of stone.<br>
        The character must spend at least a full minute
        carefully striking at the stone. Most characters will use a
        hammer, pick or chisel, but a sword pommel or another
        rock will do just as well. Characters trained at martial arts
        might strike with their bare hands. At the end of the
        minute, the character strikes a final blow — and the excess
        rock shatters, leaving the shape the character wanted.<br>
        The player rolls Wits + Craft. For a simple success, the
        character can quarry stone blocks ready for use in building or
        knock a doorway in a wall. With three successes, he can craft
        an obsidian vase, already hollowed out. For five successes, he
        can produce a portrait statue so realistic that a person might
        mistake it for the actual person, turned to stone.
        The Essence cost of this Charm depends on the
        volume of the finished object: one mote of Essence per
        cubic foot of stone.<br>
        Cascade Charms:<br>
        • The Dragon-Blooded have developed variations
        where a character picks up a rock, bashes it against something
        hard, and the rock shapes itself into some specific
        useful item. The most common variations produce weapons.
        A character who knows this Charm is seldom disarmed
        for long. The stone weapon remains as strong as a metal
        weapon for a scene, but can break afterward.<br>
        • A cascade Charm much prized by martial artists
        enables a Dynast to shatter large masses of stone with a
        single blow. This is extremely useful in sieges.<br>
        • One variation enables a character to merge bits of
        rock into solid stone. It works just as well on glass, brick or
        pottery. A character could use the Charm to seal doors
        shut with bars of solid rock.<br>
        • Another variation (not requiring Stone-Carving
        Fingers Form as a prerequisite because it's so simple) lets a
        character break an enemy's stone or metal weapon with a
        single well-placed blow. These variations use Brawling,
        Melee or Martial Arts, depending on which way the
        character prefers to fight. (Each Ability serves as the basis
        for a separate Charm.)<br>
        • Great masters among the Aspects of Earth hew
        entire palaces and temples from rock using advanced
        versions of this Charm.
        "


