---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph air_awareness[Air Awareness Charms]
        direction TB

        voice_on_the_wind_technique[Voice on the<br>Wind Technique]
        click voice_on_the_wind_technique callback "
        Voice on the Wind Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: 1 minute<br>
        Type: Simple<br>
        Minimum Awareness: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Speech requires breath, the very air of life. Some
        Dynasts of Air can extend their senses through the air and
        so listen to what people say far away. The farther away a
        character wants to eavesdrop, the more difficult the Charm
        becomes: For a simple success, an Aspect of Air can clearly
        hear normal speech from a hundred feet away. The character
        also gets a general sense of the target's direction (assuming
        she doesn't know already). For each additional point of
        difficulty, that range increases by a factor of ten. For each
        additional dot of Essence the character has, the base distance
        increases by a factor of ten. A powerful Air-attuned lord can
        - with great difficulty — hear voices throughout the world.
        (The Empress certainly seemed to have this knack.)<br>
        This Charms comes with limitations. The character
        must specify a single person he wants to spy upon: He
        cannot, for instance, declare that he will &quot;listen for people
        plotting against me.&quot; At most, he can make a list of
        suspected enemies and eavesdrop on them one by one. The
        character cannot hear anything spoken in an airtight
        chamber. Many of the powerful Dynasts build such cham-
        bers for their privy councils, specifically to defeat this
        Charm. Finally, listening to a person from so far away
        demands total concentration: The character cannot per-
        form any other action while hearing voices on the wind.
        Cascade Charms:<br>
        • A more powerful Charm could have a longer dura-
        tion, allowing a character to listen in on another character
        for a full hour, or even longer — but still only one person
        at a time.<br>
        • Alternatively, the character can listen to any
        conversation or other noises at a specific location far away.
        In this case, the character must objectively define a precise
        spot (such as &quot;the kitchen in Lord Peleps' villa&quot; or &quot;the
        interior of that carriage down the street&quot;).
        "

    end

