---
config:
  theme: dark
---
flowchart TD

    leaping_flame_attitude[Leaping Flame Attitude]
    click leaping_flame_attitude callback "
        Leaping Flame Attitude<br>
        <br>
        Cost: 5 motes<br>
        Duration: The Dragon-Blooded's Essence in scenes<br>
        Type: Simple<br>
        Minimum Dodge: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Fire is the most mobile of the elements. The Dragon-Blooded
        who learn its mysteries can infuse the Essence of
        Fire into themselves or a single target, granting them the
        agility of a leaping flame. The player rolls Wits + Dodge.
        The target gains one dot of the Dodge Ability for every
        success rolled by the Dragon-Blooded character, to a
        maximum of the target's own Dodge rating, for the duration
        of the Charm. The recipient also gains one extra dot
        in Athletics (no more), but only for purposes of jumping
        and keeping his balance. The target cannot more than
        double his Dodge ability, even if multiple Dragon-Blooded
        invoke this Charm on him.<br>
        Cascade Charms:<br>
        • An improved Charm could increase the recipient's
        movement rate, allowing the character to move his full
        distance (walking, running or sprinting) while still per-
        forming other actions in a turn.<br>
        • A considerably more powerful Dynast might learn
        to perform an Essence-fueled dodge so agile that she
        becomes impossible to hit by any hand-to-hand attack that
        is not itself reinforced with Essence.
        "


