---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph water_socialize[Water Socialize Charms]
        direction TB

        loyalty_eroding_method[Loyalty Eroding Method]
        click loyalty_eroding_method callback "
        Loyalty Eroding Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: Varies<br>
        Type: Simple<br>
        Minimum Socialize: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Fire destroys quickly; water erodes slowly, subtly, but
        no less completely. Those who study the metaphysical
        aspects of the elements declare Water the most sinister and
        deadly of the elements. Masters of the Essence of Water
        can stir currents of doubt in the minds of others, eroding
        trust in favor of treachery.<br>
        This Charm requires nothing more than a few minutes
        in which to talk to a person. The Storyteller sets the
        difficulty, based on the target's degree of devotion and
        faith in another person, institution, belief or cause. The
        Dragon-Blooded's player rolls Manipulation + Socialize. If
        he rolls enough successes, the target person becomes
        suspicious, cynical and hostile enough to betray whoever
        or whatever the Dynast wanted. The treacherous dislike
        persists for at least an hour after the Charm's use; if the
        Dynast received more successes than the minimum necessary,
        the hatred can last for days.<br>
        A Dynast who uses the Loyalty-Eroding Method on
        several well-chosen targets can turn an entire town against
        a victim. Rousing suspicion and hatred on such a large
        scale often runs out of control, though. After the affected
        people banish or lynch the target of their ire, the Storyteller
        secretly rolls one die for every person in the community
        affected by the Loyalty-Eroding Method. For each success
        rolled, the community attacks one more scapegoat as old
        enmities flare — and the Dynast has no control over who
        the people choose.<br>
        Cascade Charms:<br>
        • A more subtle and advanced Charm instills a seed
        of betrayal that grows and blossoms later instead of right
        away. Such a delayed-effect Charm might have a time
        limit, or prime a person for treachery when a certain
        condition is met or signal given.
        "

    end
