---
config:
  theme: dark
---
flowchart TD

    fire_in_the_belly_attitude[Fire in the Belly Attitude]
    click fire_in_the_belly_attitude callback "
        Fire in the Belly Attitude<br>
        <br>
        Cost: 2 motes per person<br>
        Duration: The Dragon-Blooded's Essence in scenes<br>
        Type: Simple<br>
        Minimum Presence: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        People often describe strong passions as flames, and
        the Aspects of Fire take this metaphor literally. Through
        this Charm, a Dynast can whip up the flames of courage
        and anger, making a person more brave and aggressive.
        The character must say something fierce and rousing to his
        troops, and his player makes a Charisma + Presence roll. If
        the Charm succeeds, each recipient gains one dot of both
        Valor and Willpower for the next five minutes, up to the
        maximum possible. Alas, the Charm does not work on the
        character himself— and if the Dragon-Blood cuts and runs
        or otherwise shows cowardice, the Charm's effects end at
        once. An individual cannot benefit from multiple simultaneous
        uses of this Charm, even if different
        Dragon-Blooded invoke it.<br>
        Cascade Charms:<br>
        "
