---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph air_melee[Air Melee Charms]
        direction TB

        one_mind_technique[One Mind Technique]
        click one_mind_technique callback "
        One Mind Technique<br>
        <br>
        Cost: 2 motes per person<br>
        Duration: 5 minutes<br>
        Type: Simple<br>
        Minimum Melee: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Just as speech is a form of modulated wind, so thought
        is silent speech. A Dynast of Air can enable a group of
        armsmen to know each other's thoughts, at least to a
        limited degree. What one soldier knows, the others know.
        As a result, a group that fights with one mind displays
        uncanny coordination. They trade opponents without a
        hitch; one fighter parries a blow aimed at another; an
        enemy seen by one cannot hide from any.<br>
        The player rolls Charisma + Melee. For each success
        that the Dragon-Blooded character receives, the recipients
        gain one dot each of Wits, Perception and Melee, up
        the Dragon-Blooded character's own Melee rating. The
        character can link as many people with one mind as she has
        dots of Essence. Typically, this includes the character
        herself, but this is not strictly necessary, Dynasts typically
        use this Charm to magnify the fighting prowess of their
        bodyguards or minions.<br>
        Characters linked by this Charm must have trained
        together for at least a week. They must spend a turn on a
        shared breathing exercise and battle cry to initiate the
        link. The characters must stay within 50 feet of each other.
        If any character moves beyond that range, the link breaks
        and the Charm ends. No character can benefit from
        multiple uses of the One Mind Technique at the same
        time, even if different Dragon-Blooded activate the Charm.<br>
        Cascade Charms:<br>
        • Instead of Melee, an Aspect of Air can leam a
        variation that employs Brawling, Martial Arts or Archery.<br>
        • Fighters of extraordinary skill might learn how to
        link two characters per dot of Essence, or even more.<br>
        "

    end

