---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph earth_presence[Earth Presence Charms]
        direction TB

        entombed_mind_technique[Entombed Mind Technique]
        click entombed_mind_technique callback "
        Entombed Mind Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: 5 minutes<br>
        Type: Simple<br>
        Minimum Presence: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Earth is the most static and quiescent of the elements.
        This Charm enables a Dragon-Blooded character to infuse
        some of that somnolent stasis into another person's mind,
        putting them to sleep. Some Dynasts work this Charm
        through speaking in a low, droning voice; others prefer to use
        a glittering gemstone, such as the jewel in a ring, to fix their
        victim's attention and convey the flow of Essence. One can
        only bury someone's mind if one can keep them sitting still
        for five minutes, so this Charm calls for a fair bit of guile.
        The player rolls Manipulation + Presence, with a
        difficulty equal to the target's Essence. A simple success
        causes the target to sleep for an hour, and each extra
        success adds one hour to the total. During that hour, noise,
        light and movement do not awaken the victim. You could
        send the entire Red-Piss Legion past with cymbals and he
        wouldn't wake up. At the end of this period, the victim
        passes to normal slumber.
        While in the grip of magic sleep, the victim dreams
        strange, still dreams of the caves beneath the earth and the
        mysteries within them. Once in a while, someone wakes up
        afterward knowing where to dig a well that never goes dry,
        or the location of an ore deposit.<br>
        Cascade Charms:<br>
        • More powerful versions of this charm can put a victim
        to sleep for longer periods. Old tales tell of great lords of the
        Silver Age whose bound enemies still slumber in hidden
        locations, or maidens cursed to sleep for a hundred years.<br>
        • A still more powerful variation petrifies the victim's
        body as well as her mind. Only occult means can rouse such
        a stone sleeper.
        "

    end
