---
config:
  theme: dark
---
flowchart TD

    loquacious_courtier_technique[Loquacious Courtier Technique]
    click loquacious_courtier_technique callback "
        Loquacious Courtier Technique<br>
        <br>
        Cost: 1 mote per two dice<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Socialize: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The character's stories and idle chitchat become more
        entertaining to those around him. Her every turn of phrase
        becomes wittier, her every comment more topical. Mechanically,
        this Charm allows the character to add two dice to her
        Socialize Ability for the scene for every mote she spends; she
        can add no more dice than she has dots in Socialize.
        "

    sweeten_the_tap_method[Sweeten the Tap Method]
    loquacious_courtier_technique --> sweeten_the_tap_method
    click sweeten_the_tap_method callback "
        Sweeten the Tap Method<br>
        <br>
        Cost: 2 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Loquacious Courtier Technique<br>
        <br>
        Nearly any gathering of Terrestrial Exalted involves
        the consumption of alcohol, often in great quantity. A
        Dragon-Blood can use the Sweeten-the-Tap Method while
        near a quantity of alcohol - he expends a minimum of
        Essence, and the drink noticeably improves in quality,
        strength and taste. This will usually improve the general
        mood of the room, reducing by 1 the difficulty of all
        Socialize rolls for anyone present and imbibing for the rest
        of the evening. However, should anyone botch a Socialize
        roll during the rest of the scene, an overreaction is more
        likely to take place — possibly tempers will fray, or characters
        may make ill-advised seduction attempts. This side
        effect has no particular game mechanic; the Storyteller's
        judgment should be the guide.
        "

    wary_yellow_dog_attitude[Wary Yellow Dog Attitude]
    sweeten_the_tap_method --> wary_yellow_dog_attitude
    click wary_yellow_dog_attitude callback "
        Wary Yellow Dog Attitude<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Sweeten-the-Tap Method<br>
        <br>
        When the Dragon-Blooded who knows this Charm is
        caught in a social situation that unexpectedly turns violent,
        she can quickly focus. During an unexpected combat - that
        is to say, not a military battle or one that comes at the end of
        a search-and-destroy mission for some hinterlands monster
        — the character can activate this Charm to add 3 to her
        Initiative roll. This Charm can only be used during the first
        three turns of an unexpected combat.
        "

    seizing_the_tongue_technique[Seizing the Tongue Technique]
    loquacious_courtier_technique --> seizing_the_tongue_technique
    click seizing_the_tongue_technique callback "
        Seizing the Tongue Technique<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Loquacious Courtier Technique<br>
        <br>
        In a social situation, a quick-witted Dragon-Blooded
        can often nimbly step out of a verbal pit and reestablish the
        grounds of a conversation without giving offense to another
        party. By expending the necessary Essence, the
        Dragon-Blood's player can immediately reroll any Socialize
        roll. She must accept the second roll even if it is worse
        than the first, and she cannot spend additional Essence to
        make subsequent rerolls after the first, Additionally, if
        Seizing the Tongue Technique is part of any Combo,
        then Essence must be spent to reactivate all the other
        Charms in that Combo when the reroll takes place, if those
        Charms have separate dice rolls associated with them, they
        are not rerolled
        "

    brother_against_brother_insinuation[Brother-Against-Brother<br>Insinuation]
    seizing_the_tongue_technique --> brother_against_brother_insinuation
    click brother_against_brother_insinuation callback "
        Brother-Against-Brother Insinuation<br>
        <br>
        Cost: 4 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Seizing-the-Tongue Technique<br>
        <br>
        The personal connections between arrogant and aggressive
        beings such as the Dragon-Blooded are often
        tenuous; it barely takes a spark to destroy the connection
        between two such individuals for a short while.<br>
        To activate this Charm, both the target individual and the
        character she is to be set against must be present. The Exalt
        spends the necessary motes of Essence and makes a simple
        comment to one individual about the other - &quot;I hear he's got
        plans that don't include you&quot; or the like works well enough.
        That is sufficient to weaken the bonds of friendship or love
        between the two characters for the remainder of the scene. The
        characters' reaction to this conflict is up to the Storyteller, of
        course; it may be both parties stomping off to cool their heads
        or engaging in a vicious argument or even coming to blows.<br>
        Neither party immediately remembers the character who
        started the disagreement between them, though other parties
        present may notice the character's activity. When the scene is
        over, cooler heads prevail, and both characters remember the
        strength of their friendship. Unless something horrifically bad
        happened between the two (again, a matter for the Storyteller's
        discretion), they will return to their previous relationship.<br>
        When the Charm ends, the character who was the
        original target of the Charm may remember the Exalted's
        well-timed turn of phrase (requires a successful Intelligence
        + Socialize roll with a difficulty equal to the Manipulation
        of the Exalt who used this Charm). This Charm is well-
        known in the Realm, and those who use it in social situations
        can be brought up on charges or disgraced.<br>
        This Charm does not work if either target character has
        an Essence higher than that of the Exalt using the Charm.
        "

    warm_faced_seduction_style[Warm-Faced Seduction Style]
    loquacious_courtier_technique --> warm_faced_seduction_style
    click warm_faced_seduction_style callback "
        Warm-Faced Seduction Style<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Loquacious Courtier Technique<br>
        <br>
        The Exalted coaxes the seductive aura of a flickering
        candle in the dark to coalesce around her face, and she briefly
        becomes far more attractive to a character that she is attempting
        to seduce. The Dragon-Blood who uses this Charm
        momentarily increases her Socialize dice pool by, up to five
        dice, solely for the purpose of seducing the Charm's target.
        Warm-Faced Seduction Style cannot increase the character's
        Socialize Trait no more than double its base value.
        "

    friend_to_all_nations_attitude[Friend-to-All-Nations<br>Attitude]
    warm_faced_seduction_style --> friend_to_all_nations_attitude
    click friend_to_all_nations_attitude callback "
        Friend-to-All-Nations Attitude<br>
        <br>
        Cost: 2 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Socialize: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Warm-Faced Seduction Style<br>
        <br>
        The Dragon-Blooded with Friend-to-All-Nations
        Attitude finds herself to be equally at home on the Blessed
        Isle, in the Scavenger Lands or even in the barbaric
        reaches of the Wyld. While this Charm is active, the Exalt
        suffers no penalties to her Socialize Ability for being in a
        strange land, so long as she speaks the local tongue. If she
        does not, she may suffer a penalty at the Storyteller's
        discretion, but even so, that penalty will be relatively
        minor, as she instinctively knows all of the mores and basic
        manners of the culture into which she immerses herself.
        Strangely, this Charm is somewhat less effective in
        melting-pot cultures such as Nexus, as the character picks
        up on cultural standards from several groups simultaneously.
        Thankfully, people in such melting pots are, on
        average, more tolerant of cultural differences, so the net
        effect of the Charm is the same.
        "

    smoothing_over_the_past_technique[Smoothing-Over-the-Past<br>Technique]
    warm_faced_seduction_style --> smoothing_over_the_past_technique
    click smoothing_over_the_past_technique callback "
        Smoothing-Over-the-Past Technique<br>
        <br>
        Cost: 3 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Reflexive<br>
        Minimum Socialize: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Warm-Faced Seduction Style<br>
        <br>
        This Charm enables the Dragon-Blood who uses it to
        cause a target's mind to temporarily skip over a past event
        involving the Exalted that would reflect poorly on the
        current discussion. That is to say, she makes the target
        forget about a single event in the past — an event that
        must have included the Exalt herself — just for the current
        scene. She can cause the target to forget about multiple
        events if she wishes, but that requires multiple uses of this
        Charm, just as with any other reflexive Charm.<br>
        When the scene is over, the target will be aware of what
        has happened to her, and she is likely to be quite unhappy
        about any bargains reached while she was not quite herself.
        That means that future uses of this Charm on the same:
        individual will require the Exalt to first use the Charm to
        smooth over the target's memories of having been previously
        fooled through the use of Smoothing Over-the-Past
        Technique. Covering up for careless use of this Charm can
        quickly become impossibly expensive in Essence.<br>
        This Charm does not work on characters whose
        Essence Traits are higher than that of the character
        using the Charm.
        "
