---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph earth_athletics[Earth Athletics Charms]
        direction TB

        perfect_climbing_attitude[Perfect Climbing Attitude]
        click perfect_climbing_attitude callback "
        Perfect Climbing Attitude<br>
        <br>
        Cost: 1 mote<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Athletics: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Dragon-Blooded of Earth include some superb
        mountaineers and rock-climbers, all because of this Charm.
        Not only does the character cling to a rock face like a
        limpet, she leaves indentations in the rock that other
        people can use as hand- and footholds, making the climb
        easier for them. The character can climb a sheer stone wall
        at a rate of 10 feet per turn, or 20 feet or more per turn up
        a rough cliff face (or a surface where someone already made
        handholds in the rock). Surfaces that are worse than sheer,
        such as overhangs, require multiple successes.<br>
        Cascade Charms:<br>
        • More skilled Dragon-Blooded can find or make
        projections sufficient to support a hammock. Sleeping 50
        feet up a cliff face may not be comfortable, but with this
        Charm it sure is safe.<br>
        • More powerful Dynasts of Earth can leave a virtual
        ladder or stairway in the rock, making ascent or descent
        quite safe and easy for anyone else.
        "

    end

