---
config:
  theme: dark
---
flowchart TD

    bounding_main_technique[Bounding Main Technique]
    click bounding_main_technique callback "
        Bounding Main Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: 1 hour<br>
        Type: Supplemental<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Dynasts attuned to Water can become some of the
        world's greatest sailors. The Charm makes every sailing
        task just a little bit easier: The wind doesn't die or shift at
        awkward moments, there always seems to be a current in
        the desirable direction, and crewmembers do their jobs
        with skill and efficiency.<br>
        In game terms, every two successes rolled with this
        Charm (rounded up) cancel out one difficulty penalty
        from a Sail-based feat. Thus, if the Storyteller rules that
        threading the narrow, stormy Straits of Hell normally
        would be difficulty 3, one or two successes with this Charm
        would reduce the difficulty to 2, and three or four successes
        would reduce the task to normal difficulty. The player
        must still make Ability rolls and gain at least a simple
        success for tasks, but does not suffer penalties for adverse
        conditions.<br>
        Multiple characters cannot add together successes
        rolled for this Charm. Only the roll with the greatest
        number of successes counts. For instance, if two characters
        both use Bounding Main Technique and one rolls two
        successes while the other rolls three, only the second
        character's Charm has any effect.<br>
        Cascade Charms:<br>
        • A more powerful version of this Charm extends
        over multiple ships, at least if they stay fairly close together.<br>
        • A more skilled and powerful sailor could reverse this
        Charm and use it against an enemy, adding difficulty
        penalties for any sailing task. On the high sea, this merely
        hinders a ship— it doesn't move as quickly, the crew seems
        clumsy and stupid, and so on. Moderately risky tasks (such
        as sailing a narrow passage between rocky shoals) can
        become incredibly dangerous.
        "

    hurricane_predicting_glance[Hurricane-Predicting<br>Glance]
    click hurricane_predicting_glance callback "
        Hurricane-Predicting Glance<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        With a look at the sky, the Exalted can predict the
        weather for the next day or so; his empathy with the
        currents of the ocean and air give him real prescience
        regarding the weather. The Charm will fail if the local
        weather is changing in response to a magical event or
        sorcery; this Charm only describes to the character
        what the natural weather will be if nothing unusual
        takes place. Perceptive Dragon-Blooded can sometimes
        use this Charm to predict events other than the
        weather: If, for instance, Admiral Potan's fleet is pre-
        paring to sail on a rebellious prefecture as soon as a
        storm breaks, the user of this Charm can predict
        exactly when they will set sail. And impossibly heavy
        clouds appearing out of clear blue skies might be a
        harbinger of an impending volcanic eruption. This
        Charm only works when the character is on the water;
        it fails when the Exalted's feet are on land.
        "

    storm_outrunning_technique[Storm-Outrunning<br>Technique]
    hurricane_predicting_glance --> storm_outrunning_technique
    click storm_outrunning_technique callback "
        Storm-Outrunning Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Hurricane-Predicting Glance<br>
        <br>
        When time is of the essence and getting a ship into
        safe harbor is more important than the crew's rest and
        safety, a captain or pilot with Storm-Outrunning Technique
        is essential to survival and success. This Charm
        allows a ship's officer to double that ship's rate of
        movement for the current scene. This may enable a
        small ship to beat an enemy fleet to a friendly port,
        giving the city some warning; it may let a ship beat a
        storm to safety; or it may let a crew of merchants beat
        a rival to a choice port. To activate the Charm, the
        Exalt need only spend the necessary Essence. The
        greatly increased speed may require one or more Sail
        rolls, especially if the ship cruises through hazardous
        waters at double normal velocity. Also, note that if
        this Charm is used from the deck of a becalmed sailing
        ship it will have no effect, as a speed of zero, when
        doubled, remains zero.
        "

    fine_passage_negotiating_style[Fine Passage-Negotiating<br>Style]
    hurricane_predicting_glance --> fine_passage_negotiating_style
    click fine_passage_negotiating_style callback "
        Fine Passage-Negotiating Style<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Reflexive<br>
        Minimum Sail: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Hurricane Predicting Glance<br>
        <br>
        The finest captains and pilots can thread their ships
        through the most dangerous patches of sea, avoiding
        submerged hazards with flair and panache. This Charm is
        the source of more than one pilot's reputation. With it, an
        Exalt gains an instinctive knowledge of any submerged
        hazards within five miles of the ship's current location, as
        well as the prevailing current, danger spots and safe channels
        in the same radius. The net effect of this knowledge is
        that the pilot's Sail dice pool improves by three dice for the
        remainder of the scene for the purpose of avoiding hazards.
        This Charm does not directly protect the ship from such
        hazards: If the pilot makes a bad mistake, the hull might
        still be rent asunder. It also does not give its user any special
        awareness of the activities of other characters: It cannot
        point out an ambush in a narrow passage or the impending
        arrival of an enemy vessel.
        "

    sturdy_bulkhead_concentration[Sturdy Bulkhead<br>Concentration]
    fine_passage_negotiating_style --> sturdy_bulkhead_concentration
    click sturdy_bulkhead_concentration callback "
        Sturdy Bulkhead Concentration<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Fine Passage Negotiating Style<br>
        <br>
        A Charm favored by Wood-aspected sailors, Sturdy
        Bulkhead Concentration enhances the strength of a ship's
        hull without making it heavier. When this Charm is
        active, the hull gains three additional health levels and 2
        additional soak. The benefit only remains as long as the
        Exalted who activated the Charm remains aboard the
        vessel. To activate the Charm, the character needs only to
        spend the necessary Essence while aboard the ship.
        "

    pirate_masquerading_method[Pirate Masquerading<br>Method]
    fine_passage_negotiating_style --> pirate_masquerading_method
    click pirate_masquerading_method callback "
        Pirate Masquerading Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Sail: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Fine Passage Negotiating Style<br>
        <br>
        Whenever a ship under the command of a Dragon-Blooded
        with this Charm comes into contact with hostile ships
        of any stripe, it is temporarily camouflaged as a ship of that
        allegiance: The ship appears to be a merchantman to those
        aboard merchantmen; it looks as a pirate ship does to pirates;
        and so on. The Charm is largely a visual illusion — the vessel's
        flag changes its appearance, and the crew appears, from a
        distance, to be the appropriate sort of crew for a ship of its type.
        The Charm does not change the line of the ship itself, so one
        cannot, for instance, hide an imperial dreadnought among
        fishing smacks and expect to go unnoticed. The Charm also
        fails should any viewer set foot upon the ship; visitors and
        raiders see the ship as it really is, once they are aboard it.
        "
