---
config:
  theme: dark
---
flowchart TD

    bounding_main_technique[Bounding Main Technique]
    click bounding_main_technique callback "
        Bounding Main Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: 1 hour<br>
        Type: Supplemental<br>
        Minimum Sail: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Dynasts attuned to Water can become some of the
        world's greatest sailors. The Charm makes every sailing
        task just a little bit easier: The wind doesn't die or shift at
        awkward moments, there always seems to be a current in
        the desirable direction, and crewmembers do their jobs
        with skill and efficiency.<br>
        In game terms, every two successes rolled with this
        Charm (rounded up) cancel out one difficulty penalty
        from a Sail-based feat. Thus, if the Storyteller rules that
        threading the narrow, stormy Straits of Hell normally
        would be difficulty 3, one or two successes with this Charm
        would reduce the difficulty to 2, and three or four successes
        would reduce the task to normal difficulty. The player
        must still make Ability rolls and gain at least a simple
        success for tasks, but does not suffer penalties for adverse
        conditions.<br>
        Multiple characters cannot add together successes
        rolled for this Charm. Only the roll with the greatest
        number of successes counts. For instance, if two characters
        both use Bounding Main Technique and one rolls two
        successes while the other rolls three, only the second
        character's Charm has any effect.<br>
        Cascade Charms:<br>
        • A more powerful version of this Charm extends
        over multiple ships, at least if they stay fairly close together.<br>
        • A more skilled and powerful sailor could reverse this
        Charm and use it against an enemy, adding difficulty
        penalties for any sailing task. On the high sea, this merely
        hinders a ship— it doesn't move as quickly, the crew seems
        clumsy and stupid, and so on. Moderately risky tasks (such
        as sailing a narrow passage between rocky shoals) can
        become incredibly dangerous.
        "


