---
config:
  theme: dark
---
flowchart TD

    observer_awareness_method[Observer Awareness Method]
    click observer_awareness_method callback "
        Observer Awareness Method<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Larceny: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This simple Charm allows a Dragon-Blood to know
        if he is being observed. It was developed in the days before
        the Realm proper, when it was conceivable that one of
        the noble Terrestrial Exalted could act in a criminal
        capacity. In these dangerous days, the Charm sees use
        among those Exalted who might act as spies or who wish
        to speak to a confidante unobserved. Simply spend the
        necessary Essence and roll Perception + Larceny; a single
        success tells the Exalted whether he is being observed.
        Each additional success points out the location of an
        observer, starting with the closest.
        "

    trackless_walk_style[Trackless Walk Style]
    observer_awareness_method --> trackless_walk_style
    click trackless_walk_style callback "
        Trackless Walk Style<br>
        <br>
        Cost: 2 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Larceny: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Observer Awareness Method<br>
        <br>
        The greatest spies and thieves of the Realm know that
        the best way to avoid detection in their efforts is to leave as
        little evidence as possible of their passing. However, those
        spies and thieves know full well that the most talented
        magistrates and house investigators can learn a great deal
        from a trace as innocuous as a single hair. By activating this
        Charm as he enters a location, a Dragon-Blood prevents
        himself from leaving inadvertent evidence. This Charm
        does not prevent the character from being observed; it
        merely prevents him from leaving behind clues to his
        identity, such as footprints. Also, this Charm does not
        prevent the character from deliberately leaving behind
        evidence of his presence (if, for instance, he is a romantic
        master thief and always leaves a rose at the scene of a crime,
        this Charm does not prevent him from doing so). Characters
        using this Charm cannot be tracked except by supernatural
        means, but the Charm's short duration means that it is an
        expensive way to conceal ones passage for a long while.
        "

    ears_of_the_snow_owl[Ears of the Snow Owl]
    observer_awareness_method --> ears_of_the_snow_owl
    click ears_of_the_snow_owl callback "
        Ears of the Snow Owl<br>
        <br>
        Cost:
        Duration:
        Type:
        Minimum Larceny:
        Minimum Essence:
        Prerequisite Charms:
        1 mote
        One minute
        Simple
        4
        2
        Observer Awareness
        Method
        This Charm, quite useful when sneaking about in
        places one shouldn't be, allows a character to hear conversations
        and movement in other rooms as clearly as if the
        walls between him and those spaces weren't there. By
        spending the necessary Essence in conjunction with a
        listen-oriented Perception roll, the player can eliminate
        any penalties to that roll that might come as a function of
        obstacles between his character and the thing he's listening
        to. The Charm does not eliminate penalties due to
        distance, just physical obstructions.
        "

    window_in_the_door_technique[Window-in-the-Door Technique]
    ears_of_the_snow_owl --> window_in_the_door_technique
    click window_in_the_door_technique callback "
        Window-in-the-Door Technique<br>
        <br>
        Cost: 2 motes<br>
        Duration: One turn<br>
        Type: Simple<br>
        Minimum Larceny: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Ears of the Snowy Owl<br>
        <br>
        Many a time has come when a mortal thief or spy has
        wished for the ability to see what lies beyond a doorway or
        inside a chest without risking the opening of a latch or lock.
        Spies among the Terrestrial Exalted do not merely wish for
        this ability; this Charm allows them to do precisely that. The
        character simply spends the necessary Essence, and an area
        roughly two feet square before his eyes becomes transparent.
        That area doesn't move — once the character has used this
        Charm, the area that was in front of him when he spent the
        Essence remains transparent to him for a full turn. The
        Dragon-Blood can only see through about a three-inch
        thickness of stone — perhaps twice that of wood and half
        that much iron or jade. The material is only transparent to
        the Exalted using this Charm; others cannot see through it.
        Walls, doors and containers can be enchanted to prevent
        this kind of voyeurism.
        "

    resetting_tumblers_technique[Resetting Tumblers Technique]
    click resetting_tumblers_technique callback "
        Resetting Tumblers Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Larceny: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        With this ability, the Exalted can immediately discard
        a failed break-in attempt or other Larceny action and try at
        once to remedy the situation. A player may spend the
        required Essence and then immediately reroll the dice pool
        for the most recent Larceny action his character performed;
        this must take place right after the roll is made and before the
        Storyteller describes its success or failure. The Exalted must
        accept the result of the second dice roll, even if it is worse
        than the first one. Additionally, if the Larceny action and
        this Charm are part of a Combo, then using the Charm
        forces the Exalted to re-spend all of the necessary Essence to
        activate the other Charms in the Combo, even if he does not
        need to reroll or reactivate them.
        "

    artful_sprinting_theft[Artful Sprinting Theft]
    resetting_tumblers_technique --> artful_sprinting_theft
    click artful_sprinting_theft callback "
        Artful Sprinting Theft<br>
        <br>
        Cost: 1 mote<br>
        Duration: One turn<br>
        Type: Supplemental<br>
        Minimum Larceny: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Resetting Tumblers Technique<br>
        <br>
        The occasional orphaned Dragon-Blood on the
        streets of hinterland cities such as Nexus might grow up
        to learn this Charm; ordinarily, noble Terrestrials of the
        Realm will have nothing to do with it, save possibly for
        its application to later Charms. Ordinarily, even the
        simplest Larceny actions - pocket-picking and bag-snatching
         — require the character to slow down slightly,
        using only half of his maximum movement (which
        would be his Dexterity + 12 yards) on the turn he uses
        Larceny. With this Charm, the character may use his
        full dice pool on a simple Larceny action (one that
        would ordinarily take just one turn) while running flat-
        out. The action can take place at the beginning, middle
        or end of this movement.
        "

    space_crossing_theft_technique[Space-Crossing Theft Technique]
    window_in_the_door_technique --> space_crossing_theft_technique
    artful_sprinting_theft --> space_crossing_theft_technique
    click space_crossing_theft_technique callback "
        Space-Crossing Theft Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Larceny: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Window-in-the-Door Technique, Artful Sprinting Theft<br>
        <br>
        With this Charm, the Exalted can cause an object
        to disappear from its current location and reappear in
        his hands without crossing the intervening space. The
        character must be able to see the object clearly — if it
        is within a locked chest, he must use Window-In-The-Door
        Technique (see above) to see it before he can use
        Space-Crossing Theft Technique to grab it. However, if
        he can see it, he only needs to expend the Essence and
        off it goes, as long as it weighs less than about 15 pounds
        (the Storyteller's judgment is final as to what can be
        taken and what can't). This Charm does not work on
        items held by a sentient being (a mortal, Exalted or
        spirit), but it will work on items they are merely wearing:
        the Exalted could snatch a sheathed sword but not
        a sword in a foe's hand.
        "
