---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph fire_investigation[Fire Investigation Charms]
        direction TB

        revealing_light_method[Revealing Light Method]
        click revealing_light_method callback "
        Revealing Light Method<br>
        <br>
        Cost: 5 motes<br>
        Duration: 1 minute<br>
        Type: Simple<br>
        Minimum Investigation: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Fire reveals what is hidden. Its light pushes aside the
        darkness; its heat reveals the metal within the ore. A
        Dynast can use Essence to make an ordinary flame blaze up
        with a glaring, pitiless light that reveals whatever another
        person tries to conceal. Secret cupboards, chambers and
        passages are easily located as the hair-fine crack of their
        hidden doors suddenly stand out like gaping black chasms.
        A person's disguise looks laughably false.<br>
        The player rolls Perception + Investigation. A simple
        success rolled for this Charm negates any physical attempt
        to make one object or person look like another. In cases
        where something is hidden by misdirection or being placed
        in or behind other objects (such as a letter hidden in a stack
        of other missives, or within a long-necked vase) the
        Storyteller must set a difficulty rating based on how clev-
        erly or thoroughly the object is concealed, and the player
        must meet that difficulty when rolling for the Charm.<br>
        Cascade Charms:<br>
        • The Revealing Light Method does not penetrate
        magical forms of concealment and disguise. An improved
        Charm can — or at least, each success rolled cancels one
        success from any Charm of concealment.<br>
        • A more powerful or skilled Dynast could develop a
        Charm that would reveal any attempt to tell a deliberate
        lie. The Dragon-Blooded &quot;sees it in his eyes&quot; that the target
        was fibbing.
        "
    end

