---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph fire_survival[Fire Survival Charms]
        direction TB

        precise_fire_method[Precise Fire Method]
        click precise_fire_method callback "
        Precise Fire Method<br>
        <br>
        Cost: 5 motes<br>
        Duration: 1 hour<br>
        Type: Simple<br>
        Minimum Survival: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        As one might expect, the Dragon-Blooded attuned to
        Fire can shape that unstable element with preternatural skill.
        This Charm displays that power in a comparatively subtle
        way. The character starts a fire; the method doesn't matter.
        If the fire has suitable fuel, it will spread, as fires do. This fire,
        however, spreads only along a path predefined by its creator
        along invisible threads of Essence. For instance, a Fire-attuned
        character could drop a torch on a forest floor littered
        with dry leaves and have the fire burn in a narrow line, not
        even scorching the leaves near the defined path or setting the
        trees on fire. Applications include barriers of flame to restrict
        and channel a fight, or a form of time-delayed arson.
        The fire can last a full hour, fuel permitting. At the
        end of that time, the Dragon-Blood can extinguish magic-bound
        fire, if he so desires. If the character is no longer
        present to restrain the fire, it burns out of control to the
        extent that its fuel permits.<br>
        The player rolls Intelligence + Survival for the character
        to lay the threads of Essence. The basic Precise Fire
        extends through 25 square feet, in whatever simple shape
        the character desires. For instance, the Dynast could
        create a wall of fire one foot wide and 25 feet long, a solid
        square five feet on a side, a foot-thick ring eight feet in
        diameter and so on. For every extra success, the area is
        increased by an additional 25 square feet, but the character
        cannot benefit from more successes than she has points of
        permanent Essence. The Storyteller may also impose difficulty
        penalties if the character wants to burn a particularly
        complicated shape, such as writing a person's name in fire.<br>
        Cascade Charms:<br>
        • The basic Charm requires that the Dragon-Blooded
        character light the fire by hand. With greater skill and
        power, a character could initiate Precise Fires using fires
        someone else set, or from a distance. For instance, a
        character could shoot a flame arrow to start a Precise Fire
        far away, or send flames leaping from an enemy's campfire.<br>
        • A more powerful character could make the flames
        burn even in areas without suitable fuel. Whatever's avail-
        able, burns.
        "

    end

