---
config:
  theme: dark
---
flowchart TD

    herbal_medicine_techniques[Herbal Medicine Techniques]
    click herbal_medicine_techniques callback "
        Herbal Medicine Techniques<br>
        <br>
        Cost: 5 motes<br>
        Duration: Until consumed<br>
        Type: Simple<br>
        Minimum Medicine: 2<br>
        Minimum Essence: 1<br>
        <br>
        In the Age of the Exalted, most drugs and medicines
        come from plants. A physician or druggist who under-
        stands the Essence within plants can prepare drugs and
        medicines with uncannily precise effects. Each effect is
        actually a separate Charm, but a character who learns one
        Herbal Medicine Technique probably knows a few more as
        well. Some common tricks include:<br>
        • Time Delay: A drug or medicine takes effect at a
        time set by the Dragon-Blooded character, perhaps days
        after the Dynast administered the draught.<br>
        • Trigger: A drug or medicine takes effect when a
        certain external condition is met.<br>
        • Tuning: The druggist can control the content of
        hallucinations caused by a drug.<br>
        Most uses of an Herbal Medicine Technique require
        only a simple success. Some applications - for instance,
        very precise hallucinations or a time delay longer than a
        few hours — might impose difficulty penalties.
        The Dynast who would use an Herbal Medicine
        Technique must compound the drug or medicine herself
        and infuse it with Essence at that time. The effect of the
        Essence-charged drug lasts its regular duration. Only after
        the magic medicine runs its course can the character who
        created it recover the motes of Essence used in its creation.<br>
        Cascade Charms:<br>
        • With experience, a Dragon-Blooded pharmacist
        might Combo different Herbal Medicine Techniques.<br>
        • More skilled and powerful druggists might produce
        medicines with actual magical effects on their users. Storytellers
        may want to restrict how &quot;magical&quot; an effect
        characters can achieve through Medicine-based Charms.
    "
