---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph water_medicine[Water Medicine Charms]
        direction TB

        drowning_in_blood_strike[Drowning-in-blood-strike]
        click drowning_in_blood_strike callback "
        Drowning-in-blood-strike<br>
        <br>
        Cost: 4 motes<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Medicine: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The body, as anyone can see, contains a lot of water
        - blood. Dragon-Blooded warriors who learn the hidden
        tides and currents of blood can strike in such a way as to
        cause internal bleeding into an enemy's lungs. The victim
        can literally drown in his own blood.<br>
        To use this Charm, the attacker must successfully
        strike her opponent in some way. If the Drowning-in-Blood
        Strike roll succeeds, the target loses one point of
        Stamina on each subsequent turn, for as many turns as the
        player rolled successes on the Essence + Medicine roll.
        The Drowning-in-Blood Strike does not itself inflict health
        levels of damage, though it may look like a series of rapid
        punches or some other attack.<br>
        Cascade Charms:<br>
        • A more skilled or powerful Dynast no longer needs
        to punch his opponent to inflict the Drowning-in-Blood
        Strike; a light slap, or even a mere brush with a finger, will
        suffice to disrupt the flow of blood.<br>
        • An even more advanced version of the Drowning-
        in-Blood Strike adds a time delay: The attacker can prime
        the victim to drown in his own blood minutes or hours
        later.<br>
        • Techniques resembling the Drowning-in-Blood
        Strike can be used to stanch internal or external bleeding.
        "


    end

