---
config:
  theme: dark
---
flowchart TD

    forest_passage_method[Forest Passage Method]
    click forest_passage_method callback "
        Forest Passage Method<br>
        <br>
        Cost: 2 motes<br>
        Duration: The Dragon-Blooded's Essence in scenes<br>
        Type: Simple<br>
        Minimum Survival: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        A Wood-attuned character can attune herself to the
        Essence of trees, grasses, briars and other plant life around
        her. While thus attuned, she can pass through dense
        vegetation without any penalty to her movement or combat.
        Somehow, the crowding, tangling plants never seem
        to be exactly where the character is. Not only does this
        make it easier to pursue animals or fugitives through
        undergrowth, briars or other hindrances, the Dragon-Blooded
        character enjoys a considerable advantage over
        an enemy if she fights in such surroundings.<br>
        Cascade Charms:<br>
        • A more experienced or powerful Wood-attuned
        character could extend the effect of the Forest Passage
        Method to other characters, for a suitably increased Essence
        cost.<br>
        • A variation using Stealth instead of Survival makes
        a person virtually invisible, silent and undetectable while
        within forest, scrub or shrubbery.
        "


