---
config:
  theme: dark
---
flowchart TD

    memorable_performance_technique[Memorable Performance<br>Technique]
    click memorable_performance_technique callback "
        Memorable Performance Technique<br>
        <br>
        Cost: 1 mote per two dice<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Performance: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Exalt can call upon her own Essence to draw
        truly outstanding performances from within. Whether
        the performance is music, theater or another performing
        art, the character enhances her talent with this
        Charm. The character can add two dice to her Performance
        dice pool for every mote of Essence spent. She
        can no more than double her Performance Ability with
        this Charm, and if she wishes to add just a single die (for
        example, if she has an odd Performance score) she must
        spend a full mote to get it.
        "

    talented_improvisation[Talented Improvisation]
    memorable_performance_technique --> talented_improvisation
    click talented_improvisation callback "
        Talented Improvisation<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Performance: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Memorable Performance Technique<br>
        <br>
        The character with Talented Improvisation can catch
        herself in a misstep in any performance and work her way out
        of it. Whether turning a bad note into an unexpected chord
        or moving from a forgotten line into an unforgettable soliloquy,
        the character is never in serious danger when performing
        onstage. If the player spends the necessary Essence immediately
        upon making a Performance roll, she can reroll it at
        once. This must be done before the Storyteller describes the
        general success or failure of her attempt. She must take the
        second result, no matter what it is. If this Charm is part of a
        Combo, the other Charms in the Combo must be paid for a
        second time when Talented Improvisation is used, but if they
        require dice rolls, those rolls cannot be remade.
        "

    dance_of_flashing_swords[Dance of Flashing Swords]
    talented_improvisation --> dance_of_flashing_swords
    click dance_of_flashing_swords callback "
        Dance of Flashing Swords<br>
        <br>
        Cost: 2 motes, 1 Willpower, + 1 mote per extra enemy<br>
        Duration: One scene<br>
        Type: Reflexive<br>
        Minimum Performance: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Talented Improvisation<br>
        <br>
        Occasionally, a Dragon-Blooded warrior has no choice
        but to engage in combat in a crowded area or finds himself in
        another situation in which he does not want to be seen
        fighting: Perhaps an ally's mind has been subverted by an evil
        sorcerer, and the Exalt must subdue the ally without letting
        Political enemies know of his circle's internal strife. Regardless
        of the reason, this Charm lets a combatant hide his actions
        and those of a foe within what appears to be stage combat.
        Simply spend the necessary Essence to activate this Charm,
        and most observers will not realize that the ongoing battle is
        not for show alone, no matter how implausible the circumstances
        seem. If the Exalted faces many enemies simultaneously,
        he can extend this cover to include them so long as they are
        extras: He spends one additional mote per extra. He cannot
        extend such cover over a group of characters that are not
        extras, nor can he extend his cover to protect any allies of his
        that show up. This Charm will not fool characters with
        Essence higher than the character using the Charm.
        "

    enchanting_performance[Enchanting Performance]
    memorable_performance_technique --> enchanting_performance
    click enchanting_performance callback "
        Enchanting Performance<br>
        <br>
        Cost: 8 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Performance: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Memorable Performance Technique<br>
        <br>
        At this level of mastery, the Dragon-Blood's performances
        become so awe-inspiring, so staggeringly beautiful,
        that she can insinuate minor suggestions into audience
        members who behold them. If the suggestions violate individual
        audience members' Natures, then those viewers will
        not obey them; more generally, the suggestions must be the
        sorts of things that won't bring the audience to any real harm.
        They might find themselves more willing to travel to a
        particular part of town at a particular time or to buy their goods
        from a particular merchant or to trust a particular leader more
        than they would otherwise. Only one sort of performance can
        violate the rule against bringing audience members to obvious
        harm, and that is a performance designed to incite a riot.
        Perhaps obviously, this is just as dangerous to the Exalt as it is
        to the audience members and should not be attempted lightly.
        The player must spend the necessary Essence and
        Willpower to enact this Charm, and she must also roll
        Charisma + Performance. With a basic success, the character
        can instill a simple suggestion into a small crowd; the
        group will remember where they got the idea. For each
        additional success, the crowd can be somewhat larger:
        Three successes implies a crowd of hundreds and five a
        crowd of thousands. Additionally, if the character sacrifices
        one success, the crowd will not remember where they
        received the suggestion that spurred their mass activity.
        "

    protective_performance[Protective Performance]
    enchanting_performance --> protective_performance
    click protective_performance callback "
        Protective Performance<br>
        <br>
        Cost: 8 motes<br>
        Duration: Until performance ends<br>
        Type: Simple<br>
        Minimum Performance: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Enchanting Performance<br>
        <br>
        This performance lends a bit of defensive magic to an
        entire crowd of viewers. This magic can be used to protect
        the crowd from hostile or mind-affecting sorcery or from
        impersonal ranged attacks such as volleyed arrow fire. The
        Charm provides no protection against hand-to-hand attacks.
        To activate the Charm, the character must spend
        the necessary Essence. All those watching the performance
        in question receive the following benefits so long as
        the performance continues:<br>
        • Treat their Essences as being one higher than it is
        for the purposes of withstanding mind-affecting powers.<br>
        • Add two additional soak, both lethal and bashing,
        against ranged attacks.
        "

    subgraph The Outcaste
        tireless_footfalls_cadence[Tireless Footfalls Cadence]
        click tireless_footfalls_cadence callback "
            Tireless Footfalls Cadence<br>
            <br>
            Cost: 2 motes per fang<br>
            Duration: Instant<br>
            Type: Simple<br>
            Minimum Performance: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Memorable Performance Technique<br>
            <br>
            The songs of the Dragon-Blooded can inspire even
            the most slovenly unit to incredible feats of endurance. As
            her unit sets out upon the road (the song must be started
            with the march), the Terrestrial raises her voice in song,
            singing tales of the unit's glory, the prodigious feats it has
            accomplished and the justified vengeance it is going to
            wreak upon the enemy when it arrives. As she sings, her
            soldiers find their loads lightened, their resolve stiffened
            and the journey less onerous.<br>
            So long as she continues singing, her unit gains a
            number of automatic successes equal to her Permanent
            Essence - 2 (minimum 1) on all fatigue checks, and its rate
            of travel is doubled. This feat can only be performed for
            infantry units, and a single Dragon-Blooded can only
            affect a number of fangs equal to her permanent Essence +
            2, but the Charm is synergistic (see p. 45). Motes spent on
            this Charm are committed — a Dragon-Blood can keep
            the Charm working for a number of hours equal to her
            permanent Essence + Stamina.
            "

        flawless_training_execution[Flawless Training Execution]
        click flawless_training_execution callback "
            Flawless Training Execution<br>
            <br>
            Cost: 5 motes, 1 Willpower, plus 1 mote and 1 committed mote per fang trained<br>
            Duration: Two months<br>
            Type: Simple<br>
            Minimum Performance: 2<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: None<br>
            <br>
            This Charm allows the Dragon-Blooded to execute
            a training plan developed by Charms higher in this tree.
            With the Charm in effect, the Exalt can flawlessly lead
            drills, impart knowledge and teach classes without error.
            A single Dragon-Blooded can train a number of
            fangs equal to his Permanent Essence, but this Charm is
            synergistic (see p. 45) — groups of Terrestrials working
            in concert can train large units of troops quickly. Each
            use of this Charm requires a training program or protocol
            developed with the Peerless Training Method
            Protocols or other Charms — a Dragon-Blooded can
            memorize a number of training programs at one time
            equal to his permanent Essence. While this Charm is in
            use, 1 mote of Essence per fang trained is committed to
            its continued operation - these motes are released
            when the program is complete.
            "

        peerless_training_method_protocols[Peerless Training Method Protocols]
        click peerless_training_method_protocols callback "
            Peerless Training Method Protocols<br>
            <br>
            Cost: 7 motes, 1 Willpower<br>
            Duration: One month per dot of permanent Essence, or until training program is used<br>
            Type: Simple<br>
            Minimum Performance: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Flawless Training Execution<br>
            <br>
            During the First Age, the Dragon-Blooded relied
            on the Celestial Exalted and their superior training
            methods to bring knowledge to the people and acted as
            facilitators, rather than designers, of training programs.
            When the Usurpation was being planned, the
            Terrestrial Exalted developed this family of Charms as
            a way to secretly train commandos and soldiers for
            their war, and the Dragon-Bloods have continued to
            refine the process ever since.<br>
            Like the Sense-Destroying Methods, this Charm is
            actually a family of Charms that work in an identical
            fashion — five examples of the Charms available are listed
            in the Protocols sidebar on this page, but others are known,
            and more can be developed as needed. Using one of these
            Charms, a skilled Dragon-Blood can develop a training
            program to improve those undergoing the program in
            specific areas — she can teach civilians how to be soldiers,
            teach disaster recovery techniques or impart the fundamentals
            of nearly any task.<br>
            To use these Charms, the Terrestrial develops a
            training program — this requires one week, minus one
            day for each dot of permanent Essence over 2 (so a
            Dragon-Blooded with Essence 4 can develop a training
            program in five days). At the end of this time, the
            Charm's user commits the plan to record on paper, and
            his player rolls the character's Intelligence + Performance,
            against a difficulty of 4. If the Charm is successful,
            the plan will raise one Ability listed to 3, two Abilities to
            2 and the remaining Abilities to 1 each, add one dot to
            an Attribute listed and raise one of the Virtues listed by
            one. Extra successes can be used to buy specialties for the
            Abilities raised - each extra success equals one specialty.
            No more than two specialties can be gained in this
            fashion. A failed roll indicates a training plan that simply
            will not work — the time and Essence spent is lost. A
            botched roll indicates a training plan that is subtly flawed
            in some fashion — it cannot work, but this will not
            become evident until it is implemented in the field by
            being used by someone with the Flawless Training Ex-
            ecution Charm. This will typically be noticeable within
            the first week of training, but particularly bad botches
            may take weeks to become evident.<br>
            The Abilities gained by this Charm are not additive
            - if a character has more dots in that Ability than the
            training program would provide, she gains no benefit
            (though she may still gain any attached specialties, if she
            has less than three). These Charms cannot raise Attributes
            above 3, Virtues above 2 or Willpower above 8 (these stats
            can be raised later through experience). A given character
            can only benefit from a single Charm in this tree once but
            can be the recipient of multiple different Charms (so a
            character could receive the Combat Drill Protocol and
            then the Officer Readiness Training Protocol). This Charm
            has no effect whatsoever on individuals with an Essence
            higher than 1.<br>
            Each training program is unique and can only be
            used once — if a developer wants to hand a training
            program to two subordinates, he must use this Charm
            twice and develop two different programs. A Dragon-
            Blooded can develop as many training programs as he
            likes, but each requires 2 committed motes of Essence to
            remain viable - these motes are returned when some-
            one with the Flawless Training Execution Charm uses
            the training program.
            "
    end
    memorable_performance_technique --> tireless_footfalls_cadence
    flawless_training_execution --> peerless_training_method_protocols
