---
config:
  theme: dark
---
flowchart TD

    forest_passage_method[Forest Passage Method]
    click forest_passage_method callback "
        Forest Passage Method<br>
        <br>
        Cost: 2 motes<br>
        Duration: The Dragon-Blooded's Essence in scenes<br>
        Type: Simple<br>
        Minimum Survival: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        A Wood-attuned character can attune herself to the
        Essence of trees, grasses, briars and other plant life around
        her. While thus attuned, she can pass through dense
        vegetation without any penalty to her movement or combat.
        Somehow, the crowding, tangling plants never seem
        to be exactly where the character is. Not only does this
        make it easier to pursue animals or fugitives through
        undergrowth, briars or other hindrances, the Dragon-Blooded
        character enjoys a considerable advantage over
        an enemy if she fights in such surroundings.<br>
        Cascade Charms:<br>
        • A more experienced or powerful Wood-attuned
        character could extend the effect of the Forest Passage
        Method to other characters, for a suitably increased Essence
        cost.<br>
        • A variation using Stealth instead of Survival makes
        a person virtually invisible, silent and undetectable while
        within forest, scrub or shrubbery.
        "

    wild_wandering_forester_charm[Wild-Wandering<br>Forester Charm]
    click wild_wandering_forester_charm callback "
        Wild-Wandering Forester Charm<br>
        <br>
        Cost: 1 mote per 2 dice<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Survival: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Exalt using this Charm calls upon his superior
        knowledge of the wilderness and uses his Essence, and
        his relationship to the Elemental Pole of Wood in
        particular, to improve his chance of survival in hostile
        environments. The Dragon-Blood can improve his Survival
        dice pools by two dice for every mote of Essence
        spent, but can no more than double his Survival Ability.
        The character must spend a full mote of Essence
        even if he wishes to add just a single die (as might be the
        case if he has an odd Survival score).
        "

    forgiveness_of_nature_invoking_prana[Forgiveness of<br>Nature Invoking Prana]
    wild_wandering_forester_charm --> forgiveness_of_nature_invoking_prana
    click forgiveness_of_nature_invoking_prana callback "
        Forgiveness of Nature Invoking Prana<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Survival: 2<br>
        Minimum Essence: 2<br>
        <br>
        Prerequisite Charms: Wild-Wandering Forester Charm
        The Exalt with this Charm is able to beg a brief favor
        of the spirits of the natural world when he has given offense
        or behaved in an inappropriate manner before them. In so
        doing, he may be able to correct prior mistakes, although
        there is always the chance that he will instead give further
        offense. Immediately after a Survival roll, the Dragon-Blood's
        player may spend 2 motes of Essence and reroll. He
        must accept the second roll. If this Charm is part of a
        Combo, the character must pay all the Essence necessary
        to activate associated Charms again, even if they do not
        contribute to the rerolled pool.
        "

    quarry_revelation_technique[Quarry Revelation<br>Technique]
    wild_wandering_forester_charm --> quarry_revelation_technique
    click quarry_revelation_technique callback "
        Quarry Revelation Technique<br>
        <br>
        Cost: 2 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wild-Wandering Forester Charm<br>
        <br>
        With this Charm, the Exalted can track the passage
        of nearly any creature that is not using magic (such as
        Trail Concealing Measurement, below) to hide signs of
        its passing. The character needs only to spend the required
        Essence, and signs of his quarry's passage stand out
        to the character's eyes: Animal tracks and spoor become
        much more prominent, and the broken twigs and other
        signs that reveal a human's passage are quite clear. The
        tracker's player must make a simple Perception + Survival
        roll and acquire only a single success to keep on his
        prey's trail, regardless of the conduciveness of the local
        terrain and weather to tracking. The character cannot
        follow a trail more than a week old with this Charm. If the
        target is using Trail Concealing Measurement or some
        other wilderness Charm that makes her untrackable
        without magical aid, then this Charm counts as such aid.
        Under such circumstances, the tracking Exalt's player
        may make a normal Survival roll to track the target but
        does not gain this Charm's normal mechanical bonus.
        "

    trail_concealing_measurement[Trail Concealing<br>Measurement]
    quarry_revelation_technique --> trail_concealing_measurement
    click trail_concealing_measurement callback "
        Trail Concealing Measurement<br>
        <br>
        Cost: 3 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Survival: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Quarry Revelation Technique<br>
        <br>
        The Exalted using Trail Concealing Measurement
        knows instinctually how to hide signs of his passage. He
        does this so skillfully that mortal trackers and those without
        Quarry Revelation Technique (above) or other magical
        means of tracking him are unable to do so. Players of beings
        with magical means to pursue the character make normal
        rolls to track the character. It is rumored by those who have
        traveled close to the Wyld that the Lunar Exalted are not
        fooled by this Charm at all when they wear animal shapes.
        "

    ration_enhancing_method[Ration-Enhancing Method]
    quarry_revelation_technique --> ration_enhancing_method
    click ration_enhancing_method callback "
        Ration-Enhancing Method<br>
        <br>
        Cost: 2 motes<br>
        Duration: One hunt<br>
        Type: Simple<br>
        Minimum Survival: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Quarry Revelation Technique<br>
        <br>
        Ration-Enhancing Method doubles the effectiveness
        of any hunting expedition the character takes part in
        during the scene that it is active. Whether alone or as part
        of a group, when the Dragon-Blood with this Charm sets
        off to find food, he (and his group, if applicable) will find
        twice as much food as the level of success on their Survival
        rolls would otherwise imply.
        "

    hostile_environment_preparation[Hostile Environment<br>Preparation]
    wild_wandering_forester_charm --> hostile_environment_preparation
    click hostile_environment_preparation callback "
        Hostile Environment Preparation<br>
        <br>
        Cost: 3 motes + 1 per companion<br>
        Duration: 1 Day<br>
        Type: Simple<br>
        Minimum Survival: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wild-Wandering Forester Charm<br>
        <br>
        This Charm enables an Exalt and his companions to
        avoid the worst effects of hostile environments. In a hot
        environment, the Exalted leading the group uses this
        Charm to make sure he and his fellows remain out of the
        worst heat of the sun and conserve water. In a cold
        environment, he makes sure they conserve body heat as
        well as possible and remain moving to avoid frostbite.
        When Hostile Environment Preparation Method is active,
        the group can be assumed to be unharmed by any
        environment that would ordinarily require three or fewer
        successes on a Survival roll. Environments that would
        require four or more successes now require three fewer
        successes, so even the most hostile natural environment
        only requires two successes on a Survival roll. The Charm's
        base 3 motes cost protects the Exalt. Every additional
        mote spent protects a single traveling companion. An
        Exalt cannot protect more individuals with this Charm
        than his permanent Essence.
        "

    shelter_creation_technique[Shelter Creation Technique]
    hostile_environment_preparation --> shelter_creation_technique
    click shelter_creation_technique callback "
        Shelter Creation Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Survival: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Hostile Environment Preparation Method<br>
        <br>
        The character calls upon helpful spirits of Wood
        (and, if appropriate, other elements) to help him build
        a remarkably robust, protective and comfortable shelter
        even in the worst environment. For a group traveling in
        the forest, the Exalted can create a wooden hut in a
        matter of about 30 minutes. Those traveling in the
        desert can find themselves in a sheltered outcropping,
        shaded from above and with plenty of room for wind to
        flow through. A character in the Far North may build an
        igloo or other hard-packed snow shelter in about 30
        minutes. These shelters will last no more than a day, as
        they are somewhat magical in nature. Generally, the
        shelter the character builds can hold around six human-sized
        creatures; if the Exalted wishes to build a larger
        shelter, he must spend an additional mote of Essence per
        person to be accommodated within it.
        "
