---
config:
  theme: dark
---
flowchart TD

    %% described in Storyteller's Companion
    subgraph air_archery[Air Archery Charms]
        direction TB

        archers_favorable_wind[Archer's Favorable Wind]
        click archers_favorable_wind callback "
        Archer's Favorable Wind<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Archery: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Wind makes archery less accurate because it blows
        arrows off course. The Aspects of Air, however, can
        persuade the winds to let the arrow fly unhindered. Each
        point of Essence the character has cancels one point of
        extra difficulty. Thus, a Dynast of Air with Essence 4 could
        practice target shooting in a hurricane! Each bowshot
        demands a separate use of this Charm.<br>
        Cascade Charms:<br>
        • A more experienced Aspect of Air might be able to
        negate wind penalties for a few minutes, during which she
        could fire as many arrows as she wanted.<br>
        • The character could extend the Archer's Favorable
        Wind to a small group of other characters.<br>
        • An Air-attuned archer might persuade the winds to
        blow against the arrows of his enemies, increasing their
        difficulty to hit.
        "

        fortunate_wind_attack[Fortunate Wind Attack]
        click fortunate_wind_attack callback "
        Fortunate Wind Attack<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Archery: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Through this basic Charm, a Dragon-Blooded archer
        persuades the winds to propel and guide his arrow. The
        range increment of the character's weapon in doubled for
        that attack.<br>
        Cascade Charms:<br>
        • A more experienced Dynast of Air could extend this
        Charm's effect to a small group of people.<br>
        • As with various Archery-based Charms used by
        Solars, a Dragon-Blooded archer might negate range pen-
        alties entirely.
        "

    end

