---
config:
  theme: dark
---
flowchart TD

    subgraph Players Guide
        transubstantiation_of_flesh[Transubstantiation of Flesh]
        click transubstantiation_of_flesh callback "
            Transubstantiation of Flesh<br>
            <br>
            Cost: 5 motes per hour (plus 1 Willpower in Creation)<br>
            Duration: Varies<br>
            Type: Simple<br>
            Minimum Conviction: 2<br>
            Minimum Essence: 1<br>
            Prerequisite Charms: None<br>
            <br>
            With this Arcanos, a Ghost-Blood may suffuse his
            body with necrotic Essence, blurring the distinction between
            flesh and corpus. This effect lasts one hour for every
            5 motes spent. During that time, the ghost-blood's body
            becomes fully malleable to the Arcanoi of the Shifting
            Ghost-Clay Path. In addition, the character gains the
            ability to soak lethal damage with half Stamina and
            otherwise resists injury, poison and disease like one of the
            Exalted. When the duration ends, however, the spectral
            flesh overrides all changes and reverts to its original state.
            Characters employing this Arcanos can perceive incorporeal
            ghosts clearly, though other types of spirits remain
            hidden to their senses.
            "

        lower_soul_ascendant[Lower Soul Ascendant]
        click lower_soul_ascendant callback "
            Lower Soul Ascendant<br>
            <br>
            Cost: 7 motes, 1 Willpower<br>
            Duration: One scene<br>
            Type: Simple<br>
            Minimum Conviction: 2<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Transubstantiation of Flesh<br>
            <br>
            Unlike their ghostly parents, the Half-Dead retain
            both higher and lower souls. Although both halves
            remain conjoined until death, a Ghost-Blood with this
            Arcanos may briefly subsume his higher consciousness
            to the bestial power of his bloated po. For the rest of the
            scene, the character loses all morality and embraces
            psychopathic behavior such as that imposed by the
            Deliberate Cruelty Virtue Flaw (see Exalted, p. 132). In
            addition, the character suffers no wound penalties and
            adds his Essence rating to all Physical Attributes. When
            the Arcanos ends, his player must roll Conviction +
            Essence. The character remains trapped in his inhuman
            cruelty for a number of hours equal to the successes
            rolled. Incapacitated or mortally wounded Ghost-Blooded
            may explicitly activate Lower Soul Ascendant
            as a reflexive action regardless of whether they are
            conscious or have already used a Charm during the turn.
            If the character cannot pay any part of the cost, the
            Arcanos still takes effect but the character loses a dot of
            permanent Willpower. Used in this fashion, the Ghost-Blood
            instantly heals all bashing levels and a number of
            levels of lethal damage equal to his Conviction but also
            loses a dot of permanent Essence as the Arcanos activates
            (in addition to any permanent Willpower loss).
            The character retains any Arcanoi for which he fails to
            meet the Minimum Essence requirements, but he cannot
            use them until he spends experience to restore his
            diminished spirit.
            "

        spiteful_essence_onslaught[Spiteful Essence Onslaught]
        click spiteful_essence_onslaught callback "
            Spiteful Essence Onslaught<br>
            <br>
            Cost: 1 mote per 1L per target<br>
            Duration: Instant<br>
            Type: Simple<br>
            Minimum Conviction: 3<br>
            Minimum Essence: 3<br>
            Prerequisite Charms: Lower Soul Ascendant<br>
            <br>
            Building on the principles of Lower Soul Ascendant,
            a Ghost-Blood can manifest the wrath of her
            swollen po in rays of pale, searing Essence. As the
            Arcanos activates, dancing sparks of cold light ignite
            around the character like will-o-wisps, brightly visible
            to material and immaterial onlookers alike. From these
            sparks emerge beams of manifested spite. The Ghost-
            Blood's player makes one attack roll of Charisma +
            Conviction, with a base difficulty of the number of
            separate targets included in the barrage. The character
            cannot attack more targets in a single use of this Arcanos
            than her Essence rating. The base damage is 1L per mote
            spent powering the blast, plus successes on the attack
            roll, but the character must spend motes for each target
            separately, allocating at least 1 mote to each.<br>
            Characters cannot spend more motes on all uses of
            this Charm in a single turn than their Conviction +
            Essence. Thus, a barrage against two targets by a character
            with Conviction 4 and Essence 2 could inflict up to 5L on
            the first target and 1L on the second target or inflict 3L to
            each or divide the damage in any combination of 6L or less.
            This Arcanos affects material and dematerialized beings
            equally and may be used by incorporeal Ghost-Blooded to
            attack the living as readily as spirits.
            "

        wraith_form_transformation[Wraith Form Transformation]
        click wraith_form_transformation callback "
            Wraith Form Transformation<br>
            <br>
            Cost: 6 motes per hour, plus 1 Willpower<br>
            Duration: Varies<br>
            Type: Simple<br>
            Minimum Conviction: 2<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: Transubstantiation of Flesh<br>
            <br>
            A Ghost-Blood employing Wraith Form Transformation
            ripples and fades away with a rustling whisper, her
            flesh wholly subsumed into the corpus of her Half-Dead
            soul. This Arcanos duplicates the effects of Transubstantiation
            of Flesh, including resistance conferred and
            susceptibility to Arcanoi of the Shifting Ghost-Clay Path.
            Furthermore, she does not need air, food or water for the
            duration of the effect. However, the Arcanos also causes
            the Ghost-Blood to dematerialize as per the spirit Charm
            of the same name (see p. 82). Unlike elementals, Ghost-
            Blooded may still regain Essence through respiration and
            pay no upkeep while dematerialized with this Arcanos.
            However, it still requires a dice action for a Ghost-Blood
            to prematurely end the effect to rematerialize, and wards
            intended to bar the passage of ghosts can stop her.<br>
            While immaterial, Ghost-Blooded can use Arcanoi of
            the Terror-Spreading Art or Stringless Puppeteer Art to
            affect the physical world, though a possessing Ghost-Blood
            suffers forcible ejection from her host as the Arcanos
            ends and she reforms. Characters employing this Arcanos
            may reflexively spend 1 mote to manifest as a translucent
            phantom in the physical world for up to one scene. While
            manifested as a phantom, the character may speak and be
            heard as a faint whisper, but she remains incorporeal. A
            character who dies while under the effects of Wraith Form
            Transformation always becomes a ghost.
            "


        ghost_body_evasion[Ghost Body Evasion]
        click ghost_body_evasion callback "
            Ghost Body Evasion<br>
            <br>
            Cost: 6 motes<br>
            Duration: One turn<br>
            Type: Reflexive<br>
            Minimum Conviction: 4<br>
            Minimum Essence: 3<br>
            Prerequisite Charms: Wraith Form Transformation<br>
            <br>
            A Ghost-Blood with this Arcanos may dissolve into
            an incorporeal form in response to physical danger, perceived
            or otherwise. He remains visible to onlookers as a
            luminous translucent phantom, but all physical attacks
            pass through his incorporeal body. Use of this Arcanos is
            not considered a type of dodge or soak, but may preempt
            damage by allowing the character to become immaterial in
            the instant before an attack strikes. Obviously, Ghost
            Body Evasion provides no defense against attacks that
            function against immaterial beings. Characters may
            rematerialize prior to the end of the turn if so desired by
            reflexively spending one Willpower point. The immaterial
            state granted by this Arcanos duplicates the effects of
            Wraith Form Transformation.
            "


        restless_spirit_sojourn[Restless Spirit Sojourn]
        click restless_spirit_sojourn callback "
            Restless Spirit Sojourn<br>
            <br>
            Cost: 15 motes, 1 Willpower<br>
            Duration: Indefinite<br>
            Type: Simple<br>
            Minimum Conviction: 3<br>
            Minimum Essence: 3<br>
            Prerequisite Charms: Wraith Form Transformation<br>
            <br>
            With the activation of this Arcanos, a Ghost-Blood's
            body falls into a deep coma, and her soul flows from her
            mouth as an immaterial cloud of Essence. The soul reforms
            over the next turn into the dematerialized semblance of
            the character, as if she had used Wraith Form Transformation.
            This spirit body begins with a number of -0 health
            levels equal to the character's permanent Willpower plus
            any levels obtained with Ox-Body Technique. The soul
            keeps track of health separate from the actual body. A
            Ghost-Blood using Restless Spirit Sojourn may return her
            soul to her body across any distance by reflexively spending
            a Willpower point and accepting a level of unsoakable
            aggravated damage to her flesh. Recalling a soul does not
            count as a Charm use and may be performed on the same
            turn as the character activates other Charms. No Essence
            or Willpower is required if the soul can &quot;touch&quot; its flesh in
            an attempt to rejoin, and this form of return incurs no
            aggravated damage.<br>
            If a character's spirit body dies, she loses one point
            of permanent Essence, and her scarred soul returns to its
            flesh. Once soul and flesh rejoin by any method, the
            body immediately awakens with a painful gasp. An
            awakened Ghost-Blood cannot escape her flesh again
            with this Arcanos until a number of hours have passed
            equal to the health levels of damage her soul had
            suffered at the time of rejoining.<br>
            While using this Arcanos, a Ghost-Blood's torpid
            body needs only a third of its usual intake of air, food and
            water and may be force-fed by caretakers. Since characters
            do not feel the needs of their flesh while using this
            Arcanos, Ghost-Blooded must take care not to let their
            bodies wither away from starvation or thirst. If a Ghost-Blood's
            body dies in its soul's absence, the soul experiences
            a turn of terrible agony in which she can do nothing but
            writhe and scream. When the pain fades, the character
            becomes a full ghost with her body's usual health levels
            minus any spiritual damage already sustained.
            "

    end

    transubstantiation_of_flesh --> lower_soul_ascendant
    lower_soul_ascendant --> spiteful_essence_onslaught
    transubstantiation_of_flesh --> wraith_form_transformation
    wraith_form_transformation --> ghost_body_evasion
    wraith_form_transformation --> restless_spirit_sojourn
