---
config:
  theme: dark
---
flowchart TD

    speak_with_the_dead[Speak With the Dead]
    click speak_with_the_dead callback "
        Speak With the Dead<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Investigation: 3<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        The lands of the dead are not far from the lands of the
        living. Sometimes ghosts can observe the doings of the
        living with near clarity. This Charm allows an Abyssal to
        ask a single question of an incorporeal ghost about events
        that have happened in that location within the last 10
        minutes x successes rolled.
        "
