---
config:
  theme: dark
---
flowchart TD

    blight[Blight]
    click blight callback "
        Blight<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Lore: 2<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        By forcing her death Essence into the land around her,
        the deathknight can destroy all the plant life in the
        vicinity and seriously damage the living creatures that live
        there. The player rolls Charisma + Lore. All plants within
        a circular area with a radius equal to the number of
        successes rolled in meters wither and die. All animals and
        people within that radius, including other Exalted, take
        three dice of lethal damage.
        "
