---
config:
  theme: dark
---
flowchart TD

    rust[Rust]
    click rust callback "
        Rust<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Craft: 3<br>
        Minimum Essence: 1<br>
        Prerequisite: None<br>
        <br>
        The Exalted channels Essence directly into a piece of
        metal, causing it to rust away to nothing within seconds.
        This Charm can be used only on objects the size of a large
        sword or a single suit of metal armor. This Charm does not
        work on items made from or reinforced by the Five Magical
        Materials. This Charm has a range of 10 yards x the
        Abyssal's Essence and may be used only once per turn.
        "
