---
config:
  theme: dark
---
flowchart TD

    contaminate[Contaminate]
    click contaminate callback "
        Contaminate<br>
        <br>
        Cost: 4 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Medicine: 3<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        Diseases are one of the doors to the Underworld. This
        Charm allows an Abyssal to open that door somewhat,
        temporarily infecting the target with a plague. The player
        chooses from one of the plagues listed in the Exalted rulebook
        (page 298) and makes an Intelligence + Medicine roll. If the
        roll is successful, the target must succeed on a Stamina +
        Resistance roll to resist infection, just as if exposed to the
        disease in question. The illness is noncommunicable.
        "
