---
config:
  theme: dark
---
flowchart TD

    terrestrial_circle_sorcery[Terrestrial Circle Sorcery]
    click terrestrial_circle_sorcery callback "
        Terrestrial Circle Sorcery<br>
        <br>
        Cost: 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Occult: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: None<br>
        <br>
        Least of all sorcery and still worlds beyond the power
        of the most talented mortal wizards, magic of the First
        Circle sees much use among the deathknights.
        Note that invoking this Charm only enables the
        character to cast a single Terrestrial Circle Sorcery spell.
        The actual spell itself has an Essence cost, often very high,
        that the character must pay to actualize it. This cost is
        listed in the spell’s description. Terrestrial Circle Sorcery
        can never be part of a Combo.
        "

    celestial_circle_sorcery[Celestial Circle Sorcery]
    terrestrial_circle_sorcery --> celestial_circle_sorcery
    click celestial_circle_sorcery callback "
        Celestial Circle Sorcery<br>
        <br>
        Cost: 2 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Occult: 4<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: Terrestrial Circle Sorcery<br>
        <br>
        Easily outstripping the most potent spells of the Dragon-Blooded,
        the magic of the Second Circle is well known in the
        Underworld as a weapon of the Deathlords and their Daybreak
        Caste servants. Other Abyssal Exalted must often coax
        or barter with these entities for power, though the sorcerer-
        kings of the dead are notably reticent to share their secrets.
        Celestial Circle Sorcery can never be part of a Combo.
        "

    shadowlands_circle_necromancy[Shadowlands Circle Necromancy]
    click shadowlands_circle_necromancy callback "
        Shadowlands Circle Necromancy<br>
        <br>
        Cost: 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Occult: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: None<br>
        <br>
        Where sorcery manipulates and channels the Essence
        of Creation, its sister art of necromancy binds the dark
        energies of the Underworld. The Essence of death is potent
        but limited in scope. What it lacks in flexibility, however,
        it makes up for in might. Those who delve into the mystical
        lore of the Malfeans to master this Charm can hone will
        and spirit to perform necromancy of the First Circle. Note
        that, as with sorcery, the cost of this Charm only enables
        the character to cast a single Shadowlands Circle spell.
        The actual spell itself has an Essence cost, often very high,
        that the character must pay to actualize it. This cost is
        listed in the spell’s description. Shadowlands Circle Necromancy
        can never be part of a Combo.
        "

    labyrinth_circle_necromancy[Labyrinth Circle Necromancy]
    shadowlands_circle_necromancy --> labyrinth_circle_necromancy
    click labyrinth_circle_necromancy callback "
        Labyrinth Circle Necromancy<br>
        <br>
        Cost: 2 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Occult: 4<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: Shadowlands Circle Necromancy<br>
        <br>
        Above — or perhaps below — the necromancy of
        the First Circle, Labyrinth Circle magic is the stuff of
        nightmares and dreams best left to dead gods. Still, for
        those who would master its secrets, this circle offers great
        and terrible power. Labyrinth Circle Necromancy can
        never be part of a Combo.
        "

    void_circle_necromancy[Void Circle Necromancy]
    labyrinth_circle_necromancy --> void_circle_necromancy
    click void_circle_necromancy callback "
        Void Circle Necromancy<br>
        <br>
        Cost: 3 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Occult: 5<br>
        Minimum Essence: 5<br>
        Prerequisite Charms: Labyrinth Circle Necromancy<br>
        <br>
        In true poetic irony, the very death taint that denies
        the Abyssal Exalted access to Solar Circle Sorcery also
        grants them comparable power over the Oblivion they
        serve. Masters of Void Circle Necromancy are thankfully
        rare, but theirs is the power of unmaking, the power that
        would devour all Creation in its hunger — and the
        Underworld as well. Few spells of this potency exist
        outside the personal libraries of the Deathlords; the
        sorcerer-kings of the Underworld zealously hoard such
        mighty lore as they hoard little else. Void Circle Necromancy
        can never be part of a Combo.
        "

    spirit_sensing_technique[Spirit Sensing Technique]
    click spirit_sensing_technique callback "
        Spirit Sensing Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Occult: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm allows the character to perceive dematerialized
        spirits in her vicinity. Such beings appear as
        translucent specters of their materialized form, although
        ghosts appear more “solid” to the Abyssal than other types
        of spirits. Every 5 motes spent above the Charm’s base cost
        allow the character to project one additional sense into the
        spirit realm. However, even if a character can feel the
        touch of a dematerialized spirit, she cannot actually touch
        it without employing other magic.
        "

    through_dead_eyes[Through Dead Eyes]
    spirit_sensing_technique --> through_dead_eyes
    click through_dead_eyes callback "
        Through Dead Eyes<br>
        <br>
        Cost: 6 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Occult: 5<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Spirit Sensing Technique<br>
        <br>
        Even in the most verdant forests, the necrotic Essence
        of the Underworld leaks through into Creation in
        wisps and trails. With this potent Charm, an Abyssal can
        perceive these energies directly. Beings and places suffused
        with death glow with their own baleful radiance,
        while objects imbued with living Essence appear shadowed
        or empty. In addition to perceiving dematerialized
        ghosts, the character can identify other Abyssal Exalted
        with a glance and precisely determine the boundaries of
        any shadowland. Deathknights employing this Charm
        can also spot the seething ripples and whorls of Charms
        and sorcery, allowing them to notice most magic without
        a roll. With a successful Intelligence + Occult roll, a
        character can even identify magic (although the difficulty
        increases by 1 if the scrutinized magic does not
        involve death energy).
        "

    corpus_rending_blow[Corpus-Rending Blow]
    spirit_sensing_technique --> corpus_rending_blow
    click corpus_rending_blow callback "
        Corpus-Rending Blow<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Occult: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Spirit Sensing Technique<br>
        <br>
        Charging his hand or weapon with spectral energy,
        the character can make one strike against an immaterial
        spirit. The character’s player must still roll to hit the
        creature normally, although the deathknight may elect to
        attack the spirit’s Essence in lieu of inflicting damage. This
        decision must be made when activating the Charm, before
        rolling the attack. If the Abyssal chooses to drain Essence,
        roll her Conviction + Occult in place of damage, using the
        spirit’s Valor as its soak total. Each level of “damage”
        inflicted in this fashion drains 2 motes of Essence from the
        spirit’s pool and adds it to the character’s own. Drained
        motes that would take a character above her normal
        maximum are still drained but dissipate without benefit to
        the Exalt. If the character uses this Charm to cause actual
        injury, the attack is resolved normally. This Charm confers
        no ability to perceive incorporeal spirits, so characters
        attacking without other magic (such as Spirit Sensing
        Technique) suffer the usual penalty for blind fighting. This
        Charm has no effect on materialized spirits. Corpus-Rending
        Blow is explicitly permitted to be part of a Combo with
        Charms of other Abilities.
        "

    soul_eating_strike[Soul-Eating Strike]
    corpus_rending_blow --> soul_eating_strike
    click soul_eating_strike callback "
        Soul-Eating Strike<br>
        <br>
        Cost: 5 motes<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Occult: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Corpus-Rending Blow<br>
        <br>
        This Charm allows an Abyssal to infuse a single attack
        with the chill of the Void. The character’s blow can strike
        incorporeal spirits. A successful hit inflicts aggravated damage
        and drains Essence as Corpus-Rending Blow (roll
        separately for each form of damage). Spirits slain by such
        attacks are irrevocably destroyed. Against materialized spir-
        its, this Charm allows the Abyssal to drain Essence as above,
        but the attack does not inflict aggravated damage. Materialized
        spirits killed via Soul-Eating Strike eventually
        regenerate. This Charm is explicitly permitted to be part of
        a Combo with Charms of other Abilities. Spirits can sense
        Exalted who know this Charm and fear and loathe them.
        "

    spirit_draining_ward[Spirit-Draining Ward]
    soul_eating_strike --> spirit_draining_ward
    click spirit_draining_ward callback "
        Spirit-Draining Ward<br>
        <br>
        Cost: 10 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Occult: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Soul-Eating Strike<br>
        <br>
        Opening himself as a conduit to the Void, the Abyssal
        spreads his arms, and a maelstrom of flickering shadows
        billows out to fill a radius equaling his permanent Essence in
        yards. This effect remains centered on the character for the
        remainder of the scene. While visible in the material world,
        the unnatural storm barely raises a light breeze. However,
        immaterial spirits within the area of effect suffer battering
        cold equivalent to an arctic gale. Against such creatures, this
        Charm inflicts a number of levels of aggravated damage equal
        to the Abyssal’s permanent Essence minus the spirit’s permanent
        Essence. This damage is not rolled. It is simply applied
        each turn unless the spirit has a means of soaking aggravated
        damage. The character regains 2 motes of Essence for every
        level of damage inflicted by the ward, up to his usual maximum.
        Spirits killed by this Charm are sucked into the Void
        and permanently destroyed. Although this Charm cannot
        injure spirits whose Essence rating matches or exceeds the
        character, the ward still discomfits them (adding +1 to the
        difficulty of all actions inside its area of effect). Materialized
        spirits are immune to this Charm. Spirits can sense Exalts who
        knows this Charm and hate them for it.
        "
