---
config:
  theme: dark
---
flowchart TD

    withered_touch[Withered Touch]
    click withered_touch callback "
        Withered Touch<br>
        <br>
        Cost: 1 mote<br>
        Duration: One turn<br>
        Type: Supplemental<br>
        Minimum Brawl: 3<br>
        Minimum Essence: 1<br>
        Prerequisite: None<br>
        <br>
        The Exalted focuses the Essence of the Underworld
        into his hands. Any attacks the character makes without
        a weapon that turn cause lethal rather than bashing
        damage. However, this Charm only works against bare or
        cloth-covered flesh. Characters in metal armor are im-
        mune to this Charm. Abyssals who use this Charm often
        Combo it with the Rust Charm.
        "
