---
config:
  theme: dark
---
flowchart TD

    dirge[Dirge]
    click dirge callback "
        Dirge<br>
        <br>
        Cost: 4 motes<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Performance: 3<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        A deathknight can channel Essence into a mournful
        song so that the audience, willing or otherwise, starts to die
        as they listen. Their bodies weaken as their life Essence is
        sucked away into the Underworld. Each listener suffers 3L
        dice of damage each turn that they listen to the song,
        which can be soaked only by Stamina and soak-boosting
        Charms. The Essence cost of this Charm must be spent
        each turn that the deathknight continues to sing his Dirge.
        "
