---
config:
  theme: dark
---
flowchart TD

    ox_body_technique[Ox-Body Technique]
    click ox_body_technique callback "
        Ox-Body Technique<br>
        <br>
        Cost: None<br>
        Duration: Permanent<br>
        Type: Special<br>
        Minimum Endurance: Varies<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        As befitting the champions of the Underworld, Abyssal
        Exalted are far more resilient than mere mortals and
        may purchase extra health levels as if they were a Charm.
        This Charm can be taken as many times as a character has
        dots of Endurance. Each Ox-Body Technique purchased
        provides one of the following, decided by the player at the
        time of purchase:<br>
        • One -0 health level<br>
        • Two -1 health levels<br>
        • One -1 health level and two -2 health levels<br>
        "

    ghost_armor_prana[Ghost Armor Prana]
    click ghost_armor_prana callback "
        Ghost Armor Prana<br>
        <br>
        Cost: 3 motes per point
        Duration: One hour
        Type: Simple
        Minimum Endurance: 3
        Minimum Essence: 2
        Prerequisite Charms: None
        The Abyssal enfolds his anima about his armor, grant-
        ing it surreal lightness for an hour. For every 3 motes spent,
        the character reduces the fatigue value and mobility penalty
        of his armor by one point, to a maximum possible reduction
        equal to his permanent Essence. A fatigue value of zero
        indicates the character need never roll to see if he becomes
        fatigued from wearing his armor. This Charm cannot reduce
        a character’s mobility penalty or fatigue value below zero.
        "

    tireless_sentinel_technique[Tireless Sentinel Technique]
    ghost_armor_prana --> tireless_sentinel_technique
    click tireless_sentinel_technique callback "
        Tireless Sentinel Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Endurance: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Ghost Armor Prana<br>
        <br>
        An Abyssal with this Charm may revivify himself with
        Essence, allowing him to act at full strength without penalties
        for sleep loss or exhaustion. There is no limit to how many
        days this Charm can be used in a row, but animating death
        Essence is a poor substitute for natural rest. After a number of
        days equal to the character’s Stamina + Endurance, the Exalt
        begins to suffer one unsoakable level of bashing damage each
        time the Charm is used. This damage does not heal until the
        character stops using the Charm. Once a character ends use
        of Tireless Sentinel Technique, he cannot safely reactivate it
        until all damage from the Charm has been healed. Doing
        otherwise only continues the process of decay.
        "

    relentless_revenant_spirit[Relentless Revenant Spirit]
    tireless_sentinel_technique --> relentless_revenant_spirit
    click relentless_revenant_spirit callback "
        Relentless Revenant Spirit<br>
        <br>
        Cost: None<br>
        Duration: Permanent<br>
        Type: Special<br>
        Minimum Endurance: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Tireless Sentinel Technique<br>
        <br>
        Once an Abyssal learns this Charm, death itself
        cannot stop him. If slain, his spirit rises again as a ghost. He
        loses his Exaltation and its commiserate powers, but he
        gains the full advantages of unlife, retains the ability to use
        any supernatural martial-arts forms he may know up to and
        including the Form (but not more advanced techniques)
        and gains twice as many Arcanoi as a starting ghost. The
        Storyteller has final say on what Traits the character keeps
        and how many ghost Charms he can purchase, etc.
        "

    pain_eating_focus[Pain-Eating Focus]
    click pain_eating_focus callback "
        Pain-Eating Focus<br>
        <br>
        Cost: 1 mote<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Endurance: 1<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        More than any of the other Chosen, the Abyssal
        Exalted understand the power of suffering and hate. A
        character with this Charm may invoke it whenever she is
        struck in combat. For every die of pre-soak damage the
        attack inflicts, her player may roll one die. Each success on
        this roll restores 1 mote of Essence, up to the character’s
        usual limit. A character cannot harvest more Essence from
        a single attack than her Essence rating.
        "

    insensible_corpse_technique[Insensible Corpse Technique]
    pain_eating_focus --> insensible_corpse_technique
    click insensible_corpse_technique callback "
        Insensible Corpse Technique<br>
        <br>
        Cost: None/1 mote per -1<br>
        Duration: Permanent/one scene<br>
        Type: Special/Reflexive<br>
        Minimum Endurance: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Pain-Eating Focus<br>
        <br>
        Many Abyssal Exalted show disturbing indifference
        to suffering. When this Charm is purchased, the player
        must decide whether to permanently inure the Exalt
        against the worst of his pain or cultivate a more powerful
        numbing for short-term use. In the former case, the Exalt
        permanently subtracts 2 from all wound penalties. Such
        anesthetizing does not accelerate healing, so a -2 level
        reduced to -0 still regenerates as a -2. However, this
        penalty reduction is cumulative, so characters buying this
        Charm twice subtract 4 from their wound penalties. Once
        this Charm is purchased three times, the Exalt is thereafter
        immune to all but the most unimaginably terrible agony.
        In its configuration as a temporary anesthetic, this
        Charm allows characters to dampen pain with Essence.
        For every mote spent, the Exalt can ignore one die of
        wound penalties. This Charm can be used multiple times
        in a scene, with cumulative effect. Characters can even
        negate more dice of wound penalties than they currently
        suffer from in preparation for future injury. Exalted who
        know the temporary and permanent form of this Charm
        combine both effects when determining their final wound
        penalty reduction.
        "

    agony_savoring_spirit[Agony-Savoring Spirit]
    pain_eating_focus --> agony_savoring_spirit
    click agony_savoring_spirit callback "
        Agony-Savoring Spirit<br>
        <br>
        Cost: 1 Willpower<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Endurance: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Pain-Eating Focus<br>
        <br>
        Where an Abyssal with Pain-Eating Focus draws
        power from her own torment, a character with this Charm
        may feed on the suffering of others. A character can use
        this Charm whenever she slays an individual single-
        handedly. The Abyssal’s player rolls Conviction. Each
        success restores one point of Willpower.
        "
