---
config:
  theme: dark
---
flowchart TD

    summon_skeleton[Summon Skeleton]
    click summon_skeleton callback "
        Summon Skeleton<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Presence: 3<br>
        Minimum Essence: 3<br>
        Prerequisite: None<br>
        <br>
        The Abyssal Exalted channels her Essence into the
        ground beneath her feet. If a largely whole skeleton is in the
        vicinity, it claws its way from the ground and follows the
        orders of the Abyssal to the best of its limited Intelligence.
        See Exalted, page 298, for statistics of the walking dead.
        "
