---
config:
  theme: dark
---
flowchart LR

    dark_steed_mastery[Dark Steed Mastery]
    click dark_steed_mastery callback "
        Dark Steed Mastery<br>
        <br>
        Cost: 1 mote per die<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Conviction: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm is frequently taught to ghostly cavalry in
        the service of a Deathlord or another tyrant of the Underworld.
        Dark Steed Mastery allows a ghost to better control
        a ghostly mount. This Arcanos adds one die to the ghost’s
        Ride dice pools for every mote of Essence spent, to a
        maximum number of dice equal to his Essence. This
        Charm can only be used within the Underworld or a
        shadowland, unless the ghost uses Manifest the Dark Steed
        (see p. 41).
        "

    pole_the_black_depths[Pole the Black Depths]
    click pole_the_black_depths callback "
        Pole the Black Depths<br>
        <br>
        Cost: 1 mote per die<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Conviction: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm allows a ghost sailor to better fulfill his
        duties. The ghost who uses Pole the Black Depths gains
        one die to his Sail dice pools for every mote of Essence
        spent, to a maximum number of dice equal to his Essence.
        This Charm can only be used within the Underworld or a
        shadowland, unless the ghost is on the crew of a boat
        manifested through the use of Conjure the Defeated Vessel
        or Sunken Admiral Technique (see p. 41-42).
        "

    scent_of_sweet_blood[Scent of Sweet Blood]
    click scent_of_sweet_blood callback "
        Scent of Sweet Blood<br>
        <br>
        Cost: 1 mote<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Compassion: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This simple Charm allows a ghost to smell spilled
        blood or bleeding wounds at a range of one mile per dot of
        Essence. The blood does not have to be particularly fresh,
        but it should be from a mortal or Exalt — animal blood is
        only sensed at half the range that mortal or Exalt blood can
        be smelled. The ghost learns the direction of and distance
        to the blood. Unusually large amounts — say, more than
        a human body’s worth — may be detected at as far away as
        five miles per dot of Essence, and strong wind currents or
        other intense weather may interfere with this ability.
        "

    moons_cold_glow[Moon's Cold Glow]
    click moons_cold_glow callback "
        Moon's Cold Glow<br>
        <br>
        Cost: 2 motes<br>
        Duration: One night per success<br>
        Type: Simple<br>
        Minimum Conviction: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The Underworld is gloomy and dark even on its
        brightest mornings. This simple art allows a ghost to pierce
        the natural darkness of the Underworld. If there is no
        precipitation or fog, double the distance for both Clear
        Vision and Murky Vision for the ghost, to a maximum of
        100 yards (see Exalted, p. 237). Roll Perception + Conviction.
        Success means that the ghost can see normally until
        the following dawn, and each additional success adds 24
        hours to the duration from that point.
        "

    whispers_of_the_living[Whispers of the Living]
    click whispers_of_the_living callback "
        Whispers of the Living<br>
        <br>
        Cost: 3 motes<br>
        Duration: One minute per success<br>
        Type: Simple<br>
        Minimum Conviction: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        The Underworld is itself a dark reflection of Creation,
        and every point in the Underworld corresponds to a
        particular space in Creation. This Arcanos allows the
        ghost to hear the living world as though she was standing
        in the equivalent spot to her current location in the
        Underworld. A Perception + Occult roll activates the
        Charm, and the ghost can listen for one minute per
        success. A botch on this roll allows any living being in that
        same location to hear unearthly whispers and winds,
        giving away these strange goings-on. Whispers of the
        Living only works at night. As with Two World Vision,
        Whispers of the Living does not allow a ghost to listen in
        from Creation into the Underworld.
        "


    pyre_smoke_form[Pyre Smoke Form]
    click pyre_smoke_form callback "
        Pyre Smoke Form<br>
        <br>
        Cost: 2 motes<br>
        Duration: One turn per success<br>
        Type: Simple<br>
        Minimum Temperance: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        With Pyre Smoke Form, a ghost may become incorporeal
        even in environments where he would ordinarily be
        manifest — in the Underworld, for instance, or in a
        shadowland during Calibration. Using this Arcanos requires
        a Stamina + Temperance roll, and each success
        allows one turn of incorporeality.
        "

    breeze_carried_ash_form[Breeze-Carried Ash Form]
    pyre_smoke_form --> breeze_carried_ash_form
    click breeze_carried_ash_form callback "
        Breeze-Carried Ash Form<br>
        <br>
        Cost: 5 motes<br>
        Duration: One turn per success<br>
        Type: Simple<br>
        Minimum Conviction: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Pyre Smoke Form<br>
        <br>
        Breeze-Carried Ash Form allows a ghost to fly through
        the air at any speed up to his maximum running pace, so
        long as he is incorporeal as he does so (this Charm is
        primarily effective only in the land of the living). His
        player must make a Dexterity + Athletics roll, and each
        success allows one turn of flight. If the ghost is above
        ground level when the Charm expires, he falls toward the
        ground as though solid. He does not take any damage from
        the fall, however, because he must be incorporeal to use
        this Arcanos.
        "

    two_world_vision[Two-World Vision]
    click two_world_vision callback "
        Two-World Vision<br>
        <br>
        Cost: 2 motes<br>
        Duration: One turn per success<br>
        Type: Simple<br>
        Minimum Conviction: 1<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Every spot in the Underworld has an analog within
        Creation proper — the lands of the dead are simply a dark
        mirror to the lands above. With this Charm, a ghost can
        glance from his location in the Underworld at the corresponding
        space in Creation. A Perception + Occult roll
        suffices to activate the Charm and provides one turn of
        vision per success. Two World Vision only works at night.
        This Arcanos doesn’t work both ways. Even if the ghost
        finds himself in the living
        "

    assassins_subtle_escape[Assassin's Subtle Escape]
    click assassins_subtle_escape callback "
        Assassin's Subtle Escape<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One hour per success<br>
        Type: Simple<br>
        Minimum Temperance: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Assassin’s Subtle Escape allows a ghost to tempo-
        rarily inhabit a mundane object in the living world. The
        ghost simply lays his hand upon the object, and his
        physical essence is absorbed into the thing. The ghost’s
        presence cannot be detected by mundane means, though
        Charms such as Superior Sight Focus (see Exalted: The
        Abyssals, p. 205) allow others to detect him. While
        inhabiting an object, the ghost cannot be directly harmed.
        Damage to the object does not harm the inhabiting
        ghost, but the item’s destruction by fire, pulverization or
        magic sends the ghost to Lethe. The ghost’s player must
        succeed in a Manipulation + Crafts roll for the ghost to
        successfully inhabit the object, and he remains within it
        for up to one hour per success or until he decides to leave
        — note that once the ghost leaves the object the Charm
        expires. The ghost may expend an additional 5 motes and
        a point of Willpower in order for his player to reroll his
        duration at any time. However, the new duration of the
        Charm is measured from the new expenditure and roll
        (rather than being tacked onto the end of the existing use
        of the Charm).<br>
        Assassin’s Subtle Escape does not allow a ghost resid-
        ing in an object to animate the object in any fashion. He
        is only a passenger. Only one ghost can reside in a given
        object at a time.
        "

    motivated_shell[Motivated Shell]
    assassins_subtle_escape --> motivated_shell
    click motivated_shell callback "
        Motivated Shell<br>
        <br>
        Cost: 8 motes + 1 Willpower<br>
        Duration: One turn per success<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Assassin’s Subtle Escape<br>
        <br>
        Motivated Shell can only be activated once a ghost
        inhabits an object through Assassin’s Subtle Escape
        (above). This Arcanos enables the ghost to control the
        motions of an object he inhabits. The motions must be
        the sorts of things that the object could ordinarily do or
        be made to do by hand. A door swings open or closed; a
        lock turns or opens; a cart’s wheels roll on their own. The
        ghost’s player rolls Manipulation + Craft, and each success
        allows the ghost to control the object’s ordinary
        movements for one turn.
        "

    ride_the_mystic_vessel[Ride the Mystic Vessel]
    assassins_subtle_escape --> ride_the_mystic_vessel
    click ride_the_mystic_vessel callback "
        Ride the Mystic Vessel<br>
        <br>
        Cost: 3 motes<br>
        Duration: One turn<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Assassin’s Subtle Escape<br>
        <br>
        This Charm allows the ghost to use Assassin’s Subtle
        Escape to inhabit an object made of the Five Magical
        Materials. Ride the Mystic Vessel does not allow the ghost
        to inhabit highly enchanted items (those requiring Arti-
        fact •• or higher) unless those items are made of soulsteel
        or jade. Even then, the ghost cannot inhabit an item if it
        is Artifact •••• or above or attuned to an Exalt.
        Ghosts cannot combine Arcanoi into Combos, so
        this Arcanos cannot be activated simultaneously with
        Assassin’s Subtle Escape. Instead, the ghost must activate
        Ride the Mystic Vessel and then, the following
        turn, activate Assassin’s Subtle Escape and enter the
        object in question.
        "

    angry_trickster_ghost_method[Angry Trickster Ghost Method]
    two_world_vision --> angry_trickster_ghost_method
    assassins_subtle_escape --> angry_trickster_ghost_method
    click angry_trickster_ghost_method callback "
        Angry Trickster Ghost Method<br>
        <br>
        Cost: 5 motes<br>
        Duration: Three turns<br>
        Type: Simple<br>
        Minimum Conviction: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Two World Vision, Assassin’s Subtle Escape<br>
        <br>
        This Arcanos allows an angry ghost to harness his rage
        into a storm of flying objects in Creation. This storm will
        injure any unarmored beings caught within it, and it does
        not differentiate between friend and foe. The ghost’s
        player rolls Conviction + Melee. Every success increases
        the diameter of the storm by five yards. The storm hurts
        those caught in the area. It deals four dice of lethal damage
        if the objects used are sharp and hard and four dice of
        bashing damage otherwise (with successes adding to this
        damage). An entity caught within the storm of objects can
        defend against it normally.
        "

    former_life_destruction_technique[Former Life Destruction Technique]
    click former_life_destruction_technique callback "
        Former Life Destruction Technique<br>
        <br>
        Cost: None<br>
        Duration: Permanent<br>
        Type: Special<br>
        Minimum Temperance: 4<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: None<br>
        <br>
        This art — one of the few introduced to ghostly
        society by the Deathlords — replicates the Abyssal Exaltation
        in that it allows a ghost to hide his true name from
        Creation. The ghost hides his name behind a title or an
        obviously false name and can never speak or respond to his
        true name. In return, the character receives an additional
        three dice to resist any sorcery or necromancy that relies on
        his name or identity. It does not protect him against line-of-sight
        magical attacks, however — the character’s identity
        as “Mavis Karan” is protected, not his identity as “third guy
        from the left at that table.”
        "
