---
config:
  theme: dark
---
flowchart TD

    courier_in_dreams[Courier in Dreams]
    click courier_in_dreams callback "
        Courier in Dreams<br>
        <br>
        Cost: 2 motes<br>
        Duration: 50 words<br>
        Type: Simple<br>
        Minimum Compassion: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        With this Arcanos, a ghost can send a message to a
        living being through dreams. The ghost can perform this
        Charm from the Underworld, a shadowland or Creation,
        and send the message to a subject anywhere in Creation.
        The message travels instantaneously to the subject’s cur-
        rent location. However, the subject does not receive the
        message until the next time he sleeps (and if that is more
        than eight hours away, the subject does not receive the
        message at all). The ghost may speak up to 50 words to the
        subject, who sees the Charm’s effect as the ghost standing
        and speaking the words to him. This Arcanos does not
        allow for two-way communication — the subject receives
        the ghost’s message but may not send a reply.
        "

    honorable_descendant_blessing[Honorable Descendant Blessing]
    courier_in_dreams --> honorable_descendant_blessing
    click honorable_descendant_blessing callback "
        Honorable Descendant Blessing<br>
        <br>
        Cost: 5 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Compassion: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Courier in Dreams<br>
        <br>
        A ghost can use this Arcanos to send a minor blessing to
        an appropriately pious living descendant. The ghost simply
        speaks the descendant’s name aloud, pictures him and spends
        the necessary Essence, and the subject of the Charm immediately
        receives a three-dice bonus pool that can be used to
        supplement any action at any time in the next day. As the
        Arcanos takes effect, the subject feels a pleasant surge of
        energy and good fortune. These dice can only be used once —
        after the subject of the Charm uses the bonus dice, they are
        gone. This Charm only works on living mortals and Exalts
        who can trace a line of blood descent from the ghost.
        "

    dishonorable_descendant_curse[Dishonorable Descendant Curse]
    courier_in_dreams --> dishonorable_descendant_curse
    click dishonorable_descendant_curse callback "
        Dishonorable Descendant Curse<br>
        <br>
        Cost: 6 motes<br>
        Duration: One hour per success<br>
        Type: Simple<br>
        Minimum Compassion: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Courier in Dreams<br>
        <br>
        This Arcanos is, in most ways, the opposite of Honorable
        Descendant Blessing. It can only be used on living
        mortals and Exalts who trace a line of blood descent from
        the ghost. It works at any range, however. The ghost must
        simply visualize the target and state his name aloud, and
        the subject feels a dull, throbbing pain throughout the
        duration of the Charm. While the curse is active, the
        subject loses one die from all dice pools. Spend the necessary
        Essence, and roll Compassion + Lore. For every
        success, the curse lasts one hour. The ghost who activates
        the Arcanos may dismiss the curse at any time.
        "
