---
config:
  theme: dark
---
flowchart TD

    taste_the_demon_wind[Taste the Demon Wind]
    click taste_the_demon_wind callback "
        Taste the Demon Wind<br>
        <br>
        Cost: 2 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Valor: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        One of the most common hazards of ghostly existence
        are roving packs of hungry ghosts. Mindless and driven by
        inhuman appetites, they roam the across the worlds, constantly
        searching for prey, living or otherwise. As such, it
        behooves a clever ghost to be aware of these potential
        hazards, and Taste the Demon Wind allows a ghost to do
        exactly that.<br>
        When a ghost uses this power, a successful roll of
        Perception + Presence renders her aware of the number,
        direction and location of any hungry ghosts in the vicinity.
        The more successes rolled, the further out hungry ghosts
        can be detected.<br>
        <br>
        Number of Range Successes<br>
        1 100 yards<br>
        2 250 yards<br>
        3 500 meters<br>
        4 1 mile<br>
        5 5 miles<br>
        <br>
        Taste the Demon Wind must be used consciously. The
        ghost must be actively listening for hungry ghosts, or else,
        this Arcanos is useless. The way in which the power manifests
        varies from spirit to spirit. Some detect hungry ghosts
        as a foul odor or a sudden chill, while others claim to be able
        to suddenly hear their howling, even from great distances.<br>
        Once a ghost has detected a hungry ghost, she is then
        aware of its location at all times until it leaves her range.
        Hungry ghosts are not aware they’ve been found out, nor
        are they usually clever enough to lope outside of range and
        then return, undetected.
        "

    call_the_ravening_hound[Call the Ravening Hound]
    taste_the_demon_wind --> call_the_ravening_hound
    click call_the_ravening_hound callback "
        Call the Ravening Hound<br>
        <br>
        Cost: 8 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Taste the Demon Wind<br>
        <br>
        Summoning a hungry ghost — or a pack of them — is
        not the brightest thing a ghost can do. However, there are
        times when it makes sense to do so. The arrival of a pack
        of hungry ghosts can provide excellent cover for an escape,
        and some of the more advanced Arcanoi also provide uses
        for hungry ghosts that arrive.<br>
        The use of Call the Ravening Hound requires a
        successful Manipulation + Presence roll. The more successes
        scored, the further away the hungry ghosts may be
        that are summoned (and the more who are likely to heed
        the call). Bear in mind, however, that if one hungry ghost
        suddenly bolts in response to a summons, the rest of his
        pack may follow of its own volition.<br>
        <br>
        Number of Successes Range Maximum Number of Hungry Ghosts Called<br>
        1 100 yards 250 yards 1<br>
        2 250 yards 2<br>
        3 500 yards 4<br>
        4 1 mile 8<br>
        5 5 miles 20<br>
        <br>
        When a ghost uses this power successfully, a cold,
        unearthly shrieking rises up from where he is standing.
        This radiates outward to the limits of the Arcanos’
        effective range. Any hungry ghosts within the range will
        howl in response, and the nearest to the summoning
        ghost will respond. This initial call is very distinctive,
        and those who are familiar with the use of the Arcanos
        will be able to recognize it for what it is. This practice is
        highly illegal in civilized portions of the Underworld.
        Those caught using Call the Ravening Hound face enslavement
        or worse as punishment for deliberately
        attracting the scourge of hungry ghosts.
        "

    relentless_hunters_mark[Relentless Hunter's Mark]
    call_the_ravening_hound --> relentless_hunters_mark
    click relentless_hunters_mark callback "
        Relentless Hunter's Mark<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One hour<br>
        Type: Simple<br>
        Minimum Valor: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Call the Ravening Hound<br>
        <br>
        Hungry ghosts are relentless, savage hunters. This is why
        many ghosts find it useful to unleash them on their enemies.
        Placing the Relentless Hunter’s Mark on a victim immediately
        makes that individual the center of attention for any
        hungry ghost in the vicinity, as well as any he stumbles across
        while the Mark endures. A pale white handprint outlined in
        angry red, the Mark calls hungry ghosts to itself like raw meat
        calls hungry dogs, and it whips those hungry ghosts into a
        frenzy of anger against the Mark’s bearer.<br>
        The Mark can be placed on an individual or on an
        item such as a breastplate or weapon. To place the Relent-
        less Hunter’s Mark, a ghost’s player must make a successful
        Dexterity + Brawl roll for his character to touch the target,
        then succeed on a Manipulation + Presence roll (difficulty
        2). The Mark then remains in place on the target for an
        hour, highly visible to all. Hungry ghosts will react to the
        Mark immediately and will pursue the victim relentlessly
        until either they or their target is brought down. Once the
        Mark fades, hungry ghosts will no longer be unnaturally
        drawn to the character, but if they’re already hunting her,
        they won’t suddenly stop.<br>
        While the basic Mark fades after an hour, some ghosts
        are skilled at prolonging its effects. The expenditure of a
        single experience point when placing the Relentless
        Hunter’s Mark on a target seals it in place for a year and a
        day. Spending 2 makes it permanent.
        "

    diversion_of_the_savage_hunger[Diversion of the Savage Hunger]
    call_the_ravening_hound --> diversion_of_the_savage_hunger
    click diversion_of_the_savage_hunger callback "
        Diversion of the Savage Hunger<br>
        <br>
        Cost: 12 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Call the Ravening Hound<br>
        <br>
        The flip side of detecting the location of a nearby
        hungry ghost is preventing it from detecting you. While
        ghosts of power can deal with even a pack of hungry ghosts
        with minimal risk of destruction, not every restless spirit is
        so capable. Even those who can put down a hungry ghost
        should the situation require it often prefer to avoid any
        confrontation on general principle.<br>
        With that in mind, many ghosts become skilled in the
        exercise of Diversion of the Savage Hunger. The successful
        use of this Arcanos effectively removes a ghost from the
        perception of any nearby hungry ghosts. A successful
        Perception + Presence roll is required (difficulty 2), but
        once success is achieved, the hungry ghost or ghosts are no
        longer a problem — a single successful use hides a ghost
        from all hungry ghosts until the end of the scene. Any
        attack on the hungry ghosts or otherwise ostentatious
        display of the hiding ghost’s presence negates the effect of
        Diversion of the Savage Hunger and leaves the ghost
        vulnerable to attack once again.
        "

    tame_the_wicked_appetite[Tame the Wicked Appetite]
    diversion_of_the_savage_hunger --> tame_the_wicked_appetite
    click tame_the_wicked_appetite callback "
        Tame the Wicked Appetite<br>
        <br>
        Cost: 8 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 2<br>
        PrerequisiteCharms: Diversion of the Savage Hunger<br>
        <br>
        Tame the Wicked Appetite does exactly what its
        name suggests: It soothes the driving passion of hungry
        ghosts, rendering them passive and calm. Hungry ghosts
        that are affected will simply lay down in their tracks or
        wander around dazed. If attacked, they will return to their
        customary savagery, but if not attacked, they will be dull
        and passive until the Arcanos’ power wears off. They will
        not even resist attempts to chain or muzzle them, though
        once they feel their bonds they may become more violent.<br>
        Using Tame the Wicked Appetite requires a roll of
        Charisma + Presence. The more successes obtained, the
        more hungry ghosts that can be dealt with. Any hungry
        ghost struck by the usage of Tame the Wicked Appetite
        will fall prey to it immediately, whether it is wandering the
        shadowlands or in mid-pounce. This Charm has a maximum
        range of (the ghost’s Valor x 10) yards.<br>
        <br>
        Number of Successes Number of Hungry Ghosts Tamed<br>
        1 1<br>
        2 3<br>
        3 5<br>
        4 10<br>
        5 20<br>
        <br>
        The hungry ghosts’ hunger remains sated for the
        duration of a single scene, though for the cost of another
        mote of Essence, the ghost using the Arcanos can extend
        the effect for an hour. Furthermore, by spending an experience
        point, the ghost can make the effect permanent,
        rendering the affected hungry ghosts permanently deprived
        of their appetites. This expenditure releases any
        Essence committed to the Charm.
        "

    command_the_hungry_devil[Command the Hungry Devil]
    call_the_ravening_hound --> command_the_hungry_devil
    click command_the_hungry_devil callback "
        Command the Hungry Devil<br>
        <br>
        Cost: 8 motes, 1 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Call the Ravening Hound<br>
        <br>
        There are times when it is not enough to divert a
        hungry ghost. Occasionally, it is useful to harness the
        ravening power of a hungry ghost to one’s own ends. Thus
        was developed the ability to Command the Hungry Devil.
        This Arcanos allows a ghost to issue a single, irresistible
        command to a hungry ghost. The command itself must be
        obeyed to the letter and to the best of the hungry ghost’s
        ability, even if it leads to swift destruction.<br>
        To Command the Hungry Devil requires a successful
        Manipulation + Presence roll, difficulty 2. The more successes
        achieved, the more hungry ghosts can be commanded.<br>
        <br>
        Number of Successes Number of Hungry Ghosts Commanded<br>
        1 1<br>
        2 3<br>
        3 5<br>
        4 10<br>
        5 20<br>
        <br>
        The command need not be a single word, as a relatively
        simple sentence can be understood by a hungry
        ghost. “Stop” is a perfectly acceptable use of Command the
        Hungry Devil, with the understanding that the hungry
        ghost is free to start again a moment later. More effective
        are commands such as “Attack him!” or “Go back to the
        corpse that spawned you!” On the other hand, any ghost
        who issues a complex command such as “Invade the Prince
        of Shadows’ citadel and bring me his left-handed gauntlet”
        is going to be disappointed. If the order given is too
        complex, the target ghost will remain motionless for a turn
        and then resume its former attitude. Hungry ghosts will,
        however, attempt to fulfill impossible commands, so long
        as they are simple enough to be understood.
        "

    dust_commands_litany[Dust Commands Litany]
    command_the_hungry_devil --> dust_commands_litany
    click dust_commands_litany callback "
        Dust Commands Litany<br>
        <br>
        Cost: 12 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Command the Hungry Devil<br>
        <br>
        Dust Commands Litany is an extension of the power
        of Command the Hungry Devil. Rather than a single
        command, however, it grants mastery over the hungry
        ghost for an entire scene. Furthermore, it can be extended
        for an additional scene by an additional mote’s expenditure.
        Dust Commands Litany is useful for ghosts who keep
        penned herds of hungry ghosts or who employ the beasts as
        watchdogs and the like.
        "

    ghostly_harness_exercise[Ghostly Harness Exercise]
    tame_the_wicked_appetite --> ghostly_harness_exercise
    command_the_hungry_devil --> ghostly_harness_exercise
    click ghostly_harness_exercise callback "
        Ghostly Harness Exercise<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One month<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Tame the Wicked Appetite, Command the Hungry Devil<br>
        <br>
        There are some among the dead who devote their
        existence to dealing with the scourge of hungry ghosts in
        a most unusual fashion — by taming them. These spirits
        are masters of Ghostly Harness Exercise, which allows
        them to soothe hungry ghosts’ savage nature for extended
        periods of time. While hungry ghosts marked by this
        power maintain their capacity for savagery, they are no
        longer constantly ravenous and can be trained. They
        even form a bond of sorts with the ghost who tames them,
        and so long as they are tamed, they will not attack him
        under any circumstances. This includes while under the
        influence of Command the Hungry Devil. Of course, the
        hungry ghost trainer must keep his end of the bargain,
        taking care of his charges, spending time with them and
        feeding them appropriately.<br>
        Hungry ghosts tamed with this power can be used as
        watchdogs or bodyguards. Some ghosts use them as fight-
        ing animals in tournaments and underground betting pits,
        but most feel that this is an unnecessary expense. Without
        the effects of Ghostly Harness Exercise, the task of training
        a hungry ghost is utterly impossible. Even with the Charm,
        training is a time-consuming process and requires a month
        of intense work with harness, whip and fist. However, once
        the hungry ghost has been trained, it is trained forever.<br>
        Tamed hungry ghosts function in much the same way
        trained hounds do for mortals, obeying simple commands,
        leaping to their owners’ defense and eagerly awaiting the
        chance to hunt.
        "

    spirit_handling_leash[Spirit Handling Leash]
    ghostly_harness_exercise --> spirit_handling_leash
    click spirit_handling_leash callback "
        Spirit Handling Leash<br>
        <br>
        Cost: 5 motes, 2 Willpower<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Ghostly Harness Exercise<br>
        <br>
        Spirit-Handling Leash is not nearly so powerful as its
        prerequisite. It does, however, have one virtue that Ghostly
        Harness Exercise lacks: versatility. It allows a trainer to
        transfer a tamed hungry ghost’s loyalty to a new owner,
        quickly, easily and permanently. The trainer is still regarded
        with some, for lack of a better term, affection, but
        it is to its new owner that the hungry ghost now shows its
        utter devotion. The Spirit-Handling Leash will remain in
        place permanently, and the hungry ghost whose affections
        have been transferred will regard its owner with the same
        affection it once gave its trainer. The hungry ghost will
        hunt, guard or attack at its owner’s command and will
        never attack the holder of the Spirit-Handling Leash. It is
        not uncommon to see servants of wealthy and noble ghosts
        walking the streets of the necropoli with leashed packs of
        hungry ghosts snuffling out ahead of them, a plain symbol
        of their power for all to see.
        "
