---
config:
  theme: dark
---
flowchart TD

    hide_of_the_cunning_hunter[🌙 Hide of the Cunning Hunter]
    click hide_of_the_cunning_hunter callback "
        Hide of the Cunning Hunter<br>
        <br>
        Cost: 1 mote<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Manipulation: 1<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        This Charm is often one of the first that young
        Lunars learn. It allows the Lunar to suppress his tattoos,
        causing them to become invisible. The effects of this
        Charm dissipate if the Lunar's Tell becomes visible due
        to his anima banner reaching or exceeding the 4-7
        motes level of anima display. Otherwise, it is impossible
        to detect the Lunar's tattoos — even forms of sight that
        allow the perception of active Essence will not see the
        effects of the Charm. Storytellers should assume that
        individuals who see a Lunar with unsuppressed tattoos
        will always regard the Lunar suspiciously for the purposes
        of perceiving his Tell, and most will immediately
        realize the character's nature. The Lunar Anathema
        are, after all, the stuff of legend.
        "

    masking_the_brilliant_form[🌙 Masking the Brilliant Form]
    hide_of_the_cunning_hunter --> masking_the_brilliant_form
    click masking_the_brilliant_form callback "
        Masking the Brilliant Form<br>
        <br>
        Cost: 3 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Manipulation: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Hide of the Cunning Hunter
        <br>
        This Charm makes it harder to perceive the
        Lunar's Tell. While this Charm is active, it is impossible
        to detect the Tell of a Lunar who has never
        purchased Deadly Beastman Transformation. While
        this Charm is active, Lunars who have purchased
        Deadly Beastman Transformation 1-2 times are treated
        as if they had never purchased it for the purposes of
        having their Tells spotted. Lunars who have pur-
        chased Deadly Beastman Transformation 3 or more
        times are treated as if they purchased it 1-2 times for
        the purposes of spotting their Tells. This Charm
        cannot suppress the character's Tell at the 4-7 motes
        level of anima banner display, and its effects end if the
        character's anima becomes that intense.
        "
