---
config:
  theme: dark
---
flowchart LR

    beast_instinct_method["🌑 Beast Instinct Method"]
    click beast_instinct_method callback "
        Beast Instinct Method<br>
        <br>
        Cost: 2 motes per die<br>
        Duration: Instant<br>
        Type: Supplemental<br>
        Minimum Wits: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        A Lunar's ties to the wild allow him to survive in
        conditions where others would suffer great hardship. By
        using this Charm, the Lunar taps into his bestial nature,
        using instinct and cunning rather than rational thought
        to guide his actions. When attempting any form of
        Survival roll that involves Wits, the Lunar's player may
        purchase additional dice up to his character's unmodified
        Wits score.
        "

    whale_breath_technique["🌕 Whale-Breath Technique"]
    beast_instinct_method --> whale_breath_technique
    click whale_breath_technique callback "
        Whale-Breath Technique<br>
        <br>
        Cost: 3 motes<br>
        Duration: Stamina x 10 minutes<br>
        Type: Simple<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        Using this Charm, a Lunar replicates the breath
        control of a diving whale and need not breath for a
        considerable period of time (Stamina x 10 minutes). The
        Lunar can survive underwater, in poison gas or even
        where there's no air at all. However, the Lunar cannot
        speak without compromising the effects of the Charm —
        doing so requires him to expel air from his lungs. The
        Lunar may speak a few words, perhaps a short sentence,
        but if he does so, the duration of the Charm decreases to
        one minute. If he speaks a longer sentence or speaks
        again, the duration decreases to five turns. A third
        attempt at speech or any form of longer communication
        cancels the Charm. As part of activating the Charm, the
        Lunar must take a deep breath and so cannot simply
        reactivate it in hostile conditions.
        "

    gill_breathing_technique["🌙 Gill-Breathing Technique"]
    whale_breath_technique --> gill_breathing_technique
    click gill_breathing_technique callback "
        Gill-Breathing Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: One day<br>
        Type: Reflexive<br>
        Minimum Manipulation: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Whale-Breath Technique<br>
        <br>
        By activating this Charm, the Lunar manipulates
        his body to form gills. This allows him to breath as well
        in water as in air for the rest of the day. A character
        existing underwater may simply commit 5 motes to this
        Charm to keep gills indefinitely.
        "

    sealskin_endurance["🌕 Sealskin Endurance"]
    beast_instinct_method --> sealskin_endurance
    click sealskin_endurance callback "
        Sealskin Endurance<br>
        <br>
        Cost: 4 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        By activating this Charm, the Lunar protects himself
        from cold conditions. The exact method differs from
        Lunar to Lunar — some may grow a layer of blubber,
        others a pelt of warm fur. Regardless, the effects are the
        same. For the duration of the Charm, the Lunar can exist
        in relative comfort even in the coldest conditions. He
        does not suffer from hypothermia, frostbite or immersion,
        nor does he suffer the effects of snow blindness.
        He is not, however, protected from the harshest
        rigors of the Elemental Poles, nor from magically
        conjured cold.
        "

    heat_adapting_method["🌕 Heat-Adapting Method"]
    beast_instinct_method --> heat_adapting_method
    click heat_adapting_method callback "
        Heat-Adapting Method<br>
        <br>
        Cost: 4 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        This Charm has the opposite effect of Sealskin
        Endurance, resulting in a lean, sleek Lunar adapted to
        the rigors of warm environments. His body becomes
        highly efficient at conserving water and adept at
        radiating excess heat without the need for sweating.
        For the duration of the Charm, the Lunar can exist in
        relative comfort in even the warmest conditions. He
        does not suffer heatstroke or sand blindness, nor does
        his skin blister and burn after exposure to the sun. The
        Heat Adapting Method does not protect the Lunar
        from the effects of fire.
        "

    fire_walking_prana["🌕 Fire-Walking Prana"]
    heat_adapting_method --> fire_walking_prana
    click fire_walking_prana callback "
        Fire-Walking Prana<br>
        <br>
        Cost: 5 motes<br>
        Duration: 10 turns<br>
        Type: Simple<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Heat Adapting Method<br>
        <br>
        By means of this Charm, the Lunar can — for a
        short time — resist the effects of fire. He may walk
        through flames and across burning coals without
        suffering ill effects. He is not, however, immune to
        the effects of prolonged heat. The character adds his
        Essence to his soak against magical fire. While under
        the protection of this Charm, the character is also
        immune to the effects of smoke inhalation and to
        overheating caused by exposure to flames.
        "

    unerring_den_finding_sense["🌑 Unerring Den-Finding Sense"]
    beast_instinct_method --> unerring_den_finding_sense
    click unerring_den_finding_sense callback "
        Unerring Den-Finding Sense<br>
        <br>
        Cost: 4 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Perception: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        Using this Charm, a Lunar can unerringly find
        shelter for himself and a number of associates. The
        exact sort of shelter will depend on the environment
        — in rocky terrain, the Lunar's senses may lead him
        to a cave or cleft, while, in a forest, he may divine a
        hollow tree of suitable size. The Lunar's player makes
        a Perception + Survival roll, each success indicating
        capacity for one person, irrespective of the environmental
        conditions. However, this protection merely shields
        the characters from the elements — it does not guarantee
        there is firewood or food in the vicinity.
        "

    food_scenting_method["🌕 Food-Scenting Method"]
    beast_instinct_method --> food_scenting_method
    click food_scenting_method callback "
        Food-Scenting Method<br>
        <br>
        Cost: 4 motes<br>
        Duration: Varies<br>
        Type: Simple<br>
        Minimum Perception: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        By using this Charm, a Lunar will never go hungry.
        If he is traveling during the day in hospitable terrain,
        the Lunar is guaranteed to find enough nuts, berries,
        ants and fungi to keep him well fed. If he actively
        forages for food (see Exalted, p. 245), he may gather
        sufficient food to feed a number of people equal to his
        Perception + Survival, though doing so will take
        approximately an hour of his time. In harsher environments,
        the Lunar is still able to feed himself, though
        the Storyteller may wish the Lunar's player to roll his
        character's Perception + Survival, perhaps even at an
        increased difficulty level, to determine how many
        people he can feed. In no case should the difficulty
        increase above 3 unless the Lunar is stranded on pack
        ice, in the midst of a vast loose-sand desert or in some
        other wildly hostile environment.
        "

    water_providing_technique["🌑 Water-Providing Technique"]
    beast_instinct_method --> water_providing_technique
    click water_providing_technique callback "
        Water-Providing Technique<br>
        <br>
        Cost: 5 motes<br>
        Duration: Varies<br>
        Type: Simple<br>
        Minimum Perception: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Beast Instinct Method<br>
        <br>
        Using this Charm, a Lunar can find sufficient water
        to meet his needs for a day. This moisture may be from
        concealed springs, condensation on leaves or the pulp of
        vegetation. Lunars in dire straits have gathered the film of
        moisture from around individual grains of sand, so sensitive
        are their tongues. If the Exalt seeks water for others,
        he may gather sufficient moisture to meet the needs of a
        number of people equal to his Perception + Survival,
        though harsh conditions may require his player to roll
        against a difficulty depending on the circumstances, each
        success indicating sufficient water for a person. Finding
        water takes 30 minutes per person (including the Lunar),
        and as with the Food-Scenting Method above, the difficulty
        of the roll to find water should never rise above 3.
        "

    wolf_endurance_method["🌕 Wolf-Endurance Method"]
    food_scenting_method --> wolf_endurance_method
    water_providing_technique --> wolf_endurance_method
    click wolf_endurance_method callback "
        Wolf-Endurance Method<br>
        <br>
        Cost: 6 motes<br>
        Duration: Until released<br>
        Type: Simple<br>
        Minimum Stamina: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Food-Scenting Method, Water-Providing Technique<br>
        <br>
        Many wild beasts can go for days without nourishment,
        and the Wolf Endurance Method allows the Lunar
        Exalted to do likewise. On a day that the Charm is active,
        the Lunar does not need to eat or drink and does not
        suffer any hunger pangs. Unfortunately, while Essence
        can support the body for a short while, it is very inefficient
        at powering the metabolism of an Exalted. As a
        result, the Wolf Endurance Method can be used for a
        number of weeks equal to the character's Stamina. After
        that point, the Lunar must temporarily loose a point of
        Strength or Stamina for each additional week. Attribute
        points lost in this manner cannot be recovered until the
        Charm is discontinued and the character has had several
        square and nutritious meals.
        "

    bear_sleep_technique["🌕 Bear-Sleep Technique"]
    wolf_endurance_method --> bear_sleep_technique
    click bear_sleep_technique callback "
        Bear-Sleep Technique<br>
        <br>
        Cost: 3 motes, 1 Stamina<br>
        Duration: 1 month<br>
        Type: Simple<br>
        Minimum Stamina: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wolf Endurance Method<br>
        <br>
        By activating this Charm, the Lunar can place
        himself in a deep sleep, during which time he need not
        eat and drink. Instead, Essence and body fat reserves
        sustain the Lunar. The character may place himself in
        this hibernation for a number of months up to his
        Stamina score, paying 3 motes of Essence and 1 point of
        temporary Stamina to maintain his body during this
        time. However long he sleeps, the Lunar will be ravenous
        upon waking. The Lunar must have a solid meal within
        24 hours of waking, or else, he loses an additional point
        of Stamina each day until he does. The Wolf Endurance
        Method cannot offset this Stamina loss — after hibernating,
        the Lunar is beyond mere hunger. If his Stamina
        declines to 0, the Lunar dies. Every day after waking
        during which he eats properly allows the character to
        recover one of the points of Stamina (including the one
        spent when activating the Charm).
        "

    fortitude_of_the_aurochs["🌕 Fortitude of the Aurochs"]
    wolf_endurance_method --> fortitude_of_the_aurochs
    click fortitude_of_the_aurochs callback "
        Fortitude of the Aurochs<br>
        <br>
        Cost: 10 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Stamina: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Wolf Endurance Method<br>
        <br>
        Constant activity places a great strain on the body,
        and even Exalts become fatigued after prolonged activity.
        By using Fortitude of the Aurochs, a Lunar can
        reinvigorate his body with Essence, manipulating the
        muscles and blood of his body to allow him to remain
        active. With this Charm in use, a Lunar can work for 24
        hours without worry of fatigue, nor can he become
        fatigued as a result of Charms, sorcery or other effects.
        Fortitude of the Aurochs does not eliminate any penalties
        already in effect as a result of fatigue, nor does it
        negate the need for sleep, only weariness from labor.
        Fortitude of the Aurochs also negates the need to make
        fatigue rolls for wearing armor, irrespective of environmental
        conditions.
        "

    ever_waking_method["🌕 Ever-Waking Method"]
    wolf_endurance_method --> ever_waking_method
    click ever_waking_method callback "
        Ever-Waking Method<br>
        <br>
        Cost: 3 motes<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Wolf Endurance Method<br>
        <br>
        By using Essence to reinvigorate his limbs, a Lunar
        can go for 24 hours without sleep and suffer no penalties
        (see Exalted, p. 241, for the normal penalties). He
        remains fully alert during this time and can keep acting,
        though the Charm does nothing to alleviate the symptoms
        of fatigue. The character can activate this Charm
        every day, but doing so for a prolonged period of time is
        not recommended — after a number of days equal to the
        character's Stamina, Essence alone is not sufficient to
        reinvigorate the Lunar. Each day thereafter, he must also
        spend a temporary Willpower, which he cannot recover
        without a prolonged period of sleep. After the Charm is
        discontinued, the Lunar must sleep for six hours for each
        day he was awake.
        "

    pain_numbing_prana["🌕 Pain-Numbing Prana"]
    click pain_numbing_prana callback "
        Pain-Numbing Prana<br>
        <br>
        Cost: 1 mote<br>
        Duration: Varies<br>
        Type: Reflexive<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        By utilizing this Charm, a Lunar can suppress superficial
        feelings of pain for a short period of time, overriding
        his nervous system. The duration of this Charm is equal
        in turns to twice the Lunar's Stamina + Endurance,
        during which time he may ignore any wound penalties
        imposed by bashing damage. However, he still suffers the
        effects of lethal and aggravated damage and is still
        rendered unconscious if his wounds (of any type) reach
        incapacitated.
        "

    will_of_the_stoic_warrior["🌕 Will of the Stoic Warrior"]
    pain_numbing_prana --> will_of_the_stoic_warrior
    click will_of_the_stoic_warrior callback "
        Will of the Stoic Warrior<br>
        <br>
        Cost: 2 motes<br>
        Duration: Varies<br>
        Type: Reflexive<br>
        Minimum Stamina: 4<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Pain-Numbing Prana<br>
        <br>
        Will of the Stoic Warrior allows the Lunar to suppress
        moderate to severe pain, such as the result of severe
        trauma, allowing him to ignore the dice pool penalties
        imposed by bashing or lethal damage. However, he still
        suffers the penalties imposed by aggravated damage and
        is still rendered unconscious if his wounds (of any type)
        reach incapacitated. The effects of this Charm last for a
        number of turns equal to the Exalt's Stamina + Endurance.
        "

    lunas_fortitude["🌕 Luna's Fortitude"]
    will_of_the_stoic_warrior --> lunas_fortitude
    click lunas_fortitude callback "
        Luna's Fortitude<br>
        <br>
        Cost: 4 motes<br>
        Duration: One turn<br>
        Type: Reflexive<br>
        Minimum Stamina: 5<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Will of the Stoic Warrior<br>
        <br>
        By calling on Luna's Fortitude, a Lunar ignores all
        wounds, period. Any wounds already present remain,
        and he may sustain new ones, but he suffers no action
        penalties while the Charm is in effect and is not rendered
        unconscious (or killed) no matter how far past incapacitated
        his injuries would take him. A character may
        sustain use of this Charm for a number of turns equal to
        his Stamina but must pay for the Charm in each turn.
        When the Charm ends, all wound effects immediately
        come into play; if the Lunar has suffered more points of
        lethal damage than he has health levels (including the
        health levels below Incapacitated provided by his
        Stamina), he dies immediately.
        "

    infection_resisting_method["🌕 Infection-Resisting Method"]
    click infection_resisting_method callback "
        Infection-Resisting Method<br>
        <br>
        Cost: 1 mote per die<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Stamina: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        Though diseases and infections are rarely a problem
        for the Exalted, the harsh lifestyles of the Lunar Exalted
        expose them to a wide range of contagions, and so, they
        have learned to use Essence to fortify their metabolisms.
        When making a roll to resist disease or infection, the
        Lunar's player may activate this Charm to convert
        Stamina dice into automatic successes. He may convert
        as many dice into successes as the Lunar has points of
        Stamina. The Infection-Resisting Method only helps to
        avoid disease; it does not help resist or to cure disease
        once the Lunar has become infected.
        "

    disease_purging_essence["🌕 Disease-Purging Essence"]
    infection_resisting_method --> disease_purging_essence
    click disease_purging_essence callback "
        Disease-Purging Essence<br>
        <br>
        Cost: 1 mote per die<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Infection-Resisting Method<br>
        <br>
        Using this Charm, a Lunar Exalted can purge his
        body of even the foulest plagues and infections. When
        rolling Stamina + Endurance to determine if the Lunar
        can overcome an infected wound or a disease, the Lunar's
        player can purchase additional dice up to the value of the
        character's Stamina Attribute.
        "

    bruise_relief_technique["🌕 Bruise Relief Technique"]
    infection_resisting_method --> bruise_relief_technique
    click bruise_relief_technique callback "
        Bruise Relief Technique<br>
        <br>
        Cost: 1 mote per health level<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: Infection-Resisting Method<br>
        <br>
        The minor contusions represented by bashing damage
        are of almost negligible concern to a Lunar Exalted,
        who, by exploiting his shapechanging abilities, can
        quickly repair bruises, sprains and related injuries. By
        expending Essence to power this Charm, the Exalt can
        cause her malleable flesh to repair damage. For every
        mote spent, the Exalt may remove one health level of
        bashing damage per point of Stamina, at a cost of 1 mote
        of Essence per health level. The Lunar does not have to
        repair all of his bashing damage with this Charm - he
        may leave some to heal naturally. To an observer, bruises
        and other superficial injuries simply fade away to leave
        unblemished skin. Characters may activate this Charm
        even if unconscious.
        "

    halting_the_scarlet_flow["🌕 Halting the Scarlet Flow"]
    bruise_relief_technique --> halting_the_scarlet_flow
    click halting_the_scarlet_flow callback "
        Halting the Scarlet Flow<br>
        <br>
        Cost: 2 motes per health level<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Stamina: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Bruise-Relief Technique<br>
        <br>
        By exploiting his shapeshifting abilities, a Lunar
        Exalted is able to quickly deal with cuts and other
        wounds, causing the flesh around gashes to flow together
        and broken bones to magically reknit. The Exalt may
        spend 2 motes to transform a level of lethal damage into
        bashing damage. A Lunar cannot heal more lethal damage
        in a turn than he has points of Stamina. In addition,
        if even one health level is healed, any bleeding wounds
        automatically close, preventing the loss of further health
        levels. The Lunar does not have to repair all of his lethal
        damage with this Charm — he may leave some to heal
        naturally. Observers will see the blood flow cease, wounds
        knit together and swelling subside. All that remains are
        scratches and bruising. Wounds healed with this Charm
        do not scar. Characters may activate this Charm even if
        unconscious and dying of mortal injury but cannot
        activate it if they are actually dead.
        "

    lick_wound["🌑 Lick Wound"]
    infection_resisting_method --> lick_wound
    click lick_wound callback "
        Lick Wound<br>
        <br>
        Cost: 2 motes per die<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Wits: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: Infection-Resisting Method<br>
        <br>
        Using this Charm while licking a subject's wounds
        or breathing vapors into her face allows the Lunar to use
        his own Essence to fortify an ally's resistance to infection.
        The player may purchase dice up to his character's
        Stamina and add them to the subject's efforts to resist
        infection or disease or her player's rolls to overcome
        illness or disease.
        "

    mothers_touch["🌑 Mother's Touch"]
    halting_the_scarlet_flow --> mothers_touch
    lick_wound --> mothers_touch
    click mothers_touch callback "
        Mother's Touch<br>
        <br>
        Cost: 2 or 3 motes per health level or 3 motes, 1 Willpower per health level<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Perception: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Halting the Scarlet Flow, Lick Wound<br>
        <br>
        By infusing his hands with Essence and touching a
        subject's wounds, a Lunar is able to heal or alleviate those
        wounds. These healing hands can remove bashing damage
        and transform lethal wounds into bashing. Mother's
        Touch also closes bleeding wounds, preventing the loss
        of additional health levels. Each level of bashing damage
        healed costs 2 motes of Essence, while each level of lethal
        transformed costs 3 motes. Mother's Touch can be used
        to transform aggravated damage (into lethal), but each
        health level removed costs 3 motes and a temporary
        Willpower point. With each use of Mother's Touch, the
        Lunar may transform/cure as many levels of damage as he
        has points of Stamina.
        "
