---
config:
  theme: dark
---
flowchart TD

    tentacles[Tentacles]
    click tentacles callback "
        Tentacles<br>
        <br>
        Cost: Varies<br>
        Duration: Instant<br>
        Type: Extra Action<br>
        Minimum Brawl: 3<br>
        Minimum Essence: 1<br>
        Prerequisite: None<br>
        <br>
        The Lunar pours Essence into one of her limbs, which
        splits into multiple, writhing tentacles. Anything held in
        that limb is dropped, but the Exalted's natural attacks
        function as normal. Each of the tentacles is capable of
        making a separate attack at the Exalted's full dice pool,
        although all must attack the same target. For each tentacle
        the Exalted wishes to create, she must spend 3 motes, and
        she cannot create more tendrils than her Essence. If the
        defender dodges, make one roll and apply it to all attacks.
        "

    mighty_thews[Mighty Thews]
    click mighty_thews callback "
        Mighty Thews<br>
        <br>
        Cost: 2 motes per point of Strength<br>
        Duration: Varies<br>
        Type: Simple<br>
        Minimum Brawl: 2<br>
        Minimum Essence: 2<br>
        <br>
        When she uses Essence to enhance her very muscles
        via this Charm, a Lunar seems to swell into an intimidating,
        muscular version of herself. Tendons stand out like
        taught rope, and her muscles seem ready to burst through
        her skin. The Exalted's player makes a Strength + Brawl
        roll. For every success, add one to her Strength. The
        character cannot more than double her initial Strength
        through the use of this Charm. The Charm's effect lasts for
        a number of turns equal to the character's Essence + the
        number of successes rolled.
        "
