---
config:
  theme: dark
---
flowchart TD

    strides_of_the_panther[Stride of the Panther]
    click strides_of_the_panther callback "
        Stride of the Panther<br>
        <br>
        Cost: 4 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Athletics: 3<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        The Lunar's legs shift into the likeness of the legs of a
        giant cat, and his whole body twists slightly, becoming
        lower and more streamlined. For the remainder of the
        scene, the character can move at twice his normal movement
        rate and leap three times his normal jumping distance.
        "
