---
config:
  theme: dark
---
flowchart TD

    acid_spit[Acid Spit]
    click acid_spit callback "
        Acid Spit<br>
        <br>
        Cost: 3 motes<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Thrown: 3<br>
        Minimum Essence: 1<br>
        Prerequisite: None<br>
        <br>
        The Lunar channels Essence into his own digestive
        system, momentarily transforming the acids within his
        stomach into something far viler. He can then spit this
        5 corrosive phlegm onto his opponent. The phlegm has a
        range of 10 yards and does a damage of 4L + extra successes.
        It continues to do the basic damage every turn until it is
        scraped off its victim, which requires a successful Dexterity
        + Athletics roll. This roll is not a reflexive one and must
        be made as a dice action.
        "
