---
config:
  theme: dark
---
flowchart TD

    summon_wild_beasts[Summon Wild Beasts]
    click summon_wild_beasts callback "
        Summon Wild Beasts<br>
        <br>
        Cost: 10 motes and 1 Willpower, +2 motes per creature<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Lore: 2<br>
        Minimum Essence: 2<br>
        Prerequisite: None<br>
        <br>
        The Exalted may summon creatures touched by the
        Wyld to him and direct them against his foe. The nature of
        the beast depends on the area where the summoning takes
        place. For example, in the Southwestern swamps, giant
        mutated toads may spring from the water to aid the Lunar.
        Each creature is around the size of a large dog, and the
        Exalted cannot summon more beasts than 10 times her
        Lore. See Exalted, p. 315, for creature statistics.
        "
