---
config:
  theme: dark
---
flowchart TD

    harrow_the_mind[Harrow the Mind]
    click harrow_the_mind callback "
        Harrow the Mind<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Conviction: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Through the use of this Charm, the spirit can create mental
        illusions that only the target can see. To do it, roll the spirit's
        Manipulation + Conviction. The first success creates the illusion,
        while additional successes make the illusion more difficult to
        penetrate. The target's player must make an Intelligence + Temperance
        roll and must gain a number of successes at least equal to
        the number of successes the spirit rolled. If not, the target is unable
        to tell the illusion from reality. He may make additional Intelligence
        + Temperance rolls whenever the illusion departs wildly
        from what the target expects from reality, making believable
        illusions much more difficult to see through. Once the illusion has
        been penetrated, it is dispelled, and all further uses of the Charm
        on that being are at + 1 difficulty for the next several days.
        "

    possession[Possession]
    click possession callback "
        Possession<br>
        <br>
        Cost: 3 motes, 1 Willpower
        Duration: One scene
        Type: Simple
        Minimum Conviction: 4
        Minimum Essence: 1
        Prerequisite Charms: None<br>
        Roll the spirit's Manipulation + Conviction in an extended
        resisted action against the target's Willpower. When the spirit
        gains more successes than the victim has temporary Willpower,
        the spirit takes possession of the target for the rest of the scene.
        Successes accumulate for the duration of the scene. More
        powerful versions of this Charm exist, which allow spirits to
        &quot;hollow out&quot; a being's soul and possess him indefinitely.
        "

    stoke_the_flame[Stoke the Flame]
    click stoke_the_flame callback "
        Stoke the Flame<br>
        <br>
        Cost: 1 mote per die<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Conviction: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The spirit channels Essence into the victim to inflame her
        emotional state. One success merely aggravates whatever
        condition is already present, while three or more successes
        cause the target to completely lose herself in the emotion of the
        moment. You may roll no more dice that the spirit's Convic-
        tion. Used against one of the Exalted, this Charm causes the
        character's Limit to increase by one point per success.
        "

    instill_obedience[Instill Obedience]
    stoke_the_flame --> instill_obedience
    click instill_obedience callback "
        Instill Obedience<br>
        <br>
        Cost: 10 motes, 1 Willpower<br>
        Duration: One day<br>
        Type: Simple<br>
        Minimum Conviction: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Stoke the Flame<br>
        <br>
        The spirit channels Essence into the target to alter his
        emotional state, instilling within him a desire to obey the
        spirit. Roll the spirit's Charisma + Conviction with a
        difficulty equal to the target's Essence. Simple success
        merely makes the target slightly more likely to obey, while
        three successes forces him to obey completely unless such
        obedience would cause him physical harm. At five successes,
        the target does anything the spirit commands.
        "

    geas[Geas]
    instill_obedience --> geas
    click geas callback "
        Geas<br>
        <br>
        Cost: 1 mote per day (Min 15, Max 28), 2 Willpower<br>
        Duration: One to 28 days<br>
        Type: Simple<br>
        Minimum Conviction: 5<br>
        Minimum Essence: 4<br>
        Prerequisite Charms: Instill Obedience<br>
        This Charm allows a spirit to lay a Geas, or bond, upon
        a target. It requires eye contact and a successful Manipulation
        + Conviction check, with at least three successes,
        The spirit may order the target to perform one task, which
        may include such broad orders as &quot;serve me for one month.&quot;
        The spirit may not order the target to do something that
        would directly harm the target, but it may order him to
        attempt a difficult or dangerous goal as long as there is a
        reasonable chance of success (Storyteller's discretion).
        This Charm has a minimum cost of 15 motes, even if it is
        to last only one day. This Geas does not completely govern
        the target's actions; rather, it gives the target a compulsion
        to work toward the task he has been given. For each day
        that the target fails to work in good faith toward the task,
        he loses one temporary Willpower and takes one health
        level of aggravated damage. For each two days spent
        working in good faith toward the task, he regains one
        health level lost from for disobeying the Geas.
        "

    lend_authority[Lend Authority]
    instill_obedience --> lend_authority
    click lend_authority callback "
        Lend Authority<br>
        <br>
        Cost: 15 motes<br>
        Duration: 1 day x the spirit's Willpower<br>
        Type: Simple<br>
        Minimum Conviction: 3<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Instill Obedience<br>
        <br>
        For each success on a Conviction + Presence check,
        the spirit may raise an individual's Presence by one dot.
        The spirit may not increase the target's Presence by more
        dots than the spirit's Essence, although it may increase it
        above 5. Only one use of this Charm may be active on an
        individual at any given time. The Presence lasts for one
        day for each dot of the spirit's Willpower.
        "

    world_of_illusion[World of Illusion]
    harrow_the_mind --> world_of_illusion
    click world_of_illusion callback "
        World of Illusion<br>
        <br>
        Cost: 20 motes, 1 Willpower per person<br>
        Duration: Instant<br>
        Type: Reflexive<br>
        Minimum Conviction: 4<br>
        Minimum Essence: 3<br>
        Prerequisite Charms: Harrow the Mind<br>
        <br>
        The target of this Charm finds herself in an illusory
        world of the spirit's design. The illusion is total and covers
        all senses — according to all of her senses, the target has
        been transported elsewhere. The illusion has a nearly
        instant duration but may appear to last tor up to one day to
        the mind of the target.<br>
        This Charm requires the spirit to touch its target (a
        nonreflexive Dexterity + Brawl or Martial Arts roll if she's
        actively evading) or look in her eyes. The spirit may use
        this effect on multiple people at once, but all of them must
        find themselves in the same illusion, and the spirit must
        touch all of them at once.<br>
        Any damage the target takes within the hallucination
        is purely illusory. However, if the target dies within the
        illusion, then her player must succeed on a Stamina +
        Resistance roll or fall into a coma for one day per point of
        the spirit's Essence (or longer, at the Storyteller's discretion,
        if it suits the dramatic needs of the story).
        "
