---
config:
  theme: dark
---
flowchart TD

    subgraph Players Guide
        investiture_of_infernal_glory[Investiture of Infernal Glory]
        click investiture_of_infernal_glory callback "
            Investiture of Infernal Glory<br>
            <br>
            Cost: 60 motes, 6 Willpower<br>
            Duration: Until completed<br>
            Type: Simple<br>
            Minimum Compassion: 3<br>
            Minimum Conviction: 5<br>
            Minimum Valor: 4<br>
            Minimum Essence: 7<br>
            Prerequisite Charms: Endowment, Geas, Memory Transference, Scourge<br>
            <br>
            With this Charm, a Demon Prince may stain an
            Exalted Essence to create a prince among akuma. The rite
            cannot begin until the Exalt submits his will to the demon,
            forfeiting part of his soul with a prayer of supplication that
            costs him a point of permanent Willpower. Such a sacrifice
            cannot be coerced or obtained with deception, but must be
            an act of genuine free will. It is the last act of free will the
            Exalt will ever know.<br>
            With this sacrifice, the demon infuses the subject
            with torturous power and reshapes him to better suit its
            monstrous will. Any Traits that may be purchased or raised
            in play may be cannibalized to yield the number of experience
            points it would cost to obtain the Trait in its current
            state. Thus, the character's Wits of 4 could yield 12
            experience points as it dropped to 3, while a specialty
            would yield 3 experience points. The demon chooses how
            to reassign these experience points to modify the character
            as much or as little as desired, but it must spend them all.
            Anything leftover at the end of the process is lost. It is
            possible to rebuild an Exalt from scratch, though most
            Demon Princes only make artful adjustments.<br>
            Such modifications are very quick, taking a number of
            hours equal to the experience point cost of the new or
            improved Trait to implement, but the changes are also
            excruciating ordeals involving torture, soul-branding,
            mental rape, forced re-healing and other freakishly alien
            torments. The Exalt may have his flesh turned inside out
            so the demon can twist muscles from Strength to Dexterity
            or have the beliefs of his Virtues torn asunder to
            accommodate the influx of Ability tutoring inscribed
            upon his brain.<br>
            When the process of reshaping the Exalt is complete,
            the Demon Prince imbues him with the Essence of
            the Demon Realm. This involves a new round of torments
            lasting a number of days equal to the Exalt's
            Essence rating. At the conclusion of this period, the
            character gains Inheritance 5 and Patron 5 and becomes
            an akuma Demon-Blood.<br>
            The Demon Prince immediately spends the 30
            bonus points in a new round of customization, and may
            further increase this number by assigning Flaws with a
            combined value no greater than (20 - the total value of
            the character's current Flaws). The demon also assigns
            the 17 additional points of Backgrounds awarded by
            Patron according to the intended function of the akuma.
            This concludes the ritual and the Charm, forever branding
            the Infernal Exalt as a slave of the Demon Realm.
            An Exalted akuma receives several unique advantages.
            First, the maximum cap on all Attributes and
            Abilities increases by one. An Exalt with Essence 1-5 can
            raise these Traits to 6, while more powerful Exalted can
            reach ratings equal to their Essence + 1. The Demon
            Prince can and often does exploit these heightened thresh-
            olds during the process of reshaping and empowering the
            akuma, but the Exalt may also take advantage of them
            with experience points. See page 259 of this book for
            details of experience costs beyond the Essence 5 mark.<br>
            Second, the character may learn spirit Charms like
            any Demon-Blood during the initial transformation or
            later with experience points at the same cost as normal
            Charms for his Exalted type. However, like Essence and
            other magical Traits, these Charms are subject to the
            Inheritance penalty imposed on all Exalted God-Blooded.
            The character's anima may remain eerily the same or
            twisted to reflect whatever aspect of the Demon Realm
            the master desires. Those with terrible Infernal animas
            may cause derangements in ordinary mortals who behold
            their iconic splendor. Lastly, an akuma is no longer a part
            of fate and receives the protection of that state from the
            divinations and astrological manipulations of the Sidereals.<br>
            Exalted akuma pay a heavy price for their power.
            They cannot disobey their masters or any Yozi, even if
            ordered to commit suicide or to murder former loved
            ones. Nor may they ever escape their masters. At any
            time and in any place, the Demon Prince who made
            them can borrow their senses or voice and may issue
            irresistible telepathic commands. Even if the Demon
            Prince grants the illusion of autonomy by choosing to
            convey suggestions rather than orders, it is a thin lie at best.
            The truth is slavery, absolute and eternal, to the end of the
            Exalt's long days.<br>
            Akuma cannot be redeemed or cleansed of the Yozi's
            taint. This corruption even follows Celestial Exalted into
            future incarnations of their Essence, though their succes-
            sors do not begin their lives as Infernal Exalted. Instead,
            these unfortunate souls must take a five-point version of
            the Flaw Throwback (see p. 41) in which their Essence
            Nature is a Follower seeking slavery with the Yozis. Exalted
            can fight this siren song, but the temptation remains until
            they die. Each subsequent incarnation reduces the value of
            the Throwback by two points until the taint wears off
            completely or one of the Chosen falls into the damnation
            of her forbear.<br>
            Fortunately for Creation, very few Exalted even know
            this Charm exists, and fewer still may visit Malfeas to
            undergo the change. Knowing about the benefits of life as
            an akuma requires a difficulty 6 Intelligence + Occult roll.
            Knowing the price is difficulty 8.
            "
    end
