---
config:
  theme: dark
---
flowchart TD

    cunning_thief[Cunning Thief]
    click cunning_thief callback "
        Cunning Thief<br>
        <br>
        Cost: 1 mote per 2 dice<br>
        Duration: Instant<br>
        Type: Simple<br>
        Minimum Temperance: 2<br>
        Minimum Essence: 1<br>
        Prerequisite Charms: None<br>
        <br>
        The spirit must touch the target for this Charm to
        work (resolved by a normal Dexterity + Brawl or Martial
        Arts check). If the attempt to touch the target is successful,
        make a reflexive Wits + Temperance roll. For every success
        the spirit achieves, the target loses two motes of Essence.
        The spirit cannot steal more motes than twice its Essence.
        "

    host_of_spirits[Host of Spirits]
    click host_of_spirits callback "
        Host of Spirits<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Temperance: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Through the use of this Charm, the spirit forms mul-
        tiple images of itself to deceive attackers. This ability works
        much like Harrow the Mind, above. However, there are
        more images and they are harder to distinguish from reality.
        Make an Intelligence + Temperance roll for the spirit,
        opposed by the target's Perception + Awareness. If the
        target garners fewer successes than the spirit, he sees many
        false images of the small god, each virtually indistinguishable
        from the real being. Attacks by individuals so befuddled
        have only (their Essence) in 10 chance of actually striking
        the spirit. Make another Perception + Awareness for those
        observing the spirit every time the spirit attacks.
        "
