---
config:
  theme: dark
---
flowchart TD

    essence_bite[Essence Bite]
    click essence_bite callback "
        Essence Bite<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Valor: 3<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        The spirit must touch its target for this Charm to
        work, requiring a successful Dexterity + Brawl or Martial
        Arts roll. If the touch attempt is successful, make a
        reflexive Valor + Essence roll for the spirit. For every
        success on the attack, the spirit does a point of lethal
        damage. The character's armor soak applies as normal to
        this damage, and extra successes on the attack roll add to
        damage as usual.<br>
        This Charm may rely on heat, cold, life-draining or
        any number of other mechanisms to do damage —
        almost all have secondary effects that the spirit can
        manipulate to its advantage. For example, a ghost that
        can start fires with its fiery touch can burn down a barn
        with this Charm.
        "

    materialize[Materialize]
    click materialize callback "
        Materialize<br>
        <br>
        Cost: Varies<br>
        Duration: Indefinite<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        Through the use of this Charm, the spirit can materialize
        in the physical world. The cost of this Charm is between 50
        percent and 100 percent of the spirit's temporary Essence.
        The cost varies from spirit to spirit and is listed in the spirit's
        description or assigned by the Storyteller. Generally, as the
        power of the spirit grows, the spirit must expend proportionally
        greater amounts of Essence to materialize.
        In most cases, a spirit that plans to meddle in mortal
        affairs will materialize in some safe area and then rest,
        regaining its Essence, before it goes about its business. Spirits
        that have not materialized cannot affect the physical world, not
        with Charms, physical attacks or in any other fashion.
        "

    principle_of_motion[Principle of Motion]
    click principle_of_motion callback "
        Principle of Motion<br>
        <br>
        Cost: 5 motes, 1 Willpower<br>
        Duration: Until used<br>
        Type: Extra Action<br>
        Minimum Valor: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        When the spirit uses this Charm, it gains a pool of extra
        actions equal to its Valor. Actions in this pool can be expended
        for extra attacks on the spirit's initiative or reflexively, to parry or
        dodge an attack or to refresh the spirit's Dodge pool when using
        the full dodge maneuver. If the spirit does not use all the actions
        in its pool, they remain available for it in the following turn.
        Actions in the pool will persist for many months, and many spirits
        make sure they retain a full complement of actions in case they
        are ambushed. A spirit cannot use this Charm again until it has
        used up all the extra actions granted by the last use of the Charm.
        While the spirit has extra actions in its pool, the motes of Essence
        used to power this Charm are considered committed.
        "

    words_of_power[Words of Power]
    click words_of_power callback "
        Words of Power<br>
        <br>
        Cost: 3 motes<br>
        Duration: One scene<br>
        Type: Simple<br>
        Minimum Valor: 2<br>
        Minimum Essence: 2<br>
        Prerequisite Charms: None<br>
        <br>
        The spirit may intone blasphemies, keen out the lamentations
        of the dead or speak the victim's true name, but
        regardless, its words are like a battering ram. The spirit attacks
        using Charisma + Valor to hit the opponent and does bashing
        damage equal to the spirit's Strength, which can be soaked
        only by the target's Stamina. Extra successes on the attack add
        to damage, as usual. For every health level of damage the
        target takes, he is at a - 1 penalty to all dice pools for a number
        of turns equal to the attacking spirit's Essence.
        This attack may be dodged or blocked as normal but
        has no physical effects except perhaps causing blood to
        flow from the target's ears or hurling him bodily through
        light obstructions.
        "

    subgraph Players Guide
        dematerialize[Dematerialize]
        click dematerialize callback "
            Dematerialize<br>
            <br>
            Cost: Varies<br>
            Duration: Indefinite<br>
            Type: Simple<br>
            inimum Valor: 2<br>
            inimum Essence: 2<br>
            Prerequisite Charms: None<br>
            <br>
            Through the use of this Charm, an elemental may
            transmute its flesh and personal belongings into spiritual
            Essence, thereby assuming an incorporeal state. Dematerialized
            elementals may perceive and interact with other
            incorporeal beings as if both were solid, either magically or
            with touch. However, immaterial beings are utterly undetectable
            to physical beings and cannot directly affect the physical
            world in any way without Charms or other powers intended
            for such use (such as Possession, Will-o-Wisp etc.).
            Dematerialized elementals with Essence 2+ can spend
            1 mote to manifest for a scene as a translucent phantom of
            themselves and speak in a quiet voice or whisper, exactly
            as normally immaterial spirits can do as an innate ability.
            As always, the Storyteller remains the final arbiter of
            whether a particular power may affect the physical world
            from a dematerialized state. This lack of physical interac-
            tion also allows an incorporeal elemental to effortlessly
            pass through solid walls and other material obstructions,
            though appropriate magical wards can still bar their path
            The cost of this Charm is normally between 50
            percent and 100 percent of the elemental's total
            available Essence pool. For elementals without a
            listed cost to dematerialize, the percentage cost of
            total Essence they must expend equals their (Essence
            rating x 5) + 45, rounded up. For example, a spirit
            with Essence 2 and an available pool of 48 motes pays
            27 motes (55 percent).<br>
            Eclipse Caste Solars and Moonshadow Caste Abyssals
            who learn this Charm also calculate their cost according to
            the preceding formula without applying the usual double
            cost modifier for learning spirit Charms, determining the
            value according to a percentage of their total Essence pool
            (Personal + Peripheral). The half-spirit descendents of
            gods, elementals and demons do not pay a percentage of
            their total pool, instead paying a cost of their (Essence
            rating x 5) + 5 motes.<br>
            Unlike other Charms of non-instant duration, De-
            materialize does not require that elementals commit the
            Essence cost to sustain the magic. However, beings that
            normally exist in a material state cannot regain Essence
            through respiration while Dematerialized (and vice versa
            for immaterial spirits who materialize). Instead of com-
            mitting Essence, beings using this Charm must pay half
            the normal cost each day at sunrise as a reflexive upkeep,
            rounded up. Failure to pay this upkeep immediately ends
            the effects of the Charm. Otherwise, characters must
            spend a dice action reverting back to their natural state,
            though success is automatic.<br>
            The rules printed here expand upon and supersede
            those for the Materialize Charm in Exalted and apply in
            reverse for that Charm.
            "
    end

