---
config:
  theme: dark
---
flowchart TD

    subgraph Games of Divinity
        uncanny_prowess[Uncanny Prowess]
        click uncanny_prowess callback "
            Uncanny Prowess<br>
            <br>
            Cost: 2 motes<br>
            Duration: Special<br>
            Type: Reflexive<br>
            Minimum Valor: 2<br>
            Minimum Essence: 1<br>
            Prerequisite Charms: None<br>
            <br>
            The spirit may add a number of dice equal to its Valor
            score to a single Dexterity roll. This roll could be anything
            from a single blow with a weapon to a single performance or
            even to the roll to create a single piece of fine jewelry. When
            used for longer endeavors, this Charm adds dice to each roll
            of a single extended action. However, it can only be used on
            one endeavor at a time, the Essence invested in this Charm
            cannot be regained, and the Charm cannot he recast until
            the task has been completed or abandoned.
            "

        creation_of_perfection[Creation of Perfection]
        click creation_of_perfection callback "
            Creation of Perfection<br>
            <br>
            Cost: 2 motes<br>
            Duration: Special<br>
            Type: Simple<br>
            Minimum Valor: 2<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: None<br>
            <br>
            This Charm allows spirits to create supernaturally exquisite
            items or to perform feats of inhuman skill with various crafts.
            When using this charm, roll Intelligence + Valor for the spirit.
            Every success gained on this roll can be added to a single Craft,
            Medicine, Occult or Larceny roll designed to create an item or to
            carry out a slow and careful process such as performing surgery,
            compounding a drug, putting on a disguise or creating a magical
            talisman. This Charm cannot be used to enhance any task that
            requires speed or haste such as picking a lock before the guard
            arrives, stopping someone from bleeding to death or any form of
            combat. It can also only be used on tasks that require both clear
            thought and nimble fingers. No activity can simultaneously
            benefit from both this Charm and the Uncanny Prowess Charm.
            "

        spirit_cutting[Spirit-Cutting]
        click spirit_cutting callback "
            Spirit-Cutting<br>
            <br>
            Cost: 1 mote<br>
            Duration: Instant<br>
            Type: Supplemental<br>
            Minimum Valor: 3<br>
            Minimum Essence: 2<br>
            Prerequisite Charms: None<br>
            <br>
            This Charm allows a materialized spirit to launch a
            single attack at an unmanifested spirit. For the purposes of
            the individual attack, the small god attacks the immaterial
            spirit normally.
            "
    end
